#@中文 (Chinese)

# -- generic --
$1 Rule(s);$1 规则(s)
Blank Game;空白游戏
Custom;风俗
Default;默认
Disabled;不显示
Empty;空
False;错误的
Multi;多
No Sort;不排序
No;否
None;没有
Off;离开
On;在
OR;或
True;真的
Yes;是
Import;进口
Cancel;取消

# -- misc --
Press TAB to Configure;按 TAB 键进行配置
Displays Menu Options;界面选择器设置
Action;项目
Add Artwork;添加插图
Add Emulator;添加模拟器
Add Exception;添加例外
Add Filter;添加分类
Add Input;添加输入
Add Display;添加显示
Add Rule;添加规则
Allow Exit;允许退出
Anisotropic Filtering;各向异性滤波
Anti-Aliasing (MSAA);抗锯齿 (MSAA)
Artwork Label;插图标签
Artwork Name;作品名称
Artwork Path;插图路径
Auto-detect Emulators;自动检测模拟器
Check for Updates;检查更新
Collection/Romlist;收集/游戏列表
Comparison;比较
Confirm Exit;确认退出
Confirm Favourites;设置收藏
Controls;控制器
Add Tag;添加标签
Custom Arguments;自定义参数
Custom Executable;自定义可执行文件
Custom Overlay;自定义叠加层
Default Action;默认动作
Delete this Display;删除界面
Delete this Emulator;删除模拟器
Delete this Filter;删除排序
Delete this Game;删除此游戏
Delete this Rule;删除规则
Delete this Shortcut;删除此快捷方式
Displays;界面
Emulator Name;模拟器名称
Emulators;模拟器
Multiple Monitors;多显示器
Enabled;显示
Exception;其他 Exception
Exit Attract-Mode Plus;退出Attract-Mode Plus
Exit Attract-Mode Plus?;退出Attract-Mode Plus吗?
Exit Command;退出指令
Exit Message;退出信息
Filter Name;分类名称
Filter Value;分类内容
Filter Wrap Mode;分类切换模式
Filter;分类
Settings;设置
Global Filter;全局分类
Group Clones;分组克隆
Hide Game Title Brackets;隐藏比赛标题括号
Format Game Title;格式化游戏标题
Hide Console;隐藏控制台
Image Cache Size;图像缓存大小
Insert Command Shortcut;插入命令快捷方式
Insert Display Shortcut;插入显示快捷方式
Insert Game Entry;插入游戏条目
Insert Menu Entry;插入菜单条目
Joystick $1;摇杆 $1
Joystick Mappings;摇杆映射
Joystick Threshold;操纵杆的阈值
Language;语言
Layout File;布局文件
Layout Preview;布局预览
Layout;布局
List Limit;列表大小限制
Menu Colour;菜单颜色
Menu Prompt;标题
Menu Toggle;菜单切换
Mouse Threshold;鼠标的阈值
Overview;概览
Plugins;插件
Power Saving;省电模式
Remove Input;移除-设置按键
Reverse Order;反向播放
Rule;规则
Scrape Artwork;搜刮插图
Scrape Fanart;搜刮玩家自制 (Fanart)
Scrape Flyers/Boxart;搜刮传单/手办 (Flyers/Boxart)
Scrape Game Logos (Wheel Art);搜刮LOGO (Wheel Art)
Scrape Marquees;搜刮跑马灯 (Marquees)
Scrape Snaps;搜刮快照 (Snaps)
Scrape Videos (MAME only);搜刮 Videos (MAME only)
Scraper;搜刮器
Screen Rotation;屏幕旋转
Screen Saver Timeout;屏保等待时间
Selection Speed;选择速度
Selection Delay;选择延迟
Selection Max Step;选择最大步进
Show in Cycle;在界面切换转轮中显示
Show in Menu;在界面选择菜单中显示
Sort By;排序方式
Sort Only;仅排序
Sort and Show;排序并显示
Sound;声音
Startup Mode;启动模式
Target;规则的目标
Title;标题
Game Stats;游戏统计数据
Video Decoder;视频解码
Window Mode;窗口模式
Added $1 Collection/Romlist entries;已添加 $1 收藏/ROM 列表条目

# -- indexStrings --
Name;名称
Title;标题
Emulator;模拟器
CloneOf;克隆
Year;年
Manufacturer;制造商
Category;类别
Players;玩家
Rotation;旋转
Control;控制器
Status;地位
DisplayCount;界面数量
DisplayType;界面各类
AltRomname;Rom名称
AltTitle;标题
Extra;其他信息
Buttons;按钮
Series;系列
Language;语言
Region;区域
Rating;评分
Favourite;收藏
Tags;标签
PlayedCount;游戏计数
PlayedTime;游戏时间
PlayedLast;上次游玩时间
FileIsAvailable;文件可用
Shuffle;随机播放

# -- filterCompDisplayStrings --
contains;包含
does not contain;不包含
does not equal;不等于
equals;等于
greater than;大于
less than;小于
greater than or equal;大于或等于
less than or equal;小于或等于

# -- commandDispStrings --
Back;返回
Up;向上
Down;向下
Left;左
Right;右
Select;选择
Previous Game;上一游戏
Next Game;下一游戏
Previous Page;上一页
Next Page;下一页
Previous Display;上一界面
Next Display;下一界面
Displays Menu;显示器菜单
Previous Filter;上一分类
Next Filter;下一分类
Filters Menu;分类管理菜单
Toggle Layout;切换布局
Toggle Movie;切换影片
Toggle Mute;静音
Toggle Rotate Right;向右旋转切换
Toggle Flip;切换翻转
Toggle Rotate Left;切换向左旋转
Exit;退出
Exit to Desktop;退出到桌面
Reload Layout;重新加载布局
Reload Config;重新加载配置
Reset Window;重置窗口
Screenshot;截图
Random Game;随机游戏
Replay Last Game;重新上一次的游戏
Toggle Fullscreen;切换全屏
Add/Remove Favourite;添加/移除收藏
Previous Favourite;上一收藏
Next Favourite;下一收藏
Add/Remove Tags;添加/移除标签
Screen Saver;屏保
Previous Letter;上一关键词
Next Letter;下一关键词
Intro;启动画面
Insert Game;插入游戏
Layout Options;布局选项
Plugin Options;插件选项
Custom1;用户 1
Custom2;用户 2
Custom3;用户 3
Custom4;用户 4
Custom5;用户 5
Custom6;用户 6
Custom7;用户 7
Custom8;用户 8
Custom9;用户 9
Custom10;用户 10
Ambient Soundtrack;环境音
Startup Sound;启动声音
Game Return Sound;游戏返回声音

# --uiColorDispTokens --
Indigo;靛蓝
Blue;蓝色
Cyan;青色
Turquoise;绿松石色
Green;绿色
Acid;酸性
Gold;金色
Yellow;黄色
Orange;橙色
Brown;棕色
Rust;锈色
Red;红色
Pink;粉色
Magenta;洋红色
Purple;紫色
Grey;灰色
Neutral;中性色
White;白色

# --windowModeDispTokens --
Fill Screen;铺满屏幕
Fullscreen;全屏
Window;窗口化
Borderless Window;无边框窗口

# --screenRotationDispTokens --
Flip;翻动

# --startupDispTokens --
Show Last Selection;显示最后的选择
Show Random Selection;显示随机选择
Launch Last Game;载入最后一次运行的游戏
Show Displays Menu;界面选择器

# --filterWrapDispTokens --
Wrap within Display;该列表的第一个过滤器
Jump to Next Display;跳到下一界面
No Wrap;不切换

# -- settingDispStrings --
Sound Volume;声音音量
Ambient Volume;环境音量
Movie Volume;视频音量
Loudness Normalisation;响度标准化

# -- splash_message --
Generating Romlist;ROM列表生成中
Please Wait;请稍候
Scraping Artwork;正在搜刮 插图

# -- confirm_dialog --
Add '$1' to Favourites?;添加 '$1' 到收藏?
Auto-detect emulators?;自动检测模拟器?
Found 1 emulator;找到 1 个模拟器
Found $1 emulators;找到 $1 个模拟器
No emulators found;未找到模拟器
+$1 more;还有$1个
Clear Hotkey?;清除热键?
Delete display '$1'?;删除 '$1' 界面?
Delete emulator '$1'?;删除 '$1' 模拟器?
Delete filter '$1'?;删除 '$1' 分类?
Delete game '$1'?;删除游戏'$1'?
Delete shortcut '$1'?;删除快捷方式'$1'?
Overwrite existing '$1' list?;覆盖现有的 '$1' 列表?
Remove '$1' from Favourites?;从收藏中先锋队 '$1'?
Rom path '$1' not found, proceed?;未找到 ROM 路径“$1”,是否继续?
Overwrite existing '$1' mapping?;覆盖现有的“$1”映射?
A display with this name already exists;此名称的显示已存在
Configuration files have been migrated\n to the 'config' folder.\nDelete old files?;配置文件已迁移到 'config' 文件夹。\n是否删除旧文件？

# --input_map_dialog --
Press Hotkey;按下热键
Press Input;按下-设置按键

# -- edit_dialog --
Enter Display Name;进入显示器名称
Enter Emulator Name;进入模拟器名称
Enter Filter Name;进入排序名称
Enter Tag Name;输入新标签名称
Enter Romlist Name;输入 ROM 列表名称

# -- Titles --
Configure;设置
Default Display Options;默认显示选项
Display Options;显示选项
Artwork Options;美术素材选项
Control Options;控制选项
Emulator Options;模拟器选项
Game Options;游戏选项
Shortcut Options;快捷键选项
Exception Options;例外选项
Filter Options;筛选选项
Rule Options;规则选项
Generate Collection/Romlist;生成收集ROM列表

# --indexDispStrings --
Executable;执行
Command Arguments;命令及参数
Working Directory;工作目录
Rom Path(s);ROM路径
Rom Extension(s);ROM扩展
System Identifier;系统标识
Info Source/Scraper;信息源/搜刮
Additional Import File(s);导入附加文件
Non-Blocking Mode Wait;非阻塞模式等待
Exit Hotkey;退出热键
Pause Hotkey;暂停热键

# -- datetime --
_datetime;%Y年%m月%d日 %H:%M:%S
A Moment Ago;刚才
Never;从不
$1 Second;$1秒
$1 Minute;$1分钟
$1 Hour;$1小时
$1 Day;$1天
$1 Minute Ago;$1分钟前
$1 Hour Ago;$1小时前
$1 Day Ago;$1天前
$1 Week Ago;$1周前
$1 Month Ago;$1个月前
$1 Year Ago;$1年前
$1 Seconds;$1秒
$1 Minutes;$1分钟
$1 Hours;$1小时
$1 Days;$1天
$1 Minutes Ago;$1分钟前
$1 Hours Ago;$1小时前
$1 Days Ago;$1天前
$1 Weeks Ago;$1周前
$1 Months Ago;$1个月前
$1 Years Ago;$1年前

# -- help --
_help_art_add;添加新的素材资源(跑马灯图像、屏幕截图等)
_help_art_label;标识此美术资源的标签(供布局使用)
_help_art_path;此美术素材文件的路径。多个路径可以用分号分隔。
_help_art;可供布局使用的美术资源
_help_back;退出菜单
_help_control_add_favourite;设置用于将当前选定的游戏标记为收藏/取消标记的控件。
_help_control_add_tags;设置向当前选定游戏添加/删除标签的控件
_help_control_back;设置返回按钮。
_help_control_configure;设置显示“配置菜单”的控件
_help_control_custom1;设置“Custom1”控件
_help_control_custom10;设置“自定义 10”控件
_help_control_custom2;设置“Custom2”控件
_help_control_custom3;设置“Custom3”控件
_help_control_custom4;设置“自定义4”控件
_help_control_custom5;设置“自定义5”控件
_help_control_custom6;设置“自定义6”控件
_help_control_custom7;设置“自定义7”控件
_help_control_custom8;设置“Custom8”控件
_help_control_custom9;设置“Custom9”控件
_help_control_displays_menu;设置显示“显示菜单”的控件
_help_control_down;设置用于向下移动选区的控件
_help_control_edit_game;设置用于编辑当前选择的控件
_help_control_exit_to_desktop;设​​置用于立即退出前端并返回桌面的控件
_help_control_exit;设置退出前端的控件
_help_control_filters_menu;设置显示“筛选菜单”的控件
_help_control_insert_game;设置插入新游戏条目的控件
_help_control_intro;设置显示开场动画的控件
_help_control_joystick_map;将前端的操纵杆插槽映射到特定位置连接到您计算机的已命名游戏手柄/操纵杆设备(例如, 您可以使用此选项强制前端始终使用“Microsoft X-Box 360 手柄”作为操纵杆 0)。
_help_control_joystick_threshold;注册摇杆移动的阈值, 范围从 1 到 100(100 为最低灵敏度)
_help_control_layout_options;设置显示“布局选项”菜单的控件
_help_control_plugin_options;设置显示上次查看的插件的“插件选项”菜单的控件
_help_control_left;设置将选区向左移动的控件
_help_control_mouse_threshold;鼠标移动的灵敏度阈值, 范围从 1 到 100(100 表示灵敏度最低)
_help_control_next_display;设置跳转到下一个显示器的控件
_help_control_next_favourite;设置切换到下一个收藏项的控件
_help_control_next_filter;设置移动到下一个筛选器的控件
_help_control_next_game;设置切换到下一个游戏的控件
_help_control_next_letter;设置移动到下一个字母的控件
_help_control_next_page;设置用于将选择向上移动一页的控件
_help_control_prev_display;设置切换到上一个显示区域的控件。
_help_control_prev_favourite;设置移动到上一个收藏夹的控件
_help_control_prev_filter;设置跳转到上一个筛选器的控件
_help_control_prev_game;设置切换到上一游戏的控件
_help_control_prev_letter;设置移动到上一个字母的控件
_help_control_prev_page;设置向下滚动一页的控件
_help_control_random_game;设置从当前列表中选择随机游戏的控件
_help_control_reload_layout;设置用于重新加载当前布局的控件布局
_help_control_reload_config;设置重新加载配置文件的控件
_help_control_reset_window;设置重置窗口大小和位置的控件
_help_control_replay_last_game;设置重新启动上次玩的游戏的控件
_help_control_right;设置向右移动选区的控件
_help_control_screen_saver;设置启动屏幕保护程序模式的控件
_help_control_screenshot;设置截取前端屏幕截图的控件
_help_control_select;设置启动当前选择的控件
_help_control_selection_speed;设置选择移动的速度,单位为毫秒/步, 默认值为 40
_help_control_selection_delay;设置按键重复开始前的延迟时间(毫秒), 默认值为 400
_help_control_selection_max_step;设置选择移动的最大步进大小, 默认值为 128
_help_control_toggle_flip;设置用于切换显示屏是否旋转180度的控件
_help_control_toggle_fullscreen;在全屏和窗口模式之间切换
_help_control_toggle_layout;设置切换要使用的布局脚本的控件(是否生效取决于您使用的布局)
_help_control_toggle_movie;设置切换是否播放视频的控件
_help_control_toggle_mute;设置用于静音/取消静音前端声音的控件
_help_control_toggle_rotate_left;设置切换是否将显示屏向左旋转 90 度的控件左
_help_control_toggle_rotate_right;设置用于切换显示器是否向右旋转 90 度的控件
_help_control_up;设置用于上移选择框的控件。
_help_display_add_filter;向此显示器的过滤器集添加过滤器
_help_display_add;添加新显示器
_help_display_delete;删除此显示
_help_display_filter;从显示器的过滤器集中配置此过滤器
_help_display_global_filter;配置应用于此显示收藏/ROM列表中所有条目的全局筛选规则
_help_display_in_cycle;是否将此显示包含在“上一个显示”/“下一个显示”循环中
_help_display_in_menu;是否将此显示添加到“显示菜单”中
_help_display_layout_options;配置任何特定于布局的选项
_help_display_layout;此显示使用的布局
_help_display_name;此显示的标题
_help_display_romlist;用于此显示的 ROM 列表
_help_display_sel;配置显示
_help_display_edit_default;配置新显示器的默认选项
_help_displaysmenu_exit;配置是否在显示菜单中提供“退出”选项
_help_displaysmenu_layout;显示菜单的布局。设置为“默认”以使用前端的内置菜单
_help_displaysmenu_prompt;显示菜单提示(例如“选择系统”)
_help_displaysmenu;配置显示菜单的选项
_help_emu_add;添加新的模拟器
_help_emu_args;此模拟器的命令行参数。以下内容将被正确替换：[name]、[romext]、[rompath]、[emulator]、[romfilename]、[system]、[systemn]、[workdir]、[nothing], 以及任何有效的魔法标记(请参阅布局文档)。
_help_emu_delete;删除此模拟器的条目
_help_emu_executable;模拟器可执行文件的完整路径和名称。可能的变量: $HOME = 用户主目录, $PROGDIR = Attract-Mode Plus 程序目录. Windows OS 此外还包含与系统环境变量匹配的 %SYSTEMROOT% 和 %PROGRAMFILES%
_help_emu_exit_hotkey;设置一个全局热键来退出模拟器。如果按下此热键, Attract-Mode Plus 将终止模拟器进程。
_help_emu_gen_romlist;通过在配置的 ROM 路径中搜索具有配置扩展名的 ROM 来生成 ROM 列表, 并将 XML 和其他导入文件信息(如果可用)合并到生成的列表中
_help_emu_import_extras;生成此模拟器 ROM 列表时需要读取的任何其他文件的路径。支持的文件包括：catver.ini(类别)、nplayers.ini(玩家数量)、series.ini(系列)、languages.ini(语言)和 mame.xml。多个文件路径可以用分号分隔。
_help_emu_info_source;使用“listxml”获取 mame -listxml 的输出, “listsoftware”获取 mame/mess -listsoftware 的输出, “thegamesdb.net”从 thegamesdb.net 抓取数据, “steam”从 Steam 安装读取数据, 或使用“scummvm”(如果模拟器是 scummvm)。“listsoftware”和“thegamesdb.net”还要求配置这些来源识别的系统标识符。
_help_emu_name;编辑模拟器
_help_emu_nb_mode_wait;如果此值非零, 模拟器将以非阻塞模式运行。前端将等待最多此秒数, 直到失去对模拟器窗口的焦点, 并在焦点返回前端窗口时再次唤醒。这对于正确启动 Steam 等程序是必要的。除非您确定需要, 否则应设置为 0。
_help_emu_pause_hotkey;设置一个全局热键来暂停模拟器。按下此热键后, Attract-Mode Plus 将暂停模拟器进程并返回前端。可以通过在前端再次选择同一游戏来恢复模拟器进程。
_help_emu_romext;此模拟器的 ROM 扩展名(例如 .zip)。多个扩展名之间用分号分隔。如果游戏存储在单独的子目录中, 请指定“<DIR>”作为条目。
_help_emu_rompath;此模拟器的 ROM 路径。如果用分号分隔, 可以输入多个路径。
_help_emu_scrape_artwork;从网络抓取此模拟器缺失的艺术作品图像
_help_emu_sel_auto_detect;这会扫描父文件夹中已知的模拟器, 并为每个找到的模拟器生成默认配置
_help_emu_sel_gen_romlist;生成包含多个模拟器游戏的合集/ROM列表
_help_emu_sel;配置模拟器
_help_emu_system;此模拟器的系统标识符。多个值可以用分号分隔。
_help_emu_workdir;此模拟器的工作目录。这是前端运行模拟器的目录。此外, 任何相对 ROM 路径、美术文件路径或其他导入文件路径均视为相对于此目录。
_help_filter_add_exception;为此筛选器添加例外。如果游戏符合例外情况(且未被之前的规则过滤掉), 它将被列入筛选器中。
_help_filter_add_rule;向此过滤器添加规则。游戏必须符合所有过滤器规则(或一个例外)才能被列入过滤器。
_help_filter_delete;删除此筛选器
_help_filter_exception;配置此过滤器例外。如果游戏符合例外, 则会将其列在过滤器中。规则和例外将按列出的顺序应用
_help_filter_list_limit;如果您希望限制排序列表的大小, 请将其设置为非零值。前 X 个条目使用正值(例如, “10”表示前 10 个条目), 后 X 个条目使用负值(例如, “-25”表示后 25 个条目), 或使用“0”表示无限制。
_help_filter_name;此过滤器的名称
_help_filter_reverse_order;反转已排序的收藏集/ROM 列表的顺序。默认排序方式为：信息按字母“A”到“Z”排列, 统计数据按“从大到小”排列, 或者选择“不排序”时按源列表顺序排列。
_help_filter_rule;配置此筛选规则。游戏必须符合所有筛选规则(或一个例外)才能被列入筛选器。
_help_filter_sort_by;您希望用于对游戏合集/ROM列表进行排序的游戏信息属性。设置为“No Sort”可保留源合集/ROM列表的顺序。
_help_game_custom_args;设置此项可覆盖此游戏的默认命令行参数。如果希望不使用任何参数进行覆盖, 请将其设置为[nothing]。以下参数将被相应替换：[name]、[romext]、[rompath]、[emulator]、[romfilename]、[system]、[systemn]。
_help_game_custom_executable;设置此项以覆盖此游戏的默认可执行文件游戏
_help_game_delete;从 ROM 列表中删除此游戏
_help_game_edit;编辑此游戏信息
_help_game_overview;编辑游戏概览
_help_generator_build;使用选定的模拟器生成 ROM 列表
_help_generator_opt;设置是否将此模拟器包含在生成的 ROM 列表中
_help_input_action;
_help_input_add;为此控件添加新的输入映射
_help_input_default_action;设置此控件的默认行为
_help_input_delete;移除此输入映射
_help_layout_file;某些布局提供多个 layout*.nut 文件。选择要使用的布局文件。
_help_layout_name;配置布局
_help_main_control;配置控制 Attract-Mode Plus 的摇杆、键盘和鼠标输入
_help_main_display;配置可在 Attract-Mode Plus 中循环切换的 ROM 列表/布局分组(也称为“显示”)。
_help_main_emu;配置模拟器选项
_help_main_intro;配置介绍选项
_help_main_settings;配置常规选项
_help_main_plugin;配置插件选项
_help_main_scraper;配置抓取器选项
_help_main_screensaver_timeout;切换到屏幕保护程序前等待的秒数。0 表示禁用
_help_main_screensaver;配置屏幕保护程序
_help_main_sound;配置音量、声音事件映射和环境音效
_help_misc_anisotropic_filtering;设置纹理的各向异性过滤级别。这将提高缩放纹理的质量
_help_misc_antialiasing;设置抗锯齿级别。
_help_misc_check_for_updates;配置 Attract-Mode Plus 是否应在启动时检查可用更新, 并在发现新版本时显示更新通知对话框。
_help_misc_confirm_exit;退出“吸引模式加强版”前请确认?
_help_misc_confirm_favs;确认添加/删除收藏夹?
_help_misc_custom_overlay;允许布局自定义用于显示、筛选、标签和退出菜单的叠加层
_help_misc_exit_command;退出前端时要执行的命令[例如“sudo shutdown”]
_help_misc_exit_message;退出前端的备选消息(例如“关闭系统”)
_help_misc_filter_wrap_mode;设置当“下一个筛选器”或“上一个筛选器”操作到达筛选器集末尾时的行为
_help_misc_group_clones;将同一游戏的所有克隆版本分组到一个列表项下
_help_misc_hide_brackets;显示游戏标题时隐藏括号中的文本
_help_misc_prefix_modes;将“The”和“Vs.”前缀移动到游戏标题的末尾
_help_misc_hide_console;启动时隐藏控制台。请注意, 此功能仅在从 Windows 图形用户界面启动 Attract-Mode Plus 时有效。如果从现有控制台窗口(例如批处理文件)启动, 则该进程将始终“附加”到现有控制台并向其输出。
_help_misc_image_cache_mbytes;配置Attract-Mode Plus内部图像缓存的最大大小(以兆字节为单位)
_help_misc_language;选择 Attract-Mode Plus 用户界面中使用的语言
_help_misc_layout_preview;立即显示布局配置更改
_help_misc_multiple_monitors;启用 Attract-Mode Plus 的多显示器功能。将此项设置为“否”可能会减少启动游戏时的屏幕闪烁。
_help_misc_power_saving;仅在必要时重绘屏幕, 从而帮助节省电量。在某些布局上可能会导致动画卡顿, 或在 Linux 系统上导致系统冻结
_help_misc_quick_menu;设置是否可以使用同一个按钮打开和关闭菜单。还允许在菜单之间切换, 无需先关闭菜单。
_help_misc_screen_rotation;设置屏幕的基本旋转角度
_help_misc_startup_mode;设置 Attract-Mode Plus 首次启动时应执行的操作
_help_misc_track_usage;配置 Attract-Mode Plus 是否应跟踪使用情况(每款游戏的游玩时间和游玩次数)
_help_misc_ui_color;选择 Attract-Mode Plus 用户界面使用的颜色
_help_misc_video_decoder;配置用于视频播放的解码器(如果有多个解码器可用)
_help_misc_window_mode;设置 Attract-Mode Plus 是全屏显示还是窗口化运行
_help_plugin_command;与此插件关联的可执行文件
_help_plugin_enabled;设置此插件是否启用
_help_plugin_name;配置插件
_help_plugin_sel;配置插件
_help_rule_comp;筛选器的比较类型
_help_rule_delete;删除此过滤器规则
_help_rule_target;您希望基于其进行筛选的游戏信息属性
_help_rule_value;要过滤的正则表达式值。例如, 如果筛选目标是“年份”, 比较方式为“等于”, 则值“1984”将匹配年份 1984 年“198”。将匹配 80 年代的任何年份, “(198.)|(199.)” 将匹配 80 年代或 90 年代的任何年份
_help_scraper_fanart;设置抓取游戏同人图时是否下载
_help_scraper_flyers;设置是否在抓取游戏宣传单和包装盒封面时下载
_help_scraper_marquees;设置抓取游戏时是否下载游戏标题栏和横幅。
_help_scraper_snaps;设置抓取游戏快照时是否下载
_help_scraper_vids;设置抓取游戏视频时是否下载游戏视频
_help_scraper_wheels;设置是否在抓取游戏时下载游戏图标
_help_shortcut_artwork_name;(可选)提供要与此快捷方式关联的艺术作品名称。前端在显示快捷方式时会尝试加载具有此名称的艺术作品
_help_shortcut_delete;从 ROM 列表中删除此快捷键
_help_shortcut_label;编辑此快捷键的标签
_help_shortcut_target;编辑此快捷键的目标
_help_sound_loudness_normalisation;启用自动将音量较小的媒体提升至一致音量的音频效果
_help_sound_sel;为此事件/操作分配声音
_help_sound_volume;设置此音频源的音量

# -- screensaver --

Basic Movie;基本影片
Movie Collage;影片拼贴
Image Collage;图像拼贴
RGB Movie;RGB 影片
Overlay Artwork;叠加艺术作品
Play Sound;播放声音
Preserve Aspect Ratio;保持宽高比
Blank Screen Time;黑屏时间
Blank Screen Start Command;黑屏开始命令
Blank Screen Stop Command;黑屏结束命令
Play intro;播放片头
Detect aspect ratio;检测宽高比
Default video;默认视频
16:9 video;16:9 视频
4:3 video;4:3 视频
9:16 video;9:16 视频
3:4 video;3:4 视频

# -- extra --
