#@中文 (Chinese)

# -- generic --
$1 Rule(s);$1 规则(s)
#Blank Game;
#Custom;
#Default;
Disabled;不显示
Empty;空
#False;
#Multi;
No Sort;不排序
No;否
None;没有
#Off;
#On;
OR;或
#True;
Yes;是

# -- misc --
Press TAB to Configure;按 TAB 键进行配置
Displays Menu Options;界面选择器设置
Action;项目
Add Artwork;添加插图（Artwork)
Add Emulator;添加模拟器
Add Exception;添加例外 Add Exception
Add Filter;添加分类
Add Input;添加输入
Add New Display;添加新的界面
Add Rule;添加规则
Allow Exit;允许退出
#Anisotropic Filtering;
#Anti-Aliasing;
Artwork Label;插图标签
#Artwork Name;
Artwork Path;插图路径
#Auto-detect Emulators;
#Check for Updates;
Collection/Rom List;收集/游戏列表
Comparison;比较
#Confirm Exit;
Confirm Favourites;设置收藏
Controls;控制器
#Create new tag;
#Custom Arguments;
#Custom Executable;
Default Action;默认动作 Default Action
Delete this Display;删除界面
Delete this Emulator;删除模拟器
Delete this Filter;删除排序
#Delete this Game;
Delete this Rule;删除规则
#Delete this Shortcut;
Displays;界面
Emulator Name;模拟器名称
Emulators;模拟器
Enable Multiple Monitors;使多个显示器
Enabled;显示
Exception;其他 Exception
Exit Attract-Mode Plus;退出Attract-Mode Plus
Exit Attract-Mode Plus?;退出Attract-Mode Plus吗?
Exit Command;退出指令
#Exit Message;
Filter Name;分类名称
Filter Value;分类内容
Filter Wrap Mode;分类切换模式
Filter;分类
General;其它
Global Filter;全局分类
#Group Clones;
Hide Brackets in Game Title;隐藏游戏标题中的括号
#Hide Console;
#Image Cache Size;
#Insert Command Shortcut;
#Insert Display Shortcut;
#Insert Game Entry;
#Insert Menu Entry;
#Joystick $1;
#Joystick Mappings;
Joystick Threshold;操纵杆的阈值
Language;语言
#Layout File;
Layout Preview;布局预览
Layout;布局
List Limit;列表大小限制
Menu Colour;菜单颜色
Menu Prompt;标题
Menu Toggle;菜单切换
Mouse Threshold;鼠标的阈值
#Overview;
Plugins;插件
#Power Saving;
Remove Input;移除-设置按键
#Reverse Order;
Rule;规则
Scrape Artwork;搜刮插图（Artwork）
Scrape Fanart;搜刮玩家自制（Fanart）
Scrape Flyers/Boxart;搜刮传单/手办（Flyers/Boxart）
Scrape Game Logos (Wheel Art);搜刮LOGO (Wheel Art)
Scrape Marquees;搜刮跑马灯（Marquees）
Scrape Snaps;搜刮快照（Snaps）
Scrape Videos (MAME only);搜刮 Videos (MAME only)
Scraper;搜刮器
#Screen Rotation;
Screen Saver Timeout;屏保等待时间
#Select template to use for emulator settings;
Show in Cycle;在界面切换转轮中显示
Show in Menu;在界面选择菜单中显示
Sort By;排序方式
Sound;声音
Startup Mode;启动模式
Target;规则的目标（Target）
Title;标题(Title)
Track Usage;游戏时间/频率跟踪
Video Decoder;视频解码
Window Mode;窗口模式
Wrote $1 entries to Collection/Rom List;所有 $1 ROM条目/ROM列表。

# -- indexStrings --
Name;名称
Title;标题(Title)
Emulator;模拟器(Emulator)
CloneOf;克隆 (CloneOf)
Year;年(Year)
Manufacturer;制造商
Category;类别(Category)
Players;玩家(Players)
Rotation;旋转(Rotation)
Control;控制器(Control)
Status;仿真、现状(Status)
DisplayCount;界面数量(DisplayCount)
DisplayType;界面各类(DisplayType)
AltRomname;Rom名称(AltRomname)
AltTitle;标题(AltTitle)
Extra;其他信息(Extra)
#Buttons;
#Series;
Language;语言
#Region;
#Rating;
Favourite;收藏
Tags;标签（Tags）
PlayedCount;游戏计数
PlayedTime;游戏时间
#PlayedLast;
FileIsAvailable;文件可用
#Shuffle;

# -- filterCompDisplayStrings --
contains;包含
does not contain;不包含
does not equal;不等于
equals;等于

# -- commandDispStrings --
Back;<返回<
Up;0度（向上）
Down;180度（向下）
Left;270度（向左）
Right;90度（向右）
Select;选择
Previous Game;上一游戏
Next Game;下一游戏
Previous Page;上一页
Next Page;下一页
Previous Display;上一界面
Next Display;下一界面
Displays Menu;显示器菜单
Previous Filter;上一分类
Next Filter;下一分类
Filters Menu;分类管理菜单
Toggle Layout;切换布局
Toggle Movie;切换影片
Toggle Mute;静音
Toggle Rotate Right;转90度（向右)
Toggle Flip;反转 180度
Toggle Rotate Left;转270度（向左)
Exit;退出 (Yes/No)
Exit to Desktop;退出到桌面
Reload Layout;重新加载布局
Reload Config;重新加载配置
Screenshot;截图
Random Game;随机游戏
Replay Last Game;重新上一次的游戏
Add/Remove Favourite;添加/移除收藏
Previous Favourite;上一收藏
Next Favourite;下一收藏
Add/Remove Tags;添加/移除标签
Screen Saver;屏保
Previous Letter;上一关键词
Next Letter;下一关键词
Intro;启动画面
#Insert Game;
Layout Options;布局选项
Custom1;用户 1
Custom2;用户 2
Custom3;用户 3
Custom4;用户 4
Custom5;用户 5
Custom6;用户 6
Custom7;用户 7
Custom8;用户 8
Custom9;用户 9
Custom10;用户 10
Ambient Soundtrack;环境音
Startup Sound;启动声音
Game Return Sound;游戏返回声音

# --uiColorDispTokens --
#Indigo;
#Blue;
#Cyan;
#Turquoise;
#Green;
#Acid;
#Gold;
#Yellow;
#Orange;
#Brown;
#Rust;
#Red;
#Pink;
#Magenta;
#Purple;
#Grey;
#Neutral;
#White;

# --windowModeDispTokens --
Fill Screen;铺满屏幕
Fullscreen Mode;全屏模式
Window;窗口化
#Window (No Border);

# --screenRotationDispTokens --
Flip;180度（向下）

# --startupDispTokens --
Show Last Selection;显示最后的选择
Launch Last Game;载入最后一次运行的游戏
Show Displays Menu;界面选择器

# --filterWrapDispTokens --
Wrap within Display;该列表的第一个过滤器
Jump to Next Display;跳到下一界面
No Wrap;不切换

# -- antialiasingDispTokens --
#MSAA x2;
#MSAA x4;
#MSAA x8;

# -- FeSettings::anisotropicDispTokens --
#x2;
#x4;
#x8;
#x16;

# -- settingDispStrings --
Sound Volume;声音音量
Ambient Volume;环境音量
Movie Volume;视频音量
#Loudness Normalisation;

# -- splash_message --
Generating Rom List;ROM列表生成中
#Please Wait;
Scraping Artwork;正在搜刮 插图

# -- confirm_dialog --
Add '$1' to Favourites?;添加 '$1' 到收藏？
#Attract-Mode Plus detected emulator(s) that can be imported automatically.  Import them now?;
#Auto-detect emulators?;
#Clear Hotkey?;
Delete display '$1'?;删除 '$1' 界面?
Delete emulator '$1'?;删除 '$1' 模拟器?
Delete filter '$1'?;删除 '$1' 分类?
#Delete game '$1'?;
#Delete shortcut '$1'?;
Overwrite existing '$1' list?;覆盖现有的 '$1' 列表？
Remove '$1' from Favourites?;从收藏中先锋队 '$1'？
Rom path '$1' not found, proceed anyways?;ROM路径 '$1' 没有找到。继续？
This will overwrite an existing mapping ($1).  Proceed?;覆盖现有的映射 ($1)，继续？

# --input_map_dialog --
#Press Hotkey;
Press Input;按下-设置按键

# -- edit_dialog --
Enter Display Name;进入显示器名称
Enter Emulator Name;进入模拟器名称
Enter Filter Name;进入排序名称
#Enter new tag name;
#Enter Romlist Name;

# -- Titles --
#_submenu;
#Configure Layout;
Configure Plugin;设置插件
Configure;设置
Display Edit;界面修改
Edit Artwork;编辑ARTWORK
#Edit Control;
Edit Emulator;编辑模拟器
#Edit Game;
#Edit Shortcut;
Exception Edit;其他编辑 Exception Edit
Filter Edit;编辑分类
Generate Collection/Rom List;生成收集ROM列表
Rule Edit;规则编辑

# --indexDispStrings --
Executable;执行
Command Arguments;命令及参数（ Arguments）
#Working Directory;
Rom Path(s);ROM路径
Rom Extension(s);ROM扩展
System Identifier;系统标识（System Identifier）
Info Source/Scraper;信息源/搜刮
Additional Import File(s);导入附加文件
#Non-Blocking Mode Wait;
Exit Hotkey;退出热键
#Pause Hotkey;

# -- datetime --
#_datetime;
#A Moment Ago;
#Never;
#$1 Second;
#$1 Minute;
#$1 Hour;
#$1 Day;
#$1 Minute Ago;
#$1 Hour Ago;
#$1 Day Ago;
#$1 Week Ago;
#$1 Month Ago;
#$1 Year Ago;
#$1 Seconds;
#$1 Minutes;
#$1 Hours;
#$1 Days;
#$1 Minutes Ago;
#$1 Hours Ago;
#$1 Days Ago;
#$1 Weeks Ago;
#$1 Months Ago;
#$1 Years Ago;

# -- help --
#_help_art_add;
#_help_art_label;
#_help_art_path;
#_help_art;
#_help_back;
#_help_control_add_favourite;
#_help_control_add_tags;
#_help_control_back;
#_help_control_configure;
#_help_control_custom1;
#_help_control_custom10;
#_help_control_custom2;
#_help_control_custom3;
#_help_control_custom4;
#_help_control_custom5;
#_help_control_custom6;
#_help_control_custom7;
#_help_control_custom8;
#_help_control_custom9;
#_help_control_displays_menu;
#_help_control_down;
#_help_control_edit_game;
#_help_control_exit_to_desktop;
#_help_control_exit;
#_help_control_filters_menu;
#_help_control_insert_game;
#_help_control_intro;
#_help_control_joystick_map;
#_help_control_joystick_threshold;
#_help_control_layout_options;
#_help_control_left;
#_help_control_mouse_threshold;
#_help_control_next_display;
#_help_control_next_favourite;
#_help_control_next_filter;
#_help_control_next_game;
#_help_control_next_letter;
#_help_control_next_page;
#_help_control_prev_display;
#_help_control_prev_favourite;
#_help_control_prev_filter;
#_help_control_prev_game;
#_help_control_prev_letter;
#_help_control_prev_page;
#_help_control_random_game;
#_help_control_reload;
#_help_control_replay_last_game;
#_help_control_right;
#_help_control_screen_saver;
#_help_control_screenshot;
#_help_control_select;
#_help_control_toggle_flip;
#_help_control_toggle_layout;
#_help_control_toggle_movie;
#_help_control_toggle_mute;
#_help_control_toggle_rotate_left;
#_help_control_toggle_rotate_right;
#_help_control_up;
#_help_display_add_filter;
#_help_display_add;
#_help_display_delete;
#_help_display_filter;
#_help_display_global_filter;
#_help_display_in_cycle;
#_help_display_in_menu;
#_help_display_layout_options;
#_help_display_layout;
#_help_display_name;
#_help_display_romlist;
#_help_display_sel;
#_help_displaysmenu_exit;
#_help_displaysmenu_layout;
#_help_displaysmenu_prompt;
#_help_displaysmenu;
#_help_emu_add;
#_help_emu_args;
#_help_emu_delete;
_help_emu_executable;The full path and name of the emulator executable. Possible variables: $HOME = User's home dir, $PROGDIR = Attract-Mode Plus program dir. Windows OS additionally has %SYSTEMROOT% and %PROGRAMFILES% matching system environment variables.
#_help_emu_exit_hotkey;
#_help_emu_gen_romlist;
#_help_emu_import_extras;
#_help_emu_info_source;
#_help_emu_name;
#_help_emu_nb_mode_wait;
#_help_emu_pause_hotkey;
#_help_emu_romext;
#_help_emu_rompath;
#_help_emu_scrape_artwork;
#_help_emu_sel_auto_detect;
#_help_emu_sel_gen_romlist;
#_help_emu_sel;
#_help_emu_system;
#_help_emu_workdir;
#_help_filter_add_exception;
#_help_filter_add_rule;
#_help_filter_delete;
#_help_filter_exception;
#_help_filter_list_limit;
#_help_filter_name;
#_help_filter_reverse_order;
#_help_filter_rule;
#_help_filter_sort_by;
#_help_game_custom_args;
#_help_game_custom_executable;
#_help_game_delete;
#_help_game_edit;
#_help_game_overview;
#_help_generator_build;
#_help_generator_opt;
_help_input_action;
#_help_input_add;
#_help_input_default_action;
#_help_input_delete;
#_help_layout_file;
#_help_layout_name;
#_help_main_control;
#_help_main_display;
#_help_main_emu;
#_help_main_intro;
#_help_main_misc;
#_help_main_plugin;
#_help_main_scraper;
#_help_main_screensaver_timeout;
#_help_main_screensaver;
#_help_main_sound;
#_help_misc_anisotropic_filtering;
#_help_misc_antialiasing;
#_help_misc_check_for_updates;
_help_misc_confirm_exit;Confirm before exiting Attract-Mode Plus?
_help_misc_confirm_favs;Confirm the addition/removal of Favourites?
#_help_misc_exit_command;
#_help_misc_exit_message;
#_help_misc_filter_wrap_mode;
#_help_misc_group_clones;
#_help_misc_hide_brackets;
#_help_misc_hide_console;
#_help_misc_image_cache_mbytes;
#_help_misc_language;
#_help_misc_layout_preview;
#_help_misc_multiple_monitors;
#_help_misc_power_saving;
#_help_misc_quick_menu;
#_help_misc_screen_rotation;
#_help_misc_startup_mode;
#_help_misc_track_usage;
#_help_misc_ui_color;
#_help_misc_video_decoder;
#_help_misc_window_mode;
#_help_plugin_command;
#_help_plugin_enabled;
#_help_plugin_name;
#_help_plugin_sel;
#_help_rule_comp;
#_help_rule_delete;
#_help_rule_target;
#_help_rule_value;
#_help_scraper_fanart;
#_help_scraper_flyers;
#_help_scraper_marquees;
#_help_scraper_snaps;
#_help_scraper_vids;
#_help_scraper_wheels;
#_help_shortcut_artwork_name;
#_help_shortcut_delete;
#_help_shortcut_label;
#_help_shortcut_target;
#_help_sound_loudness_normalisation;
#_help_sound_sel;
#_help_sound_volume;

# -- extra --
XML Mode;XML 模式
RGB Movie;RGB模式（RGB Movie）
Overlay Artwork;悬浮的插图
Play Sound;播放声音
Ambient Sounds;背景音乐
Movie Collage;拼图式动态画面
Command;命令
All;全部
Basic Movie;全屏式动态画面
Minimum Run Time;最小运行时间
Image Collage;拼图式静态画面
Preserve Aspect Ratio;以当前游戏为背景
