#@Deutsch

# -- generic --
$1 Rule(s);$1 Regel(n)
Blank Game;Spiele-Platzhalter
#Custom;
Default;Grundeinstellung
Disabled;ausgeschaltet
Empty;Leer
#False;
#Multi;
No Sort;Keine Sortierung
No;Nein
None;Keine
#Off;
#On;
OR;ODER
#True;
Yes;Ja

# -- misc --
#Displays Menu Options;
Action;Aktion
Add Artwork;Bilddatei hinzufügen
Add Emulator;Emulator hinzufügen
Add Exception;Ausnahme hinzufügen
Add Filter;Filter hinzufügen
Add Input;Steuerung hinzufügen
Add New Display;Neuen Bildschirm hinzufügen
Add Rule;Regel hinzufügen
Allow Exit;Beenden zulassen
#Anisotropic Filtering;
#Anti-Aliasing;
Artwork Label;Bezeichnung der Bilddatei
Artwork Name;Bilddateiname
Artwork Path;Pfad zur Bilddatei
#Auto-detect Emulators;
#Check for Updates;
Collection/Rom List;Sammlung/Romliste
Comparison;Vergleich
Confirm Exit;Beenden bestätigen
Confirm Favourites;Favoriten bestätigen
Controls;Steuerungen
Create new tag;neues Etikett erstellen
Custom Arguments;benutzerdefinierte Argumente
Custom Executable;benutzerdefinierte Programmdatei
Default Action;Standardaktion
Delete this Display;Diesen Bildschirm löschen
Delete this Emulator;Diesen Emulator löschen
Delete this Filter;Diesen Filter löschen
Delete this Game;Lösche dieses Spiel
Delete this Rule;Diese Regel löschen
Delete this Shortcut;Lösche diese Verknüpfung
Displays;Bildschirme
Emulator Name;Name des Emulators
Emulators;Emulatoren
Enable Multiple Monitors;mehrere Monitore zulassen
Enabled;Aktiviert
Exception;Ausnahme
Exit Attract-Mode;Attract-Mode beenden
Exit Attract-Mode?;Attract-Mode beenden?
Exit Command;Kommando zum Beenden
Exit Message;Abschiedsnachricht
Filter Name;Bezeichnung des Filters
Filter Value;Filterwert
Filter Wrap Mode;Rolliermodus des Filters
#Filter;
General;Allgemein
Global Filter;Globaler Filter
Group Clones;Gruppenklone
Hide Brackets in Game Title;Unterdrücke Klammern in Spieltiteln
#Hide Console;
#Image Cache Size;
Insert Command Shortcut;füge eine Kommandoverknüpfung ein
Insert Display Shortcut;füge eine Bildschirmverknüpfung hinzu
Insert Game Entry;Setze Spieleintrag
Insert Menu Entry;Setze Menüeintrag
#Joystick $1;
Joystick Mappings;Joystick Belegung
Joystick Threshold;Schwellwert Joystick
Language;Sprache
Layout File;Themendatei
Layout Options;Themen Optionen
Layout Preview;Layoutvorschau
Layout;Thema
List Limit;Limit für die Liste
Menu Colour;Menüfarbe
Menu Prompt;Eingabeaufforderung
Menu Toggle;Menü umschalten
Mouse Threshold;Schwellwert Maus
Overview;Übersicht
#Plug-ins;
#Power Saving;
Remove Input;Steuerung löschen
#Reverse Order;
Rule;Regel
Scrape Artwork;Scrape Bilddateien
#Scrape Fanart;
#Scrape Flyers/Boxart;
Scrape Game Logos (Wheel Art);Scrape Spiele Logos (Wheel Art)
#Scrape Marquees;
#Scrape Snaps;
Scrape Videos (MAME only);Scrape Videos (nur für MAME)
#Scraper;
#Screen Rotation;
Screen Saver Timeout;Timeout des Bildschirmschoners
Select template to use for emulator settings;Wähle Beispieldatei für die Emulator-Einstellungen
Show in Cycle;Zeige in der Übersicht
Show in Menu;Zeige im Menü
Sort By;Sortiert nach
Sound;Klänge
Startup Mode;Startup Modus
Target;Ziel
Title;Titel
Track Usage;Protokolliere Nutzung
#Video Decoder;
Window Mode;Fenstermodus
Wrote $1 entries to Collection/Rom List;$1 Einträge zur Romliste hinzugefügt

# -- indexStrings --
#Name;
Title;Titel
#Emulator;
CloneOf;Clone von
Year;Jahr
Manufacturer;Hersteller
Category;Kategorie
Players;Spieler
Rotation;Ausrichtung
Control;Steuerung
#Status;
DisplayCount;Anzahl Bildschirme
DisplayType;Bildschirm Typ
AltRomname;Alternativer Rom-Name
AltTitle;Alternativer Titel
#Extra;
Buttons;Tasten
#Series;
Language;Sprache
#Region;
#Rating;
Favourite;Favorit
Tags;Markierungen
PlayedCount;Male gespielt
PlayedTime;Zeit gespielt
#PlayedLast;
FileIsAvailable;Datei ist vorhanden
#Shuffle;

# -- filterCompDisplayStrings --
contains;enthält
does not contain;enthält nicht
does not equal;ist ungleich
equals;ist gleich

# -- commandDispStrings --
Back;Zurück
Up;Hoch
Down;Runter
Left;Links
Right;Rechts
Select;Auswählen
Previous Game;vorheriges Spiel
Next Game;nächstes Spiel
Previous Page;Vorherige Seite
Next Page;Nächste Seite
Previous Display;Vorheriger Bildschirm
Next Display;Nächster Bildschirm
Displays Menu;Bildschirm Menü
Previous Filter;Vorheriger Filter
Next Filter;Nächster Filter
Filters Menu;Filter-Menü
Toggle Layout;Thema wechseln
Toggle Movie;Movie wechseln
Toggle Mute;Stummschaltung wechseln
Toggle Rotate Right;Rechtsdrehung
Toggle Flip;Umdrehen (180°)
Toggle Rotate Left;Linksdrehung
Exit;Beenden (Bestätigen)
Exit to Desktop;Beenden zum Desktop
Reload;Neu laden
Screenshot;Bildschirmphoto
Random Game;Zufälliges Spiel
Replay Last Game;Letztes Spiel wiederholen
Add/Remove Favourite;Favorit hinzufügen/löschen
Previous Favourite;Voriger Favorit
Next Favourite;Nächster Favorit
Add/Remove Tags;Markierungen hinzufügen/löschen
Screen Saver;Bildschirmschoner
Previous Letter;Voriger Buchstabe
Next Letter;Nächster Buchstabe
#Intro;
#Insert Game;
Layout Options;Themen Optionen
Custom1;Eigendefiniert1
Custom2;Eigendefiniert2
Custom3;Eigendefiniert3
Custom4;Eigendefiniert4
Custom5;Eigendefiniert5
Custom6;Eigendefiniert6
Custom7;Eigendefiniert7
Custom8;Eigendefiniert8
Custom9;Eigendefiniert9
Custom10;Eigendefiniert10
Ambient Soundtrack;Umgebungs-Soundtrack
Startup Sound;Start-Klang
Game Return Sound;Klang bei Rückkehr zum Spiel

# --uiColorDispTokens --
#Indigo;
#Blue;
#Cyan;
#Turquoise;
#Green;
#Acid;
#Gold;
#Yellow;
#Orange;
#Brown;
#Rust;
#Red;
#Pink;
#Magenta;
#Purple;
#Grey;
#Neutral;
#White;

# --windowModeDispTokens --
Fill Screen;Bildschirm ausfüllen
Fullscreen Mode;Vollbildmodus
Window;Fenster
Window (No Border);Window (ohne Umrandung)

# --screenRotationDispTokens --
Flip;Umdrehen

# --startupDispTokens --
Show Last Selection;Zeige die letzte Auswahl
Launch Last Game;zuletzt gespieltes Spiel starten
Show Displays Menu;Bildschirmmenü anzeigen

# --filterWrapDispTokens --
Wrap within Display;Rollieren innerhalb der Liste
Jump to Next Display;Springe zur nächsten Liste
No Wrap;Kein Rollieren

# -- antialiasingDispTokens --
#MSAA x2;
#MSAA x4;
#MSAA x8;

# -- FeSettings::anisotropicDispTokens --
#x2;
#x4;
#x8;
#x16;

# -- settingDispStrings --
Sound Volume;Klang-Lautstärke
Ambient Volume;Umgebungs-Lautstärke
Movie Volume;Film-Lautstärke
#Loudness Normalisation;

# -- splash_message --
#Generating index ($1%);
Generating Rom List: $1%;Erzeuge Romliste $1%
Please Wait;bitte warten
Scraping Artwork: $1%;Scrape Bilddatei: $1%

# -- confirm_dialog --
Add '$1' to Favourites?;Soll '$1' zu Favoriten hinzugefügt werden?
Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?;Attract-Mode hat Emulatoren gefunden, die automatisch hinzugefügt werden können, sollen diese jetzt integriert werden?
#Auto-detect emulators?;
Clear Hotkey?;Tastenkombination entfernen?
Delete display '$1'?;Bildschirm '$1' löschen?
Delete emulator '$1'?;Emulator '$1' löschen?
Delete filter '$1'?;Filter '$1' löschen?
Delete game '$1'?;Lösche Spiel '$1'?
Delete shortcut '$1'?;Lösche Verknüpfung '$1'?
Overwrite existing '$1' list?;Existierende Romliste '$1' überschreiben?
Remove '$1' from Favourites?;Entferne '$1' aus den Favoriten?
Rom path '$1' not found, proceed anyways?;ROM-Pfad '$1' nicht gefunden. Trotzdem fortfahren?
This will overwrite an existing mapping ($1).  Proceed?;Dies überschreibt die existierende Zuordnung ($1). Fortfahren?

# --input_map_dialog --
Press Hotkey;betätige die Tastenkombination
Press Input;Steuerung betätigen

# -- edit_dialog --
Enter Display Name;Bezeichnung des Bildschirms eingeben
Enter Emulator Name;Name des Emulators eingeben
Enter Filter Name;Bezeichnung des Filters eingeben
Enter new tag name;gib einen neuen Etikettennamen ein
Enter Romlist Name;benenne die Romliste

# -- Titles --
#_submenu;
Configure Layout;Konfiguriere das Thema
Configure Plug-in;Konfiguriere Plug-in
Configure;Konfiguration
Display Edit;Bildschirm bearbeiten
Edit Artwork;Bilddatei bearbeiten
#Edit Control;
Edit Emulator;Emulator bearbeiten
Edit Game;editiere das Spiel
Edit Shortcut;editiere die Verknüpfung
Exception Edit;editiere die Ausnahme
Filter Edit;Filter editieren
Generate Collection/Rom List;Sammlung/Romliste erstellen
Rule Edit;Regel editieren

# --indexDispStrings --
Executable;Ausführbare Datei
Command Arguments;Kommandozeilenargumente
Working Directory;Arbeitsverzeichnis
Rom Path(s);Pfad(e) zu dem ROMs
Rom Extension(s);ROM Dateiendung(en)
System Identifier;System Kennung
Info Source/Scraper;Info Quelle/Scraper
Additional Import File(s);Zusätzliche Import Datei(en)
Non-Blocking Mode Wait;Klippo-Modus Wartezeit
Exit Hotkey;Hotkey zum Beenden
Pause Hotkey;Pause Tastenkombination

# -- datetime --
#_datetime;
#A Moment Ago;
#Never;
#$1 Second;
#$1 Minute;
#$1 Hour;
#$1 Day;
#$1 Minute Ago;
#$1 Hour Ago;
#$1 Day Ago;
#$1 Week Ago;
#$1 Month Ago;
#$1 Year Ago;
#$1 Seconds;
#$1 Minutes;
#$1 Hours;
#$1 Days;
#$1 Minutes Ago;
#$1 Hours Ago;
#$1 Days Ago;
#$1 Weeks Ago;
#$1 Months Ago;
#$1 Years Ago;

# -- help --
_help_art_add;Füge eine neue Bilddatei-Quelle (Marquees, Screenshots etc.) hinzu
_help_art_label;Kennzeichnung zur Identifikation dieser Bilddatei-Quelle (verwendet in Themen)
_help_art_path;Der Pfad zu den Dateien für diese Bilddatei. Mehrere Pfade können durch Semikolon getrennt werden.
_help_art;Eine Bilddatei-Quelle, welche im Thema verfügbar ist
_help_back;Menü verlassen
_help_control_add_favourite;Definiere die Taste(n), um das momentan gewählten Spiel als Favoriten zu markiern/löschen
_help_control_add_tags;Definiere die Taste(n), um Markierungen zum momentan gewählten Spiel hinzuzufügen/zu löschen
_help_control_back;Definiere die Taste(n) für Zurück/Cancel
_help_control_configure;Definiere die Taste(n), um das "Konfigurations Menu" anzuzeigen
_help_control_custom1;Definiere die Taste(n) für "Eigendefiniert1"
_help_control_custom10;Definiere die Taste(n) für "Eigendefiniert10"
_help_control_custom2;Definiere die Taste(n) für "Eigendefiniert2"
_help_control_custom3;Definiere die Taste(n) für Eigendefiniert3
_help_control_custom4;Definiere die Taste(n) für Eigendefiniert4
_help_control_custom5;Definiere die Taste(n) für Eigendefiniert5
_help_control_custom6;Definiere die Taste(n) für Eigendefiniert6
_help_control_custom7;Definiere die Taste(n) für "Eigendefiniert7"
_help_control_custom8;Definiere die Taste(n) für "Eigendefiniert8"
_help_control_custom9;Definiere die Taste(n) für "Eigendefiniert9"
_help_control_displays_menu;Definiere die Taste(n), um das "Bildschirm Menü" anzuzeigen
_help_control_down;Definiere die Taste(n), um die Auswahl nach unten zu bewegen
_help_control_edit_game;Definiere die Taste(n) zum Editieren der aktuellen Auswahl
_help_control_exit_to_desktop;Definiere die Taste(n), um das Frontend unmittelbar zum Desktop zu verlassen
_help_control_exit;Definiere die Taste(n), um das Frontend zu verlassen
_help_control_filters_menu;Definiere die Taste(n), um das "Filter Menü" anzuzeigen
#_help_control_insert_game;
_help_control_intro;Definiere die Taste(n) um das Intro-Video abzuspielen
_help_control_joystick_map;Hier kannst du das Frontend zwingen bestimmte Joystick ports immer denselben Joysticks/Gamepads zuzuweisen (So kannst du zum Beispiel "Microsoft X-Box 360 pad" immer als Joystick 0 verwenden.)
_help_control_joystick_threshold;Der Schwellwert um Joystick-Bewegungen noch zu erkennen, von 1 bis 100 (100=am wenigsten empfindlich)
#_help_control_layout_options;
_help_control_left;Definiere die Taste(n) um die Auswahl nach links zu bewegen
_help_control_mouse_threshold;Der Schwellwert um Maus-Bewegungen noch zu erkennen, von 1 bis 100 (100=am wenigsten empfindlich)
_help_control_next_display;Definiere die Taste(n), um zum nächsten Bildschirm zu springen
_help_control_next_favourite;Definiere die Taste(n), um zum nächsten Favoriten zu springen
_help_control_next_filter;Definiere die Taste(n), um zum nächsten Filter zu springen
_help_control_next_game;Definiere die Taste(n) um das nächste Spiel auszuwählen
_help_control_next_letter;Definiere die Taste(n), um zum nächsten Buchstaben zu springen
_help_control_next_page;Definiere die Taste(n), um die Auswahl zur nächsten Seite zu bewegen
_help_control_prev_display;Definiere die Taste(n), um zum vorigen Bildschirm zu springen
_help_control_prev_favourite;Definiere die Taste(n), um zum vorigen Favoriten zu springen
_help_control_prev_filter;Definiere die Taste(n), um zum vorigen Filter zu springen
_help_control_prev_game;Definiere die Taste(n) um das vorherige Spiel auszuwählen
_help_control_prev_letter;Definiere die Taste(n), um zum vorigen Buchstaben zu springen
_help_control_prev_page;Definiere die Taste(n), um die Auswahl zur vorherigen Seite zu bewegen
_help_control_random_game;Definiere die Taste(n), die ein zufälliges Spiel aus der aktuellen Liste wählen
_help_control_reload;Definiere die Taste(n), die das aktuelle Layout neu laden
_help_control_replay_last_game;Definiere die Taste(n), die das zuletzt gespielte Spiel erneut starten
_help_control_right;Definiere die Taste(n) um die Auswahl nach rechts zu bewegen
_help_control_screen_saver;Definiere die Taste(n), die den Bildschirmschoner starten
_help_control_screenshot;Definiere die Taste(n), um ein Bildschirmphoto vom Frontend zu machen
_help_control_select;Definiere die Taste(n), um die aktuelle Auswahl zu starten
_help_control_toggle_flip;Definiere die Taste(n), die den Bildschirm um 180 Grad drehen
_help_control_toggle_layout;Definiere die Taste(n), die das Thema wechseln (Dies funktioniert nicht bei allen Themen)
_help_control_toggle_movie;Definiere die Taste(n) für Videos an/aus
_help_control_toggle_mute;Definiere die Taste(n) für Frontend-Klänge an/aus
_help_control_toggle_rotate_left;Definiere die Taste(n) für eine 90 Grad Drehung des Bildschirms gegen den Uhrzeigersinn
_help_control_toggle_rotate_right;Definiere die Taste(n) für eine 90 Grad Drehung des Bildschirms im Uhrzeigersinn
_help_control_up;Definiere die Taste(n), um die Auswahl nach oben zu bewegen
_help_display_add_filter;Füge einen Filter dem Filter-Set dieses Bildschirms hinzu
_help_display_add;Neuen Bildschirm hinzufügen
_help_display_delete;Diesen Bildschirm löschen
_help_display_filter;Konfiguriere diesen Filter vom Filter-Set des Bildschirms
_help_display_global_filter;Konfiguriere die globalen Filterregeln, die auf jeden Eintrag in der Sammlung/Romliste dieses Bildschirms angewendet werden
_help_display_in_cycle;Soll dieser Bildschirm in "Vorheriger Bildschirm"/"Nächster Bildschirm" in der Übersicht angezeigt werden?
_help_display_in_menu;Soll dieser Bildschirm im "Bildschirmmenü" angezeigt werden?
_help_display_layout_options;Konfiguriere alle Themen-spezifischen Optionen
_help_display_layout;Welches Thema soll dieser Bildschirm nutzen
_help_display_name;Der Titel des aktuellen Bildschirms
_help_display_romlist;Die Sammlung/Romliste, die für diesen Bildschirm verwendet wird
_help_display_sel;Konfiguriere Bildschirm
_help_displaysmenu_exit;Lege fest, ob eine Beenden-Option im Bildschirm Menü verfügbar sein soll
_help_displaysmenu_layout;Wähle das Thema für das Bildschirmmenü. Wähle "Standard", um das voreingestellte Menü des Frontends zu verwenden
_help_displaysmenu_prompt;Die Bildschirmmenü Aufforderung (z.B. "Select System")
_help_displaysmenu;Konfiguriere die Optionen für das Bildschirmmenü
_help_emu_add;Neuen Emulator hinzufügen
_help_emu_args;Die Kommandozeilenargumente für diesen Emulator. Folgende Einträge werden entsprechend ersetzt: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;Lösche den Eintrag für diesen Emulator
_help_emu_executable;Der komplette Pfad und die Bezeichnung der Programmdatei des Emulators. $HOME wird durch die Homedir des Users ersetzt
_help_emu_exit_hotkey;Definiere einen globalen Hotkey, um den Emulator zu verlassen.  Attract-Mode wird den Emulator Prozess beenden, wenn dieser Hotkey betätigt wird.
_help_emu_gen_romlist;Generiere eine Romliste, indem der eingestellte ROM-Pfad nach ROMs mit der definierten Endung durchsucht wird. Falls verfügbar, werden XML-Informationen und zusätzliche Import-Dateien mit einbezogen.
_help_emu_import_extras;Pfad zu beliebigen zusätzlichen Dateien welche gelesen werden müssen wenn eine Romliste für diesen Emulator generiert wird. Unterstützte Dateien sind: catver.ini (für Spiele Kategorien) und nplayers.ini (für Anzahl an Spielern).  Mehrere Dateipfade können durch Semikolon getrennt werden.
_help_emu_info_source;Verwende "listxml" falls der Emulator mame -listxml Ausgabe bereitstellt, "listsoftware" für mame/mess -listsoftware Ausgabe, "thegamesdb.net" um Daten von thegamesdb.net zu scrapen, oder "steam" um von einer Steam-Installation zu lesen. "listsoftware" und "thegamesdb.net" benötigen zusätzlich die Konfiguration einer System-Kennung welche von diesen Ressourcen erkannt wird
#_help_emu_name;
_help_emu_nb_mode_wait;Definiere eine minimale Wartezeit (in Sekunden).  Attract-Mode wird bei Aktivierung dieses Emulators warten bis die minimale Zeit verstrichen ist und es zum Vordergund-Fenster wird. Dies wird speziell benötigt, um Steam korrekt unter Windows auszuführen. Lass es auf 0 stehen, außer du weißt, dass du es benötigst
_help_emu_pause_hotkey;Definiere eine globale Tastenkombination um Emulatoren zu pausieren. Wird diese benutzt pausiert Attract-Mode jegliche Emulation und kehrt zum Frontend zurück. Um die Emulation fortzusetzen muss dasselbe Spiel wie vorher ausgewählt werden.
_help_emu_romext;Die ROM Dateiendung(en) für diesen Emulator (z.B. .zip). Mehrere Endungen können durch Semikolon getrennt werden. Gib "<DIR>" als Eintrag an, falls die Spiele in separaten Unterverzeichnissen gespeichert sind
_help_emu_rompath;Der Pfad zu den ROMs für diesen Emulator. Mehrere Pfade können durch Semikolon getrennt werden.
_help_emu_scrape_artwork;Scrape fehlende Bilddateien für diesen Emulator von TheGamesDB.net und mamedb.com
#_help_emu_sel_auto_detect;
_help_emu_sel_gen_romlist;Erstelle eine Sammlung/Romliste, die aus Spielen verschiedener Emulatoren besteht.
_help_emu_sel;Konfiguriere Emulator
_help_emu_system;Die System-Kennung(en) für diesen Emulator.  Mehrere Werte können durch Semikolon getrennt werden.
_help_emu_workdir;Arbeitsverzeichnis dieses Emulators. Von hier aus startet das Frontend den gewählten Emulator. Dabei wird angenommen, dass alle relativen Pfade, Ordner für Bilddateien oder etwaige Zusatzdateien zu diesem Verzeichnis relativ positioniert sind.
_help_filter_add_exception;Füge eine Ausnahme zu diesem Filter hinzu. Stimmt ein Spiel mit dieser Ausnahme überein und wurde nicht anderweitig herausgefiltert, wird es mittles dieses Filters angezeigt
_help_filter_add_rule;Diesem Filter eine Regel hinzufügen
_help_filter_delete;Lösche diesen Filter
_help_filter_exception;Konfiguriere eine Filterausnahme. Stimmt ein Spiel mit dieser Ausnahme überein, wird es im Filter aufgelistet. Regeln und Ausnahmen werden in der selben Reihenfolge angewandt in der sie aufgelistet sind
_help_filter_list_limit;Setze dies zu einem Wert ungleich Null um die Größe der sortierten Liste zu limitieren. Verwende einen positiven Wert für die ersten X Einträge (z.B. "10" für die ersten 10 Einträge), einen negativen Wert für die letzten X Einträge (z.B. "-25" für die letzten 25 Einträge), oder "0" für alle
_help_filter_name;Bezeichnung für diesen Filter
#_help_filter_reverse_order;
_help_filter_rule;Konfiguriere Filterregel
_help_filter_sort_by;Das Spiel-Informationsattribut nach dem du die Sammlung/Romliste sortieren möchtest. Stelle auf "Keine Sortierung" um die Sortierung der Quell-Sammlung/Romliste zu verwenden
_help_game_custom_args;Nutze dies, um die Standard Kommandozeilenattribute für dieses Spiel außer Kraft zu setzen. Setze das Argument [nothing] wenn hierbei keine Parameter angewandt werden sollen. Folgendes kann analog verwendet werden: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_game_custom_executable;Nutze dies, um die Standart Programmdatei für dieses Spiel zu überschreiben.
_help_game_delete;Lösche dieses Spiel aus der Romliste
_help_game_edit;Editiere die Information zu diesem Spiel
_help_game_overview;Editiere die Spieleübersicht
_help_generator_build;Erstelle eine Romliste mit dem/den ausgewählten Emulator(en)
_help_generator_opt;Wähle, ob dieser Emulator in der zu erstellenden Romliste enthalten sein soll
_help_input_action;
_help_input_add;Dieser Aktion ein neues Steuerungs-Mapping zuordnen
_help_input_default_action;Setze ein Standardverhalten für diese Eingabe
_help_input_delete;Dieses Steuerungs-Mapping löschen
_help_layout_file;Manche Themen haben mehrere .NUT Dateien. Wähle welche standardgemäß verwendet werden soll
#_help_layout_name;
_help_main_control;Konfiguriere die Joystick-, Tastatur- und Maus-Eingaben die Attract-Mode steuern
_help_main_display;Konfiguriere die Romlisten/Themen-Gruppierungen (die "Bildschirme") welche in Attract-Mode zum Durchblättern verfügbar sind
_help_main_emu;Konfiguriere verfügbare Spielsysteme und Emulatoren
_help_main_intro;Intro konfigurieren
_help_main_misc;Konfiguriere sonstige Einstellungen
_help_main_plugin;Konfiguriere verfügbare Plug-ins
_help_main_scraper;Konfiguriere die Bilddatei-Scraper Einstellungen
_help_main_screensaver_timeout;Die Wartezeit in Sekunden, bevor der Bildschirmschoner aktiv wird. 0 zum Deaktivieren
_help_main_screensaver;Konfiguriere Bildschirmschoner
_help_main_sound;Konfiguriere Klang-Lautstärke, Klang->Ereignis Zuordnungen und den Umgebungs-Soundtrack
#_help_misc_anisotropic_filtering;
#_help_misc_antialiasing;
#_help_misc_check_for_updates;
_help_misc_confirm_exit;Bestätigung vor Verlassen von Attract-Mode verlangen?
_help_misc_confirm_favs;Das Hinzufügen/Löschen zu den Favoriten bestätigen
_help_misc_exit_command;Befehl der ausgeführt wird, wenn Beenden (Bestätigen) gewählt wird [z.B. "sudo shutdown"]
_help_misc_exit_message;Alternative Abschiedsnachricht beim Beenden des Programms [z.B. "Erstmal"]
_help_misc_filter_wrap_mode;Definiere was passieren soll wenn die "Nächster Filter" oder "Vorheriger Filter" Aktionen das Ende Filterliste erreichen
_help_misc_group_clones;Gruppieren Sie alle Klone eines Spiels unter einem einzigen Listeneintrag
_help_misc_hide_brackets;Verberge bei der Anzeige der Spieletitel den Text in Klammern
_help_misc_hide_console;Verstecke das Kommandozeilenfenster beim Starten. Bitte beachte, dass dies nur in einer Windows Schaltfläche funktioniert. Wird die Anwendung durch ein Kommandozeilenfenster, wie z.B. einer Batch-Datei, gestartet, wird der Ladevorgang and dieses Fenster gebunden sein
#_help_misc_image_cache_mbytes;
_help_misc_language;Wähle die Sprache in der Attract-Mode angezeigt wird
_help_misc_layout_preview;Zeigen Sie Änderungen an der Layoutkonfiguration sofort an
_help_misc_multiple_monitors;Wähle ob Attract-Mode mehrere Monitore verwendet. Ist "No" gewählt, kann das Flackern beim Start einiger Spiele reduzieren
#_help_misc_power_saving;
_help_misc_quick_menu;Legt fest, ob Menüs mit derselben Taste geöffnet und geschlossen werden können. Ermöglicht außerdem das Wechseln zwischen Menüs, ohne diese vorher schließen zu müssen
#_help_misc_screen_rotation;
_help_misc_startup_mode;Wähle, was passieren soll, wenn Attract-Mode das erste Mal startet
_help_misc_track_usage;Konfiguriere, ob Attract-Mode die Nutzung protokollieren soll (Gesamtspielzeit und Anzahl der Spielestarts pro Spiel)
_help_misc_ui_color;Wählen Sie die Farbe aus, die in der Benutzeroberfläche von Attract-Mode verwendet werden soll
_help_misc_video_decoder;Konfiguriere den Decoder für die Video Wiedergabe (falls mehrere Decoder verfügbar sind)
_help_misc_window_mode;Lege fest, ob Attract-Mode in einem Fenster läuft oder den Bildschirm füllt
_help_plugin_command;Die ausführbare Datei, welche mit diesem Plug-in verknüpft ist
_help_plugin_enabled;Festlegen, ob dieses Plug-in aktiviert ist
#_help_plugin_name;
_help_plugin_sel;Konfiguriere Plug-in
_help_rule_comp;Vergleichstyp für diesen Filter
_help_rule_delete;Diese Filterregel löschen
_help_rule_target;Das Spiel-Informationsattribut nach welchem du filtern möchtest
_help_rule_value;Der reguläre Ausdruckswert nach dem gefiltert wird. Wenn zum Beispiel der Filter auf "Jahr" und der Vergleichswert auf "ist gleich" gesetzt wird, wird ein Wert "1984" das Jahr 1984 filtern, "198." jedes Jahr in den Achtzigern und "(198.)|(199.)" jedes Jahr in den 80ern und 90ern
_help_scraper_fanart;Lege fest ob, Spiele Fanart während des Scrapens heruntergeladen werden soll
_help_scraper_flyers;Lege fest ob, Spiele Flyer und Box Covers während des Scrapens heruntergeladen werden sollen
_help_scraper_marquees;Lege fest ob, Spiele Marquees und Banner während des Scrapens heruntergeladen werden sollen
_help_scraper_snaps;Lege fest ob, Spiel Snapshots während des Scrapens heruntergeladen werden sollen
_help_scraper_vids;Lege fest ob, Videos der Spiele während des Scrapens heruntergeladen werden sollen
_help_scraper_wheels;Lege fest ob, Spiel Logos während des Scrapens heruntergeladen werden sollen
_help_shortcut_artwork_name;Hier kannst du Bilddateien einer Verknüpfung zuordnen. Das Frontend wird versuchen Bilddateien mit diesem Namen zu laden wenn die jeweilige Verknüpfung angezeigt wird
_help_shortcut_delete;Lösche diese Verknüpfung aus der Romliste
_help_shortcut_label;Editiere den Namen der Verknüpfung
_help_shortcut_target;Editiere das Ziel der Verknüpfung
#_help_sound_loudness_normalisation;
_help_sound_sel;Weise diesem Ereignis/dieser Aktion einen Klang zu
_help_sound_volume;Gültige Lautstärke Einstellungen gehen von 0 (stumm) bis 100

# -- extra --
XML Mode;XML-Modus
Overlay Artwork;Bilddatei als Overlay
Play Sound;Klang abspielen
Ambient Sounds;Umgebungs-Klänge
Command;Kommando
Image collage;Bilder Collage
All;Alle
Basic Movie;Basis Video
Movie collage;Video Collage
Minimum Run Time;Minimale Laufzeit
Preserve Aspect Ratio;Seitenverhältnis beibehalten
