#@English

# -- generic --
$1 Rule(s);$1 Rule(s)
Blank Game;Blank Game
Custom;Custom
Default;Default
Disabled;Disabled
Empty;Empty
False;False
Multi;Multi
No Sort;No Sort
No;No
None;None
Off;Off
On;On
OR;OR
True;True
Yes;Yes
Import;Import
Cancel;Cancel

# -- misc --
Press TAB to Configure;Press TAB to Configure
Displays Menu Options;Displays Menu Options
Action;Action
Add Artwork;Add Artwork
Add Emulator;Add Emulator
Add Exception;Add Exception
Add Filter;Add Filter
Add Input;Add Input
Add Display;Add Display
Add Rule;Add Rule
Allow Exit;Allow Exit
Anisotropic Filtering;Anisotropic Filtering
Anti-Aliasing (MSAA);Anti-Aliasing (MSAA)
Artwork Label;Artwork Label
Artwork Name;Artwork Name
Artwork Path;Artwork Path
Auto-detect Emulators;Auto-detect Emulators
Check for Updates;Check for Updates
Collection/Romlist;Collection/Romlist
Comparison;Comparison
Confirm Exit;Confirm Exit
Confirm Favourites;Confirm Favourites
Controls;Controls
Add Tag;Add Tag
Custom Arguments;Custom Arguments
Custom Executable;Custom Executable
Custom Overlay;Custom Overlay
Default Action;Default Action
Delete this Display;Delete this Display
Delete this Emulator;Delete this Emulator
Delete this Filter;Delete this Filter
Delete this Game;Delete this Game
Delete this Rule;Delete this Rule
Delete this Shortcut;Delete this Shortcut
Displays;Displays
Emulator Name;Emulator Name
Emulators;Emulators
Multiple Monitors;Multiple Monitors
Enabled;Enabled
Exception;Exception
Exit Attract-Mode Plus;Exit Attract-Mode Plus
Exit Attract-Mode Plus?;Exit Attract-Mode Plus?
Exit Command;Exit Command
Exit Message;Exit Message
Filter Name;Filter Name
Filter Value;Filter Value
Filter Wrap Mode;Filter Wrap Mode
Filter;Filter
Settings;Settings
Global Filter;Global Filter
Group Clones;Group Clones
Hide Game Title Brackets;Hide Game Title Brackets
Format Game Title;Format Game Title
Hide Console;Hide Console
Image Cache Size;Image Cache Size
Insert Command Shortcut;Insert Command Shortcut
Insert Display Shortcut;Insert Display Shortcut
Insert Game Entry;Insert Game Entry
Insert Menu Entry;Insert Menu Entry
Joystick $1;Joystick $1
Joystick Mappings;Joystick Mappings
Joystick Threshold;Joystick Threshold
Language;Language
Layout File;Layout File
Layout Preview;Layout Preview
Layout;Layout
List Limit;List Limit
Menu Colour;Menu Colour
Menu Prompt;Menu Prompt
Menu Toggle;Menu Toggle
Mouse Threshold;Mouse Threshold
Overview;Overview
Plugins;Plugins
Power Saving;Power Saving
Remove Input;Remove Input
Reverse Order;Reverse Order
Rule;Rule
Scrape Artwork;Scrape Artwork
Scrape Fanart;Scrape Fanart
Scrape Flyers/Boxart;Scrape Flyers/Boxart
Scrape Game Logos (Wheel Art);Scrape Game Logos (Wheel Art)
Scrape Marquees;Scrape Marquees
Scrape Snaps;Scrape Snaps
Scrape Videos (MAME only);Scrape Videos (MAME only)
Scraper;Scraper
Screen Rotation;Screen Rotation
Screen Saver Timeout;Screen Saver Timeout
Selection Speed;Selection Speed
Selection Delay;Selection Delay
Selection Max Step;Selection Max Step
Show in Cycle;Show in Cycle
Show in Menu;Show in Menu
Sort By;Sort By
Sort Only;Sort Only
Sort and Show;Sort and Show
Sound;Sound
Startup Mode;Startup Mode
Target;Target
Title;Title
Game Stats;Game Stats
Video Decoder;Video Decoder
Window Mode;Window Mode
Added $1 Collection/Romlist entries;Added $1 Collection/Romlist entries

# -- indexStrings --
Name;Name
Title;Title
Emulator;Emulator
CloneOf;CloneOf
Year;Year
Manufacturer;Manufacturer
Category;Category
Players;Players
Rotation;Rotation
Control;Control
Status;Status
DisplayCount;DisplayCount
DisplayType;DisplayType
AltRomname;AltRomname
AltTitle;AltTitle
Extra;Extra
Buttons;Buttons
Series;Series
Language;Language
Region;Region
Rating;Rating
Favourite;Favourite
Tags;Tags
PlayedCount;PlayedCount
PlayedTime;PlayedTime
PlayedLast;PlayedLast
FileIsAvailable;FileIsAvailable
Shuffle;Shuffle

# -- filterCompDisplayStrings --
contains;contains
does not contain;does not contain
does not equal;does not equal
equals;equals
greater than;greater than
less than;less than
greater than or equal;greater than or equal
less than or equal;less than or equal

# -- commandDispStrings --
Back;Back
Up;Up
Down;Down
Left;Left
Right;Right
Select;Select
Previous Game;Previous Game
Next Game;Next Game
Previous Page;Previous Page
Next Page;Next Page
Previous Display;Previous Display
Next Display;Next Display
Displays Menu;Displays Menu
Previous Filter;Previous Filter
Next Filter;Next Filter
Filters Menu;Filters Menu
Toggle Layout;Toggle Layout
Toggle Movie;Toggle Movie
Toggle Mute;Toggle Mute
Toggle Rotate Right;Toggle Rotate Right
Toggle Flip;Toggle Flip
Toggle Rotate Left;Toggle Rotate Left
Exit;Exit
Exit to Desktop;Exit to Desktop
Reload Layout;Reload Layout
Reload Config;Reload Config
Reset Window;Reset Window
Screenshot;Screenshot
Random Game;Random Game
Replay Last Game;Replay Last Game
Toggle Fullscreen;Toggle Fullscreen
Add/Remove Favourite;Add/Remove Favourite
Previous Favourite;Previous Favourite
Next Favourite;Next Favourite
Add/Remove Tags;Add/Remove Tags
Screen Saver;Screen Saver
Previous Letter;Previous Letter
Next Letter;Next Letter
Intro;Intro
Insert Game;Insert Game
Layout Options;Layout Options
Plugin Options;Plugin Options
Custom1;Custom1
Custom2;Custom2
Custom3;Custom3
Custom4;Custom4
Custom5;Custom5
Custom6;Custom6
Custom7;Custom7
Custom8;Custom8
Custom9;Custom9
Custom10;Custom10
Ambient Soundtrack;Ambient Soundtrack
Startup Sound;Startup Sound
Game Return Sound;Game Return Sound

# --uiColorDispTokens --
Indigo;Indigo
Blue;Blue
Cyan;Cyan
Turquoise;Turquoise
Green;Green
Acid;Acid
Gold;Gold
Yellow;Yellow
Orange;Orange
Brown;Brown
Rust;Rust
Red;Red
Pink;Pink
Magenta;Magenta
Purple;Purple
Grey;Grey
Neutral;Neutral
White;White

# --windowModeDispTokens --
Fill Screen;Fill Screen
Fullscreen;Fullscreen
Window;Window
Borderless Window;Borderless Window

# --screenRotationDispTokens --
Flip;Flip

# --startupDispTokens --
Show Last Selection;Show Last Selection
Show Random Selection;Show Random Selection
Launch Last Game;Launch Last Game
Show Displays Menu;Show Displays Menu

# --filterWrapDispTokens --
Wrap within Display;Wrap within Display
Jump to Next Display;Jump to Next Display
No Wrap;No Wrap

# -- settingDispStrings --
Sound Volume;Sound Volume
Ambient Volume;Ambient Volume
Movie Volume;Movie Volume
Loudness Normalisation;Loudness Normalisation

# -- splash_message --
Generating Romlist;Generating Romlist
Please Wait;Please Wait
Scraping Artwork;Scraping Artwork

# -- confirm_dialog --
Add '$1' to Favourites?;Add '$1' to Favourites?
Auto-detect emulators?;Auto-detect emulators?
Found 1 emulator;Found 1 emulator
Found $1 emulators;Found $1 emulators
No emulators found;No emulators found
+$1 more;+$1 more
Clear Hotkey?;Clear Hotkey?
Delete display '$1'?;Delete display '$1'?
Delete emulator '$1'?;Delete emulator '$1'?
Delete filter '$1'?;Delete filter '$1'?
Delete game '$1'?;Delete game '$1'?
Delete shortcut '$1'?;Delete shortcut '$1'?
Overwrite existing '$1' list?;Overwrite existing '$1' list?
Remove '$1' from Favourites?;Remove '$1' from Favourites?
Rom path '$1' not found, proceed?;Rom path '$1' not found, proceed?
Overwrite existing '$1' mapping?;Overwrite existing '$1' mapping?
A display with this name already exists;A display with this name already exists
Configuration files have been migrated\n to the 'config' folder.\nDelete old files?;Configuration files have been migrated\n to the 'config' folder.\nDelete old files?

# --input_map_dialog --
Press Hotkey;Press Hotkey
Press Input;Press Input

# -- edit_dialog --
Enter Display Name;Enter Display Name
Enter Emulator Name;Enter Emulator Name
Enter Filter Name;Enter Filter Name
Enter Tag Name;Enter Tag Name
Enter Romlist Name;Enter Romlist Name

# -- Titles --
Configure;Configure
Default Display Options;Default Display Options
Display Options;Display Options
Artwork Options;Artwork Options
Control Options;Control Options
Emulator Options;Emulator Options
Game Options;Game Options
Shortcut Options;Shortcut Options
Exception Options;Exception Options
Filter Options;Filter Options
Rule Options;Rule Options
Generate Collection/Romlist;Generate Collection/Romlist

# --indexDispStrings --
Executable;Executable
Command Arguments;Command Arguments
Working Directory;Working Directory
Rom Path(s);Rom Path(s)
Rom Extension(s);Rom Extension(s)
System Identifier;System Identifier
Info Source/Scraper;Info Source/Scraper
Additional Import File(s);Additional Import File(s)
Non-Blocking Mode Wait;Non-Blocking Mode Wait
Exit Hotkey;Exit Hotkey
Pause Hotkey;Pause Hotkey

# -- datetime --
_datetime;%Y-%m-%d %H:%M:%S
A Moment Ago;A Moment Ago
Never;Never
$1 Second;$1 Second
$1 Minute;$1 Minute
$1 Hour;$1 Hour
$1 Day;$1 Day
$1 Minute Ago;$1 Minute Ago
$1 Hour Ago;$1 Hour Ago
$1 Day Ago;$1 Day Ago
$1 Week Ago;$1 Week Ago
$1 Month Ago;$1 Month Ago
$1 Year Ago;$1 Year Ago
$1 Seconds;$1 Seconds
$1 Minutes;$1 Minutes
$1 Hours;$1 Hours
$1 Days;$1 Days
$1 Minutes Ago;$1 Minutes Ago
$1 Hours Ago;$1 Hours Ago
$1 Days Ago;$1 Days Ago
$1 Weeks Ago;$1 Weeks Ago
$1 Months Ago;$1 Months Ago
$1 Years Ago;$1 Years Ago

# -- help --
_help_art_add;Add a new artwork resource (marquee images, screen shots, etc.)
_help_art_label;The label that identifies this artwork resource (used by layouts)
_help_art_path;The path to the files for this artwork.  Multiple paths can be entered if separated by a semicolon.
_help_art;An artwork resource available for use by layouts
_help_back;Exit menu
_help_control_add_favourite;Set the control(s) that mark/unmark the currently selected game as a favourite
_help_control_add_tags;Set the control(s) that add/remove tags from the currently selected game
_help_control_back;Set the control(s) that go back
_help_control_configure;Set the control(s) that show the "Configuration Menu"
_help_control_custom1;Set the "Custom1" control(s)
_help_control_custom10;Set the "Custom10" control(s)
_help_control_custom2;Set the "Custom2" control(s)
_help_control_custom3;Set the "Custom3" control(s)
_help_control_custom4;Set the "Custom4" control(s)
_help_control_custom5;Set the "Custom5" control(s)
_help_control_custom6;Set the "Custom6" control(s)
_help_control_custom7;Set the "Custom7" control(s)
_help_control_custom8;Set the "Custom8" control(s)
_help_control_custom9;Set the "Custom9" control(s)
_help_control_displays_menu;Set the control(s) that show the "Displays Menu"
_help_control_down;Set the control(s) that move the selection down
_help_control_edit_game;Set the control(s) to edit the current selection
_help_control_exit_to_desktop;Set the control(s) that exit the frontend immediately to the desktop
_help_control_exit;Set the control(s) that exit the frontend
_help_control_filters_menu;Set the control(s) that show the "Filters Menu"
_help_control_insert_game;Set the control(s) that insert a new game entry
_help_control_intro;Set the control(s) that show the intro video
_help_control_joystick_map;Map the frontend's joystick slots to specifically named joystick/gamepad devices attached to your computer (You can use this to force the frontend to always use "Microsoft X-Box 360 pad" as Joystick 0, for example.)
_help_control_joystick_threshold;The threshold for registering joystick moves, from 1 to 100 (100=least sensitive)
_help_control_layout_options;Set the control(s) that show the "Layout Options" menu
_help_control_plugin_options;Set the control(s) that show the "Plugin Options" menu for the last viewed Plugin
_help_control_left;Set the control(s) that move the selection left
_help_control_mouse_threshold;The threshold for registering mouse moves, from 1 to 100 (100=least sensitive)
_help_control_next_display;Set the control(s) that move to the next display
_help_control_next_favourite;Set the control(s) that move to the next favourite
_help_control_next_filter;Set the control(s) that move to the next filter
_help_control_next_game;Set the control(s) that move to the next game
_help_control_next_letter;Set the control(s) that move to the next letter
_help_control_next_page;Set the control(s) that move the selection up one page
_help_control_prev_display;Set the control(s) that move to the previous display
_help_control_prev_favourite;Set the control(s) that move to the previous favourite
_help_control_prev_filter;Set the control(s) that move to the previous filter
_help_control_prev_game;Set the control(s) that move to the previous game
_help_control_prev_letter;Set the control(s) that move to the previous letter
_help_control_prev_page;Set the control(s) that move the selection down one page
_help_control_random_game;Set the control(s) that select a random game from the current list
_help_control_reload_layout;Set the control(s) that reloads the current layout
_help_control_reload_config;Set the control(s) that reloads the configuration files
_help_control_reset_window;Set the control(s) that resets the window size and position
_help_control_replay_last_game;Set the control(s) that relaunch the last game played
_help_control_right;Set the control(s) that move the selection right
_help_control_screen_saver;Set the control(s) that launch screen saver mode
_help_control_screenshot;Set the control(s) that take a screenshot of the frontend
_help_control_select;Set the control(s) that launch the current selection
_help_control_selection_speed;Set the speed of selection movement in milliseconds per step, default is 40
_help_control_selection_delay;Set the delay in milliseconds before key repeat begins, default is 400
_help_control_selection_max_step;Set the maximum step size for selection movement, default is 128
_help_control_toggle_flip;Set the control(s) that toggle whether the display should be rotated 180 degrees
_help_control_toggle_fullscreen;Toggle the Window Mode between Fullscreen and Window
_help_control_toggle_layout;Set the control(s) that toggle the layout script to use (It depends on the layout you are using whether this does anything)
_help_control_toggle_movie;Set the control(s) that toggle whether or not videos should be played
_help_control_toggle_mute;Set the control(s) that mute/unmute frontend sound
_help_control_toggle_rotate_left;Set the control(s) that toggle whether the display should be rotated 90 degrees to the left
_help_control_toggle_rotate_right;Set the control(s) that toggle whether the display should be rotated 90 degrees to the right
_help_control_up;Set the control(s) that move the selection up
_help_display_add_filter;Add a filter to this display's filter set
_help_display_add;Add a new display
_help_display_delete;Delete this display
_help_display_filter;Configure this filter from the display's filter set
_help_display_global_filter;Configure global filter rules that are applied to every entry in this display's collection/romlist
_help_display_in_cycle;Include this display in the "Previous Display"/"Next Display" cycle
_help_display_in_menu;Include this display in the "Displays Menu"
_help_display_layout_options;Configure any layout-specific options
_help_display_layout;The layout to use for this display
_help_display_name;The title for this display
_help_display_romlist;The collection/romlist to use for this display
_help_display_sel;Configure display
_help_display_edit_default;Configure the default options to use for new Displays
_help_displaysmenu_exit;Configure whether an Exit option should be provided in the Displays Menu
_help_displaysmenu_layout;The layout to use for the Displays Menu. Set to "Default" to use the frontend's built-in menu
_help_displaysmenu_prompt;The Displays Menu prompt (i.e. "Select System")
_help_displaysmenu;Configure options for the Displays Menu
_help_emu_add;Add a new emulator
_help_emu_args;The command line arguments for this emulator.  The following get substituted appropriately: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn], [workdir], [nothing], as well as any valid magic tokens (see layout documentation)
_help_emu_delete;Delete the entry for this emulator
_help_emu_executable;The full path and name of the emulator executable. Possible variables: $HOME = User's home dir, $PROGDIR = Attract-Mode Plus program dir. Windows OS additionally have %SYSTEMROOT% and %PROGRAMFILES% matching system environment variables.
_help_emu_exit_hotkey;Set a global hotkey to exit the emulator.  Attract-Mode Plus will terminate the emulator process if this hotkey gets pressed
_help_emu_gen_romlist;Generate a romlist by searching the configured rom path for roms with the configured extension, incorporating XML and additional import file information into the generated list (if available)
_help_emu_import_extras;Path to any additional files that need to be read when generating a romlist for this emulator.  Supported files are: catver.ini (categories), nplayers.ini (number of players), series.ini (series), languages.ini (languages) and mame.xml.  Multiple file paths can be entered if separated by a semicolon
_help_emu_info_source;Use "listxml" for mame -listxml output, "listsoftware" for mame/mess -listsoftware output, "thegamesdb.net" to scrape data from thegamesdb.net, "steam" to read from a steam installation, or "scummvm" if the emulator is scummvm.  "listsoftware" and "thegamesdb.net" also require that a System Identifier recognized by those sources be configured
_help_emu_name;Emulator Options
_help_emu_nb_mode_wait;If this is non-zero, the emulator will be run in non-blocking mode.  The frontend will wait up to this number of seconds to lose focus to the emulator's window, and will wake up again when focus returns to the frontend's window.  This is necessary for launching programs like Steam correctly.  Should be 0 unless you know you need it
_help_emu_pause_hotkey;Set a global hotkey to pause the emulator.  When pressed, Attract-Mode Plus will pause the emulator process and return to the frontend. The emulator process can be resumed by selecting the same game again in the frontend.
_help_emu_romext;The rom extension(s) for this emulator (i.e. .zip).  Multiple extensions can be entered if separated by a semicolon.  Specify "<DIR>" as an entry if games are stored in separate subdirectories
_help_emu_rompath;The path to the roms for this emulator.  Multiple paths can be entered if separated by a semicolon.
_help_emu_scrape_artwork;Scrape missing artwork images for this emulator from the net
_help_emu_sel_auto_detect;This will scan parent folder for known emulators and generate default configurations for every emulator found
_help_emu_sel_gen_romlist;Generate a Collection/Romlist containing games for multiple emulators
_help_emu_sel;Configure emulator
_help_emu_system;The system identifier(s) for this emulator.  Multiple values can be entered if separated by a semicolon
_help_emu_workdir;The working directory for this emulator.  This is the directory that the frontend runs the emulator from.  Also, any relative rom paths, artwork paths, or additional import file paths are treated as being relative to this directory
_help_filter_add_exception;Add an exception to this filter.  If a game matches an exception (and wasn't filtered out by an earlier rule) it will be listed in the filter
_help_filter_add_rule;Add a rule to this filter.  A game must match all filter rules (or a single exception) to be listed in a filter
_help_filter_delete;Delete this filter
_help_filter_exception;Configure this filter exception.  If a game matches an exception it will be listed in the filter.  Rules and exceptions get applied in the order that they are listed
_help_filter_list_limit;Set this to a non-zero value if you wish to limit the size of a sorted list.  Use a positive value for the first X entries (i.e. "10" gives the first 10 entries), a negative value for the last X entries (i.e. "-25" gives the last 25 entries), or "0" for no limit
_help_filter_name;The name for this filter
_help_filter_reverse_order;Reverse the order of the sorted collection/romlist.  Default order is "A to Z" for info, "Largest to Smallest" for stats, or the source list order for "No Sort"
_help_filter_rule;Configure this filter rule.  A game must match all filter rules (or a single exception) to be listed in a filter
_help_filter_sort_by;The game information attribute that you wish to sort the collection/romlist by.  Set to "No Sort" to keep the ordering from the source collection/romlist
_help_game_custom_args;Set this to override the default command line arguments for this game.  Set this to [nothing] if you want to override with no parameters.  The following get substituted appropriately: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_game_custom_executable;Set this to override the default executable for this game
_help_game_delete;Delete this game from the Romlist
_help_game_edit;Edit this game information
_help_game_overview;Edit game overview
_help_generator_build;Generate romlist with the selected emulator(s)
_help_generator_opt;Set whether this emulator is to be included in the generated romlist
_help_input_action;Configure Action
_help_input_add;Add a new input mapping for this control
_help_input_default_action;Set the default behaviour for this control
_help_input_delete;Remove this input mapping
_help_layout_file;Some layouts provide multiple layout*.nut files.  Select which layout file to use
_help_layout_name;Layout Options
_help_main_control;Configure the joystick, keyboard and mouse inputs that control Attract-Mode Plus
_help_main_display;Configure the romlist/layout groupings (a.k.a. "Displays") that are available to be cycled through in Attract-Mode Plus
_help_main_emu;Configure emulator options
_help_main_intro;Configure intro options
_help_main_settings;Configure general options
_help_main_plugin;Configure plugin options
_help_main_scraper;Configure scraper options
_help_main_screensaver_timeout;The amount of time in seconds to wait before switching to the screen saver.  0 to disable
_help_main_screensaver;Configure screen saver
_help_main_sound;Configure sound volumes, sound event mappings and the ambient soundtrack
_help_misc_anisotropic_filtering;Set the anisotropic filtering level for textures. This will improve the quality of scaled textures
_help_misc_antialiasing;Set the anti-aliasing level
_help_misc_check_for_updates;Configure whether Attract-Mode Plus should check for available updates on startup and display an update notification dialog when a new version is found.
_help_misc_confirm_exit;Confirm the exiting of Attract-Mode Plus
_help_misc_confirm_favs;Confirm the addition/removal of Favourites
_help_misc_custom_overlay;Allow layouts to customise the overlay used for Display, Filter, Tag, and Exit menus
_help_misc_exit_command;Command to execute when exiting the frontend [i.e. "sudo shutdown"]
_help_misc_exit_message;Alternate message to exit the frontend [i.e. "Shut Down System"]
_help_misc_filter_wrap_mode;Set what happens when the "Next Filter" or "Previous Filter" actions reach the end of the filter set
_help_misc_group_clones;Group all clones of a game under one single list entry
_help_misc_hide_brackets;Hide text in brackets when showing game titles
_help_misc_prefix_modes;Move "The" and "Vs." prefixes to the end of the game title
_help_misc_hide_console;Hide console on startup. Note that this only works if starting Attract-Mode Plus from a Windows GUI. If started from an existing console window (e.g. a batch file) then the process will always "attach" to the existing console and output to it
_help_misc_image_cache_mbytes;Configure the maximum size of Attract-Mode Plus's internal image cache (in megabytes)
_help_misc_language;Select the language to use in Attract-Mode Plus's user interface
_help_misc_layout_preview;Show layout configuration changes immediately
_help_misc_multiple_monitors;Enable the use of multiple monitors by Attract-Mode Plus.  Setting this to "No" may reduce screen flicker when launching games
_help_misc_power_saving;Helps to save power by only redrawing the screen when it's necessary. May cause animation stuttering on some layouts, or freezing on Linux
_help_misc_quick_menu;Set whether menus can be opened and closed using the same button.  Also enables switching between menus without having to close them first
_help_misc_screen_rotation;Set the base rotation of the screen
_help_misc_startup_mode;Set what should happen when Attract-Mode Plus first starts up
_help_misc_track_usage;Configure whether Attract-Mode Plus should track usage (played time and play count for each game)
_help_misc_ui_color;Select the colour to use in Attract-Mode Plus's user interface
_help_misc_video_decoder;Configure the decoder to use for video playback (if multiple decoders are available)
_help_misc_window_mode;Set whether Attract-Mode Plus fills the screen or runs in a window
_help_plugin_command;The executable associated with this plugin
_help_plugin_enabled;Set whether this plugin is enabled
_help_plugin_name;Plugin Options
_help_plugin_sel;Plugin Options
_help_rule_comp;Comparison type for the filter
_help_rule_delete;Delete this filter rule
_help_rule_target;The game information attribute that you wish to filter based on
_help_rule_value;The regular expression value to filter to.  For example, if the filter target is "Year" and comparison is "equals", a value of "1984" will match the year of 1984, "198." will match any year in the 80s, and "(198.)|(199.)" will match any year in the 80s or 90s
_help_scraper_fanart;Set whether game fanart should be downloaded when scraping
_help_scraper_flyers;Set whether game flyers and box covers should be downloaded when scraping
_help_scraper_marquees;Set whether game marquees and banners should be downloaded when scraping
_help_scraper_snaps;Set whether game snapshots should be downloaded when scraping
_help_scraper_vids;Set whether game videos should be downloaded when scraping
_help_scraper_wheels;Set whether game logos should be downloaded when scraping
_help_shortcut_artwork_name;Optionally provide an artwork name to be associated with this shortcut.  The frontend will try to load artworks with this name when displaying the shortcut
_help_shortcut_delete;Delete this shortcut from the Romlist
_help_shortcut_label;Edit this shortcut's label
_help_shortcut_target;Edit this shortcut's target
_help_sound_loudness_normalisation;Enable an audio effect that automatically boosts quiet media to a consistent volume level
_help_sound_sel;Assign a sound to this event/action
_help_sound_volume;Set the volume for this audio source

# -- screensaver --

Basic Movie;Basic Movie
Movie Collage;Movie Collage
Image Collage;Image Collage
RGB Movie;RGB Movie
Overlay Artwork;Overlay Artwork
Play Sound;Play Sound
Preserve Aspect Ratio;Preserve Aspect Ratio
Blank Screen Time;Blank Screen Time
Blank Screen Start Command;Blank Screen Start Command
Blank Screen Stop Command;Blank Screen Stop Command
Play intro;Play intro
Detect aspect ratio;Detect aspect ratio
Default video;Default video
16:9 video;16:9 video
4:3 video;4:3 video
9:16 video;9:16 video
3:4 video;3:4 video

# -- extra --
