#@Español

# -- generic --
$1 Rule(s);$1 Regla(s)
Blank Game;Juego en blanco
Custom;Personalizado
Default;Predeterminado
Disabled;Desactivado
Empty;Vacío
False;Falso
Multi;Multijugador
No Sort;No ordenar
No;Número
None;Ninguno
Off;Desactivado
On;Activado
OR;O
True;Verdadero
Yes;Si
Import;Importar
Cancel;Cancelar

# -- misc --
Press TAB to Configure;Pulse TAB para configurar
Displays Menu Options;Mostrar opciones del menú
Action;Acción
Add Artwork;Agregar tema
Add Emulator;Agregar emulador
Add Exception;Añadir excepción
Add Filter;Agregar filtro
Add Input;Agregar control
Add Display;Agregar pantalla
Add Rule;Agregar regla
Allow Exit;Permitir salida
Anisotropic Filtering;Filtrado anisotrópico
Anti-Aliasing (MSAA);Antialiasing (MSAA)
Artwork Label;Nombre del tema
Artwork Name;Nombre de la obra de arte
Artwork Path;Ruta del tema
Auto-detect Emulators;Detección automática de emuladores
Check for Updates;Buscar actualizaciones
Collection/Romlist;Colección/Lista de roms
Comparison;Comparación
Confirm Exit;Confirmar salida
Confirm Favourites;Confirmar Favoritos
Controls;Controles
Add Tag;Agregar etiqueta
Custom Arguments;Argumentos personalizados
Custom Executable;Ejecutable personalizado
Custom Overlay;Superposición personalizada
Default Action;Acción predeterminada
Delete this Display;Borrar esta Pantalla
Delete this Emulator;Suprimir este Emulador
Delete this Filter;Borrar este Filtro
Delete this Game;Eliminar este juego
Delete this Rule;Borrar esta Regla
Delete this Shortcut;Eliminar este acceso directo
Displays;Pantallas
Emulator Name;Nombre del Emulador
Emulators;Emuladores
Multiple Monitors;Múltiples Monitores
Enabled;activado
Exception;Excepción
Exit Attract-Mode Plus;Salir de Attract-Mode Plus
Exit Attract-Mode Plus?;Salir de Attract-Mode Plus?
Exit Command;Comando de salida
Exit Message;Mensaje de salida
Filter Name;Nombre del Filtro
Filter Value;Valor del Filtro
Filter Wrap Mode;Modo de Ciclado de Filtro
Filter;Filtro
Settings;Ajustes
Global Filter;Filtro Global
Group Clones;Agrupar clones
Hide Game Title Brackets;Ocultar corchetes del título del juego
Format Game Title;Formato del título del juego
Hide Console;Ocultar consola
Image Cache Size;Tamaño de caché de imágenes
Insert Command Shortcut;Insertar acceso directo a comandos
Insert Display Shortcut;Insertar acceso directo a la pantalla
Insert Game Entry;Insertar entrada de juego
Insert Menu Entry;Insertar entrada de menú
Joystick $1;Joystick $1
Joystick Mappings;Asignación de joystick
Joystick Threshold;Umbral de la palanca
Language;Idioma
Layout File;Archivo de diseño
Layout Preview;Vista previa del diseño
Layout;Tema
List Limit;Límite de lista
Menu Colour;Color del menú
Menu Prompt;Menú
Menu Toggle;Alternar menú
Mouse Threshold;Umbral del ratón
Overview;Resumen
Plugins;Complementos
Power Saving;Ahorro de energía
Remove Input;Eliminar control
Reverse Order;Orden inverso
Rule;Regla
Scrape Artwork;Extraer carátulas
Scrape Fanart;Extraer fanart
Scrape Flyers/Boxart;Extraer folletos/carátulas
Scrape Game Logos (Wheel Art);Extraer logotipos de juegos (arte de la rueda)
Scrape Marquees;Extraer imágenes de la pantalla
Scrape Snaps;Extraer capturas de pantalla
Scrape Videos (MAME only);Extraer vídeos (solo MAME)
Scraper;Extractor
Screen Rotation;Rotación de pantalla
Screen Saver Timeout;Límite de tiempo para el salvapantalla
Selection Delay;Retardo de selección
Show in Cycle;Mostrar en ciclo
Show in Menu;Mostrar en el menú
Sort By;Ordenado por
Sort Only;Solo ordenar
Sort and Show;Ordenar y mostrar
Sound;Sonido
Startup Mode;Modo de inicio
Target;Objetivo
Title;Título
Game Stats;Estadísticas del juego
Video Decoder;Decodificador de vídeo
Window Mode;Modo ventana
Added $1 Collection/Romlist entries;Se añadieron $1 entradas a la colección/lista de ROMs

# -- indexStrings --
Name;Nombre
Title;Título
Emulator;Emulador
CloneOf;Clon de
Year;Año
Manufacturer;Fabricante
Category;Categoría
Players;Jugadores
Rotation;Rotación
Control;Controles
Status;Estado
DisplayCount;Contador de pantalla
DisplayType;Tipo de pantalla
AltRomname;Nombre de rom alternativo
AltTitle;Título alternativo
Extra;Extra
Buttons;Botones
Series;Serie
Language;Idioma
Region;Región
Rating;Clasificación
Favourite;Favorito
Tags;Etiquetas
PlayedCount;Cuenta de partidas
PlayedTime;Tiempo jugado
PlayedLast;Último juego jugado
FileIsAvailable;Archivo disponible
Shuffle;Aleatorio

# -- filterCompDisplayStrings --
contains;contiene
does not contain;no contiene
does not equal;no es igual a
equals;igual
greater than;mayor que
less than;menor que
greater than or equal;mayor o igual que
less than or equal;menor o igual que

# -- commandDispStrings --
Back;Volver
Up;Arriba
Down;Abajo
Left;Izquierda
Right;Derecha
Select;Seleccionar
Previous Game;Juego anterior
Next Game;Siguiente juego
Previous Page;Página posterior
Next Page;Página anterior
Previous Display;Pantalla previa
Next Display;Pantalla siguiente
Displays Menu;Mostrar menú
Previous Filter;Filtro anterior
Next Filter;Filtro posterior
Filters Menu;Menú de filtros
Toggle Layout;Cambiar tema
Toggle Movie;Cambiar video
Toggle Mute;Silenciar
Toggle Rotate Right;Rotar a la derecha
Toggle Flip;Invertir
Toggle Rotate Left;Rotar a la izquierda
Exit;Salir (Confirmación)
Exit to Desktop;Salir a escritorio
Reload Layout;Recharger la mise en page
Reload Config;Recharger la configuration
Reset Window;Restablecer ventana
Screenshot;Captura de pantalla
Random Game;Juego aleatorio
Replay Last Game;Repetir el último juego
Toggle Fullscreen;Activar/Desactivar pantalla completa
Add/Remove Favourite;Agregar/eliminar favoritos
Previous Favourite;Anterior favorito
Next Favourite;Siguiente favorito
Add/Remove Tags;Agregar/Remover etiquetas
Screen Saver;Potector de pantalla
Previous Letter;Letra previa
Next Letter;Letra siguiente
Intro;Introducción
Insert Game;Insertar juego
Layout Options;Opciones de temas
Plugin Options;Opciones del plugin
Custom1;Personalizado 1
Custom2;Personalizado 2
Custom3;Personalizado 3
Custom4;Personalizado 4
Custom5;Personalizado 5
Custom6;Personalizado 6
Custom7;Personalizado 7
Custom8;Personalizado 8
Custom9;Personalizado 9
Custom10;Personalizado 10
Ambient Soundtrack;Canción de sonido de ambiente
Startup Sound;Sonido de inicio
Game Return Sound;Sonido de retorno al juego

# --uiColorDispTokens --
Indigo;Índigo
Blue;Azul
Cyan;Cian
Turquoise;Turquesa
Green;Verde
Acid;Ácido
Gold;Oro
Yellow;Amarillo
Orange;Naranja
Brown;Marrón
Rust;Óxido
Red;Rojo
Pink;Rosa
Magenta;Magenta
Purple;Morado
Grey;Gris
Neutral;Neutro
White;Blanco

# --windowModeDispTokens --
Fill Screen;Llenar pantalla
Fullscreen;Pantalla completa
Window;Ventana
Borderless Window;Ventana sin bordes

# --screenRotationDispTokens --
Flip;Invertir

# --startupDispTokens --
Show Last Selection;Mostrar última selección
Show Random Selection;Mostrar selección aleatoria
Launch Last Game;Iniciar último juego
Show Displays Menu;Mostrar menú de pantallas

# --filterWrapDispTokens --
Wrap within Display;Ciclar dentro de la pantalla
Jump to Next Display;Saltar a la siguiente pantalla
No Wrap;No ciclar

# -- settingDispStrings --
Sound Volume;Volumen general
Ambient Volume;Volumen de ambiente
Movie Volume;Volumen de videos
Loudness Normalisation;Normalización de volumen

# -- splash_message --
Generating Romlist;Generación de lista de roms
Please Wait;Espere, por favor
Scraping Artwork;Extraer carátulas

# -- confirm_dialog --
Add '$1' to Favourites?;¿Añadir '$1' a favoritos?
Auto-detect emulators?;¿Detectar emuladores automáticamente?
Found 1 emulator;Se encontró 1 emulador
Found $1 emulators;Encontrados $1 emuladores
No emulators found;No se encontraron emuladores
+$1 more;+$1 más
Clear Hotkey?;¿Borrar tecla de acceso rápido?
Delete display '$1'?;¿Desea borrar la pantalla '$1'?
Delete emulator '$1'?;¿Desea borrar el emulador '$1'?
Delete filter '$1'?;¿Desea borrar el filtro '$1'?
Delete game '$1'?;¿Eliminar juego '$1'?
Delete shortcut '$1'?;¿Eliminar acceso directo '$1'?
Overwrite existing '$1' list?;¿Desea sobreescribir la lista de roms '$1'?
Remove '$1' from Favourites?;¿Eliminar '$1' de favoritos?
Rom path '$1' not found, proceed?;No se encontró la ruta de la ROM '$1', ¿continuar?
Overwrite existing '$1' mapping?;¿Sobrescribir la asignación existente de '$1'?
A display with this name already exists;Ya existe una pantalla con este nombre
Configuration files have been migrated\n to the 'config' folder.\nDelete old files?;Los archivos de configuración se han migrado\n a la carpeta 'config'.\n¿Eliminar archivos antiguos?

# --input_map_dialog --
Press Hotkey;Pulsar tecla de acceso rápido
Press Input;Presionar control

# -- edit_dialog --
Enter Display Name;Ingrese el nombre de la pantalla
Enter Emulator Name;Ingrese el nombre del emulador
Enter Filter Name;Ingrese el nombre para el filtro
Enter Tag Name;Introducir nombre de etiqueta
Enter Romlist Name;Introducir nombre de la lista de ROMs

# -- Titles --
Configure;Configuración
Default Display Options;Opciones de visualización predeterminadas
Display Options;Opciones de visualización
Artwork Options;Opciones de gráficos
Control Options;Opciones de control
Emulator Options;Opciones del emulador
Game Options;Opciones del juego
Shortcut Options;Opciones de acceso directo
Exception Options;Opciones de excepciones
Filter Options;Opciones de filtro
Rule Options;Opciones de reglas
Generate Collection/Romlist;Generar lista de roms

# --indexDispStrings --
Executable;Ejecutable
Command Arguments;Argumentos
Working Directory;Directorio de trabajo
Rom Path(s);Ruta(s) de roms
Rom Extension(s);Extension(es) de roms
System Identifier;Identificador de sistema
Info Source/Scraper;Fuente de información/Scraper
Additional Import File(s);Archivos de importación adicionales
Non-Blocking Mode Wait;Modo de espera no bloqueante
Exit Hotkey;Tecla rápida de salida
Pause Hotkey;Pausar tecla de acceso rápido

# -- datetime --
_datetime;%Y-%m-%d %H:%M:%S
A Moment Ago;Hace un momento
Never;Nunca
$1 Second;$1 segundo
$1 Minute;$1 minuto
$1 Hour;$1 hora
$1 Day;$1 día
$1 Minute Ago;Hace $1 minuto
$1 Hour Ago;Hace $1 hora
$1 Day Ago;Hace $1 día
$1 Week Ago;Hace $1 semana
$1 Month Ago;Hace $1 mes
$1 Year Ago;Hace $1 año
$1 Seconds;$1 segundo
$1 Minutes;$1 minuto
$1 Hours;$1 hora
$1 Days;$1 día
$1 Minutes Ago;Hace $1 minuto
$1 Hours Ago;Hace $1 hora
$1 Days Ago;Hace $1 día
$1 Weeks Ago;Hace $1 semana
$1 Months Ago;Hace $1 mes
$1 Years Ago;Hace $1 año

# -- help --
_help_art_add;Agregar una nueva fuente de artwork (marquesinas, capturas de pantalla, etc.)
_help_art_label;Etiqueta que identifica este artwork (usado por los temas)
_help_art_path;Ruta a los archivos de este artwork. Es posible ingresar multiples rutas separadas por punto y coma.
_help_art;Una fuente de artwork disponible para ser usado por el temas
_help_back;Salir del menu
_help_control_add_favourite;Configura el(los) control(es) que marca/desmarca el juego actualmente seleccionado como favorito
_help_control_add_tags;Configura el(los) control(es) que agragan/remueven etiquetas del juego actualmente seleccionado
_help_control_back;Establecer los controles para volver atrás
_help_control_configure;Configura el(los) control(es) que muestra el "Menú de configuración"
_help_control_custom1;Configura el(los) control(es) "Personalizado1"
_help_control_custom10;Configura el(los) control(es) "Personalizado10"
_help_control_custom2;Configura el(los) control(es) "Personalizado2"
_help_control_custom3;Configura el(los) control(es) "Personalizado3"
_help_control_custom4;Configura el(los) control(es) "Personalizado4"
_help_control_custom5;Configura el(los) control(es) "Personalizado5"
_help_control_custom6;Configura el(los) control(es) "Personalizado6"
_help_control_custom7;Configura el(los) control(es) "Personalizado7"
_help_control_custom8;Configura el(los) control(es) "Personalizado8"
_help_control_custom9;Configura el(los) control(es) "Personalizado9"
_help_control_displays_menu;Configurar el(los) control(es) que "muestra el menú"
_help_control_down;Configurar el(los) control(es) que mueven hacia abajo la selección
_help_control_edit_game;Establece los controles para editar el juego. Selección actual
_help_control_exit_to_desktop;Configura el(los) control(es) que sale del frontend inmediatamente al escritorio
_help_control_exit;Configura el(los) control(es) que cierran el frontend
_help_control_filters_menu;Configurar el(los) control(es) que muestran el "Menú de filtros"
_help_control_insert_game;Establece los controles para insertar una nueva entrada de juego
_help_control_intro;Establece los controles que muestran el vídeo de introducción.
_help_control_joystick_map;Asigna los joysticks del frontend a los joysticks/mandos conectados a tu ordenador (por ejemplo, puedes usar esta opción para que el frontend use siempre "Mando de Microsoft Xbox 360" como Joystick 0).
_help_control_joystick_threshold;Umbral para los movimientos de palanca registrados, de 1 a 100 (100=menos sensible)
_help_control_layout_options;Establece los controles que muestran el menú "Opciones de diseño".
_help_control_plugin_options;Establece los controles que muestran el menú "Opciones de plugin" para el último plugin visualizado.
_help_control_left;Establecer los controles que mueven la selección a la izquierda
_help_control_mouse_threshold;Umbral para los movimientos del ratón, de 1 a 100 (100=menos sensible)
_help_control_next_display;Configurar el(los) control(es) que mueven hacia la pantalla siguiente
_help_control_next_favourite;Configura el(los) control(es) que mueven hacia el favorito siguiente
_help_control_next_filter;Configurar el(los) control(es) que mueven hacia el filtro siguiente
_help_control_next_game;Establece los controles que pasan al siguiente juego.
_help_control_next_letter;Configura el(los) control(es) que mueve hacia la letra siguiente
_help_control_next_page;Configurar el(los) control(es) que mueven hacia abajo una página la selección
_help_control_prev_display;Configurar el(los) control(es) que mueven hacia la pantalla previa
_help_control_prev_favourite;Configura el(los) control(es) que mueven hacia el favorito previo
_help_control_prev_filter;Configurar el(los) control(es) que mueven hacia el filtro previo
_help_control_prev_game;Establece los controles que te llevan al juego anterior.
_help_control_prev_letter;Configura el(los) control(es) que mueve hacia la letra previa
_help_control_prev_page;Configurar el(los) control(es) que mueven hacia arriba una página la selección
_help_control_random_game;Configura el(los) control(es) que selecciona un jego aleatorio de la lista actual
_help_control_reload_layout;Establece los controles que recargan la pantalla actual. layout
_help_control_reload_config;Configura los controles que recargan los archivos de configuración.
_help_control_reset_window;Establecer los controles para restablecer el tamaño y la posición de la ventana
_help_control_replay_last_game;Configura el(los) control(es) que relanza el último juego jugado
_help_control_right;Establece los controles que mueven la selección a la derecha.
_help_control_screen_saver;Configura el(los) control(es) que lanzan el protector de pantalla
_help_control_screenshot;Configura el(los) control(es) que toma una captura de pantalla del frontend
_help_control_select;Configura los el(los) control(es) que lanzan la selción actual
_help_control_selection_delay;Establece el retardo en milisegundos antes de que comience la repetición de teclas; el valor predeterminado es 400.
_help_control_toggle_flip;Configura el(los) control(es) que cambia si la pantalla debe ser rotada o no 180 grados
_help_control_toggle_fullscreen;Alterna el modo de ventana entre pantalla completa y ventana.
_help_control_toggle_layout;Configura el(los) control(es) que cambia el script de tema a usar (Depende del tema que está usando si esto hace algo)
_help_control_toggle_movie;Configura el(los) control(es) que cambia si los videos son o no reproducidos
_help_control_toggle_mute;Configura el(los) control(es) que silencia o no el sonido del frontend
_help_control_toggle_rotate_left;Configura el(los) control(es) que cambia si la pantalla debe ser rotada o no 90 grados a la izquierda
_help_control_toggle_rotate_right;Configura el(los) control(es) que cambia si lapantalla debe ser rotada o no 90 grados a la derecha
_help_control_up;Configurar el(los) control(es) que mueven hacia arriba la selección
_help_display_add_filter;Agregar un filtro a este conjunto de filtros de pantalla
_help_display_add;Agragar una nueva pantalla
_help_display_delete;Borra esta pantalla
_help_display_filter;Configura este filtro desde el conjunto de filtros de pantalla
_help_display_global_filter;Configura reglas globales de filtros que son aplicados a cada entrada de la lista de roms de esta pantalla
_help_display_in_cycle;Incluir esta pantalla en el ciclo "Pantalla anterior"/"Pantalla siguiente"
_help_display_in_menu;Incluir esta pantalla en el menú de pantallas
_help_display_layout_options;Configurar cualquier opción especifica de temas
_help_display_layout;Tema usado para esta pantalla
_help_display_name;Nombre de la pantalla
_help_display_romlist;Colección/lista de roms usada para esta pantalla
_help_display_sel;Configurar pantalla
_help_display_edit_default;Configura las opciones predeterminadas para las nuevas pantallas
_help_displaysmenu_exit;configura si la opción de Salir debe ser provista en el "menú de pantallas"
_help_displaysmenu_layout;El diseño del menú de visualización. Selecciona "Predeterminado" para usar el menú integrado del frontend.
_help_displaysmenu_prompt;El mensaje del menú de pantallas (p. ej., "Seleccionar sistema")
_help_displaysmenu;Configura las opciones del menú de visualización.
_help_emu_add;Agrega un nuevo emulador
_help_emu_args;Argumento de linea de comandos usado por este emulador.  Los siguientes pueden ser propiamente sustituidos: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;Borra la entrada para este emulador
_help_emu_executable;Ruta completa y nombre del ejecutable del emulador. $HOME es reemplazado por con el directorio home del usuario
_help_emu_exit_hotkey;Configura una tecla global para salir del emulador. Attract-Mode Plus terminará el proceso del emulador si esta tecla es presionada
_help_emu_gen_romlist;Genera una lista de roms buscando en las rutas de roms configuradas con las extensiones configuradas, incorporando XML e importando información adicional a la lista generada (si está disponible)
_help_emu_import_extras;Ruta de cualquier archivo adicional que neceiste ser leido cuando se genera la lista de roms para este emulador.  Los archivos soportados son: catver.ini (para categorias de juegos) y nplayers.ini (para el número de jugadores). Es posible ingresar multiples rutas separadas por punto y coma.
_help_emu_info_source;Use "listxml" si el emulador prove la salida de mame -listxml, "listsoftware" para la salida de mame/mess -listsoftware, "thegamesdb.net" para extraer información desde thegamesdb.net, o "steam" para leer desde una instalación de steam.  "listsoftware" y "thegamesdb.net" también requieren que sea configurado un identificador de sistema reconocible por esas fuentes
_help_emu_name;Editar emulador
_help_emu_nb_mode_wait;Configura un tiempo mínimo de ejecución (en segundos).  Attract-Mode Plus esperará después de ejecutar este emulador hasta que haya transcurrido el tiempo mínimo de ejecución y pasará a ejecución de fondo. Esto necesita ser configurado por Steam para funcionar correctamente en Windows. Configure esto en 0 a menos que sepa que lo necesita
_help_emu_pause_hotkey;Establece una tecla de acceso rápido global para pausar el emulador. Al pulsarlo, Attract-Mode Plus pausará el proceso del emulador y volverá a la interfaz. El proceso del emulador se puede reanudar seleccionando de nuevo el mismo juego en la interfaz.
_help_emu_romext;Extensión(es) para este emulador (por ej. .zip). Es posible ingresar multiples extensiones separadas por punto y coma. Especificar "<DIR>" como entrada si los juegos se encuientran en subdirectorios separados
_help_emu_rompath;Ruta a las roms para este emulador.  Es posible ingresar multiples rutas separadas por punto y coma.
_help_emu_scrape_artwork;Scrape missing artwork images for this emulator from TheGamesDB.net and mamedb.com
_help_emu_sel_auto_detect;Esto escaneará la carpeta principal en busca de emuladores conocidos y generará configuraciones predeterminadas para cada emulador encontrado.
_help_emu_sel_gen_romlist;Genera una colección/lista de ROMs con juegos para varios emuladores
_help_emu_sel;Configura el emulador
_help_emu_system;Identificador(es) de sistema para este emulador. Es posible ingresar multiples valores separadas por punto y coma.
_help_emu_workdir;El directorio de trabajo de este emulador. Este es el directorio desde donde se ejecuta el emulador en la interfaz. Además, cualquier ruta relativa a ROMs, rutas de carátulas o rutas de archivos de importación adicionales se tratará como relativa a este directorio.
_help_filter_add_exception;Añade una excepción a este filtro. Si un juego coincide con una excepción (y no fue filtrado por una regla anterior), aparecerá en la lista del filtro.
_help_filter_add_rule;Agrega una regla para este filtro
_help_filter_delete;Borrar este filtro
_help_filter_exception;Configura esta excepción de filtro. Si un juego coincide con una excepción, aparecerá en el filtro. Las reglas y excepciones se aplican en el orden en que aparecen.
_help_filter_list_limit;Configurar esto a cero si desea limitar el tamaño de una lista ordenada. Use un valor positivo para las X primeras entradas (por ej. "10" entrega las primeras 10 entradas), un valor negativo para las últimas X entradas (por ej. "-25" entrega las últimas 25 entradas), o "0" para ilimitado
_help_filter_name;Name ára este filtro
_help_filter_reverse_order;Invierte el orden de la colección/lista de ROMs. El orden predeterminado es de la A a la Z para información, de mayor a menor para estadísticas o el orden de la lista de origen para "Sin ordenar".
_help_filter_rule;Configura regla para el filtro
_help_filter_sort_by;Atriburo del juego a partir del cual desea que la colección/lista de roms sea ordenada. Configure a "No ordenar" para mantener el orden de la colección/lista de romo
_help_game_custom_args;Establece esto para anular los argumentos de línea de comandos predeterminados para este juego. Déjalo en blanco si quieres anularlos sin parámetros. Se sustituyen los siguientes elementos según corresponda: [nombre], [romext], [ruta_rom], [emulador], [nombre_archivo_rom], [sistema], [sisteman]
_help_game_custom_executable;Establece esto para anular el ejecutable predeterminado de este juego.
_help_game_delete;Elimina este juego de la lista de ROMs.
_help_game_edit;Edita la información de este juego.
_help_game_overview;Edita la descripción general del juego.
_help_generator_build;Genera la lista de ROM con los emuladores seleccionados
_help_generator_opt;Establece si este emulador se incluirá en la lista de ROM generada.
_help_input_action;
_help_input_add;Agrega una nueva asignación de controles para esta acción
_help_input_default_action;Establece el comportamiento predeterminado para este control.
_help_input_delete;Remover esta asignación de controles
_help_layout_file;Algunas plantillas proporcionan varios archivos layout*.nut. Seleccione el archivo de plantilla que desea usar
_help_layout_name;Configurar diseño
_help_main_control;Configura las entradas de palanca, teclado y ratón que controlan Attract-Mode Plus
_help_main_display;Configura los grupos de lista de roms/temas ("Pantallas") que están disponibles para hacer circular enAttract-Mode Plus
_help_main_emu;Configura las opciones del emulador
_help_main_intro;Configura las opciones de introducción
_help_main_settings;Configura las opciones generales
_help_main_plugin;Configura las opciones del plugin
_help_main_scraper;Configura las opciones del scraper
_help_main_screensaver_timeout;Cantidad de tiempo en segundos a esperar antes de lanzar el protector de pantalla. 0 para deshabilitar
_help_main_screensaver;Configura ell protector de pantalla
_help_main_sound;Configura volumenes de sonidos, asignaciones de eventos de sonido y el tema (canción) de ambiente
_help_misc_anisotropic_filtering;Establece el nivel de filtrado anisotrópico para las texturas. Esto mejorará la calidad de las texturas escaladas.
_help_misc_antialiasing;Establecer el nivel de suavizado
_help_misc_check_for_updates;Configura si Attract-Mode Plus debe buscar actualizaciones disponibles al inicio y mostrar un cuadro de diálogo de notificación de actualización cuando se encuentre una nueva versión.
_help_misc_confirm_exit;Confirm before exiting Attract-Mode Plus?
_help_misc_confirm_favs;Confirma la adición/remoción a favoritos
_help_misc_custom_overlay;Permitir que las plantillas personalicen la superposición utilizada para los menús Mostrar, Filtrar, Etiquetar y Salir
_help_misc_exit_command;Comando seleccionado cuando Salir (con confirmación) es seleccionado [por ej. "sudo shutdown"]
_help_misc_exit_message;Mensaje alternativo para salir de la interfaz [ej. "Apagar sistema"].
_help_misc_filter_wrap_mode;Configura que pasa cuando el "Siguiente filtro" o "Filtro previo" alcanza el final del conjunto de filtros
_help_misc_group_clones;Agrupa todos los clones de un juego en una sola entrada de lista.
_help_misc_hide_brackets;Esconde Hide el texto en paréntesis cuando se muestran los títulos de los juegos
_help_misc_prefix_modes;Mueve "The" y "Vs." Prefijos al final del título del juego
_help_misc_hide_console;Ocultar la consola al inicio. Tenga en cuenta que esto solo funciona si inicia Attract-Mode Plus desde una interfaz gráfica de Windows. Si se inicia desde una ventana de consola existente (p. ej., un archivo por lotes), el proceso siempre se conectará a la consola existente y mostrará la salida en ella.
_help_misc_image_cache_mbytes;Configura el tamaño máximo de la caché de imágenes interna de Attract-Mode Plus (en megabytes)
_help_misc_language;Selecciona el idioma de la interfaz de usuario de Attract-Mode Plus.
_help_misc_layout_preview;Mostrar los cambios de configuración de la interfaz inmediatamente
_help_misc_multiple_monitors;Habilita el uso de múltiples monitores mediante Attract-Mode Plus. Configurar esto en "No" puede reducir el parpadeo de la pantalla al iniciar juegos.
_help_misc_power_saving;Ayuda a ahorrar energía al redibujar la pantalla solo cuando es necesario. Puede causar interrupciones en la animación en algunos diseños o congelamiento en Linux
_help_misc_quick_menu;Establece si los menús se pueden abrir y cerrar con el mismo botón. También permite cambiar entre menús sin tener que cerrarlos primero
_help_misc_screen_rotation;Establece la rotación base de la pantalla.
_help_misc_startup_mode;Establece qué debe suceder cuando Attract-Mode Plus se inicia por primera vez.
_help_misc_track_usage;Configura si Attract-Mode Plus debería registrar el uso (tiempo jugado y cuenta de partidas para cada juego)
_help_misc_ui_color;Selecciona el color que se usará en la interfaz de usuario de Attract-Mode Plus.
_help_misc_video_decoder;Configura el decodificador que se usará para la reproducción de vídeo (si hay varios decodificadores disponibles).
_help_misc_window_mode;configura si Attract-Mode Plus llena lapantalla o se ejecuta en una ventana
_help_plugin_command;Ejecutable asociado a este plugin
_help_plugin_enabled;Configura si este plugin está o no habilitado
_help_plugin_name;Configurar plugin
_help_plugin_sel;Configurar plugin
_help_rule_comp;Tipo de comparación para el filtro
_help_rule_delete;Borra esta regla de filtro
_help_rule_target;El atributo de información del juego en el cual quiere basar el fitro
_help_rule_value;Expresión regular para filtrar. Por ejemplo, si el objetivo del filtro es "Año" y la comparación es "igual",un valor de "1984" coincidirá con el año 1984, "198." coincidirá con cualquier año de los 80s, y "(198.)|(199.)" coincidirá con cualquier año de los 80s o 90s
_help_scraper_fanart;Set whether game fan art should be downloaded when scraping
_help_scraper_flyers;Establecer si se deben descargar los folletos y las carátulas de los juegos al extraer datos
_help_scraper_marquees;Establecer si se deben descargar las marquesinas y banners del juego al extraer datos
_help_scraper_snaps;Establece si se deben descargar instantáneas del juego al extraer datos.
_help_scraper_vids;Establece si se deben descargar los vídeos del juego al extraerlos.
_help_scraper_wheels;Establece si se deben descargar los logotipos de los juegos al extraer datos.
_help_shortcut_artwork_name;Opcionalmente, proporciona un nombre para la imagen que se asociará a este acceso directo. La interfaz intentará cargar las imágenes con este nombre al mostrar el acceso directo.
_help_shortcut_delete;Eliminar este acceso directo de la lista de ROMs
_help_shortcut_label;Edita la etiqueta de este acceso directo
_help_shortcut_target;Edita el destino de este acceso directo
_help_sound_loudness_normalisation;Activa un efecto de audio que aumenta automáticamente el volumen del contenido multimedia con bajo volumen a un nivel constante.
_help_sound_sel;Asigna un sonido a este evento/acción
_help_sound_volume;Ajusta el volumen de esta fuente de audio

# -- screensaver --

Basic Movie;Película básica
Movie Collage;Collage de película
Image Collage;Collage de imágenes
RGB Movie;Película RGB
Overlay Artwork;Superposición de imágenes
Play Sound;Reproducir sonido
Preserve Aspect Ratio;Conservar relación de aspecto
Blank Screen Time;Tiempo de pantalla en blanco
Blank Screen Start Command;Comando de inicio de pantalla en blanco
Blank Screen Stop Command;Comando de finalización de pantalla en blanco
Play intro;Reproducir introducción
Detect aspect ratio;Detectar relación de aspecto
Default video;Vídeo predeterminado
16:9 video;Vídeo 16:9
4:3 video;Vídeo 4:3
9:16 video;Vídeo 9:16
3:4 video;Vídeo 3:4

# -- extra --
