#@Español

# -- generic --
$1 Rule(s);$1 Regla(s)
#Blank Game;
#Custom;
#Default;
#Disabled;
Empty;Vacío
#False;
#Multi;
No Sort;No ordenar
#No;
None;Ninguno
#Off;
#On;
OR;O
#True;
Yes;Si

# -- misc --
Welcome to Attract-Mode Plus;Bienvenido a Attract-Mode Plus
Press TAB to Configure;Pulse TAB para configurar
#Displays Menu Options;
Action;Acción
Add Artwork;Agregar tema
Add Emulator;Agregar emulador
#Add Exception;
Add Filter;Agregar filtro
Add Input;Agregar control
Add New Display;Agregar nueva pantalla
Add Rule;Agregar regla
Allow Exit;Permitir salida
#Anisotropic Filtering;
#Anti-Aliasing;
Artwork Label;Nombre del tema
#Artwork Name;
Artwork Path;Ruta del tema
#Auto-detect Emulators;
#Check for Updates;
Collection/Rom List;Colección/Lista de roms
Comparison;Comparación
#Confirm Exit;
Confirm Favourites;Confirmar favoritos
Controls;Controles
#Create new tag;
#Custom Arguments;
#Custom Executable;
#Default Action;
Delete this Display;Borrar esta pantalla
Delete this Emulator;Suprimir este emulador
Delete this Filter;Borrar este filtro
#Delete this Game;
Delete this Rule;Borrar esta regla
#Delete this Shortcut;
Displays;Pantallas
Emulator Name;Nombre del emulador
Emulators;Emuladores
#Enable Multiple Monitors;
Enabled;activado
#Exception;
Exit Attract-Mode Plus;Salir de Attract-Mode Plus
Exit Attract-Mode Plus?;Salir de Attract-Mode Plus?
Exit Command;Comando de salida
#Exit Message;
Filter Name;Nombre del filtro
Filter Value;Valor del filtro
Filter Wrap Mode;Modo de ciclado de filtro
Filter;Filtro
#General;
Global Filter;Filtro global
#Group Clones;
Hide Brackets in Game Title;Esconder paréntesis en títutlos de juegos
#Hide Console;
#Image Cache Size;
#Insert Command Shortcut;
#Insert Display Shortcut;
#Insert Game Entry;
#Insert Menu Entry;
#Joystick $1;
#Joystick Mappings;
Joystick Threshold;Umbral de la palanca
Language;Idioma
#Layout File;
Layout Options;Opciones de temas
Layout Preview;Vista previa del diseño
Layout;Tema
List Limit;Límite de lista
Menu Colour;Color del menú
#Menu Prompt;
Menu Toggle;Alternar menú
Mouse Threshold;Umbral del ratón
#Overview;
Plug-ins;Plugins
#Power Saving;
Remove Input;Eliminar control
#Reverse Order;
Rule;Regla
#Scrape Artwork;
#Scrape Fanart;
#Scrape Flyers/Boxart;
#Scrape Game Logos (Wheel Art);
#Scrape Marquees;
#Scrape Snaps;
#Scrape Videos (MAME only);
#Scraper;
#Screen Rotation;
Screen Saver Timeout;Límite de tiempo para el salvapantalla
#Select template to use for emulator settings;
#Show in Cycle;
#Show in Menu;
Sort By;Ordenado por
Sound;Sonido
#Startup Mode;
Target;Objetivo
Title;Título
Track Usage;Usar seguimiento
#Video Decoder;
Window Mode;Modo ventana
Wrote $1 entries to Collection/Rom List;Se agregaron $1 entradas a la lista de roms

# -- indexStrings --
Name;Nombre
Title;Título
Emulator;Emulador
CloneOf;Clon de
Year;Año
Manufacturer;Fabricante
Category;Categoría
Players;Jugadores
Rotation;Rotación
Control;Controles
Status;Estado
DisplayCount;Contador de pantalla
DisplayType;Tipo de pantalla
AltRomname;Nombre de rom alternativo
AltTitle;Título alternativo
#Extra;
#Buttons;
#Series;
Language;Idioma
#Region;
#Rating;
Favourite;Favorito
Tags;Etiquetas
PlayedCount;Cuenta de partidas
PlayedTime;Tiempo jugado
#PlayedLast;
#FileIsAvailable;
#Shuffle;

# -- filterCompDisplayStrings --
contains;contiene
does not contain;no contiene
does not equal;no es igual a
equals;igual

# -- commandDispStrings --
Back;Volver
Up;Arriba
Down;Abajo
Left;Izquierda
Right;Derecha
Select;Seleccionar
#Previous Game;
#Next Game;
Previous Page;Página posterior
Next Page;Página anterior
Previous Display;Pantalla previa
Next Display;Pantalla siguiente
Displays Menu;Mostrar menú
Previous Filter;Filtro anterior
Next Filter;Filtro posterior
Filters Menu;Menú de filtros
Toggle Layout;Cambiar tema
Toggle Movie;Cambiar video
Toggle Mute;Silenciar
Toggle Rotate Right;Rotar a la derecha
Toggle Flip;Invertir
Toggle Rotate Left;Rotar a la izquierda
Exit;Salir (Confirmación)
Exit to Desktop;Salir a escritorio
Reload;Recargar
Screenshot;Captura de pantalla
Random Game;Juego aleatorio
Replay Last Game;Repetir el último juego
Add/Remove Favourite;Agregar/eliminar favoritos
Previous Favourite;Anterior favorito
Next Favourite;Siguiente favorito
Add/Remove Tags;Agregar/Remover etiquetas
Screen Saver;Potector de pantalla
Previous Letter;Letra previa
Next Letter;Letra siguiente
#Intro;
#Insert Game;
Layout Options;Opciones de temas
Custom1; Personalizado 1
Custom2; Personalizado 2
Custom3; Personalizado 3
Custom4; Personalizado 4
Custom5; Personalizado 5
Custom6; Personalizado 6
Custom7; Personalizado 7
Custom8; Personalizado 8
Custom9; Personalizado 9
Custom10; Personalizado 10
Ambient Soundtrack;Canción de sonido de ambiente
Startup Sound;Sonido de inicio
Game Return Sound;Sonido de retorno al juego

# --uiColorDispTokens --
#Indigo;
#Blue;
#Cyan;
#Turquoise;
#Green;
#Acid;
#Gold;
#Yellow;
#Orange;
#Brown;
#Rust;
#Red;
#Pink;
#Magenta;
#Purple;
#Grey;
#Neutral;
#White;

# --windowModeDispTokens --
Fill Screen;Llenar pantalla
Fullscreen Mode;Modo pantalla completa
Window;Ventana
#Window (No Border);

# --screenRotationDispTokens --
Flip;Invertir

# --startupDispTokens --
#Show Last Selection;
#Launch Last Game;
#Show Displays Menu;

# --filterWrapDispTokens --
Wrap within Display;Ciclar dentro de la pantalla
Jump to Next Display;Saltar a la siguiente pantalla
No Wrap;No ciclar

# -- antialiasingDispTokens --
#MSAA x2;
#MSAA x4;
#MSAA x8;

# -- FeSettings::anisotropicDispTokens --
#x2;
#x4;
#x8;
#x16;

# -- settingDispStrings --
Sound Volume;Volumen general
Ambient Volume;Volumen de ambiente
Movie Volume;Volumen de videos
#Loudness Normalisation;

# -- splash_message --
#Generating index ($1%);
Generating Rom List: $1%;Generación de lista de roms: $1%
#Please Wait;
#Scraping Artwork: $1%;

# -- confirm_dialog --
#Add '$1' to Favourites?;
#Attract-Mode Plus detected emulator(s) that can be imported automatically.  Import them now?;
#Auto-detect emulators?;
#Clear Hotkey?;
Delete display '$1'?;¿Desea borrar la pantalla '$1'?
Delete emulator '$1'?;¿Desea borrar el emulador '$1'?
Delete filter '$1'?;¿Desea borrar el filtro '$1'?
#Delete game '$1'?;
#Delete shortcut '$1'?;
Overwrite existing '$1' list?;¿Desea sobreescribir la lista de roms '$1'?
#Remove '$1' from Favourites?;
Rom path '$1' not found, proceed anyways?;Ruta de roms '$1' no encontrada, ¿desea continuar?
This will overwrite an existing mapping ($1).  Proceed?;Esto sobreescribirá un mapeo de controles existente ($1). ¿Desea continuar?

# --input_map_dialog --
#Press Hotkey;
Press Input;Presionar control

# -- edit_dialog --
Enter Display Name;Ingrese el nombre de la pantalla
Enter Emulator Name;Ingrese el nombre del emulador
Enter Filter Name;Ingrese el nombre para el filtro
#Enter new tag name;
#Enter Romlist Name;

# -- Titles --
#_submenu;
#Configure Layout;
Configure Plug-in;Configuración de Plugins
Configure;Configuración
Display Edit;Editar pantalla
Edit Artwork;Modificar tema
#Edit Control;
Edit Emulator;Modificar emulador
#Edit Game;
#Edit Shortcut;
#Exception Edit;
Filter Edit;Editar filtro
Generate Collection/Rom List;Generar lista de roms
Rule Edit;Editar reglas

# --indexDispStrings --
Executable;Ejecutable
Command Arguments;Argumentos
#Working Directory;
Rom Path(s);Ruta(s) de roms
Rom Extension(s);Extension(es) de roms
System Identifier;Identificador de sistema
Info Source/Scraper;Fuente de información/Scraper
Additional Import File(s);Archivos de importación adicionales
#Non-Blocking Mode Wait;
Exit Hotkey; Tecla rápida de salida
#Pause Hotkey;

# -- datetime --
#_datetime;
#A Moment Ago;
#Never;
#$1 Second;
#$1 Minute;
#$1 Hour;
#$1 Day;
#$1 Minute Ago;
#$1 Hour Ago;
#$1 Day Ago;
#$1 Week Ago;
#$1 Month Ago;
#$1 Year Ago;
#$1 Seconds;
#$1 Minutes;
#$1 Hours;
#$1 Days;
#$1 Minutes Ago;
#$1 Hours Ago;
#$1 Days Ago;
#$1 Weeks Ago;
#$1 Months Ago;
#$1 Years Ago;

# -- help --
_help_art_add;Agregar una nueva fuente de artwork (marquesinas, capturas de pantalla, etc.)
_help_art_label;Etiqueta que identifica este artwork (usado por los temas)
_help_art_path;Ruta a los archivos de este artwork. Es posible ingresar multiples rutas separadas por punto y coma.
_help_art;Una fuente de artwork disponible para ser usado por el temas
_help_back;Salir del menu
_help_control_add_favourite;Configura el(los) control(es) que marca/desmarca el juego actualmente seleccionado como favorito
_help_control_add_tags;Configura el(los) control(es) que agragan/remueven etiquetas del juego actualmente seleccionado
#_help_control_back;
_help_control_configure;Configura el(los) control(es) que muestra el "Menú de configuración"
_help_control_custom1;Configura el(los) control(es) "Personalizado1"
_help_control_custom10;Configura el(los) control(es) "Personalizado10"
_help_control_custom2;Configura el(los) control(es) "Personalizado2"
_help_control_custom3;Configura el(los) control(es) "Personalizado3"
_help_control_custom4;Configura el(los) control(es) "Personalizado4"
_help_control_custom5;Configura el(los) control(es) "Personalizado5"
_help_control_custom6;Configura el(los) control(es) "Personalizado6"
_help_control_custom7;Configura el(los) control(es) "Personalizado7"
_help_control_custom8;Configura el(los) control(es) "Personalizado8"
_help_control_custom9;Configura el(los) control(es) "Personalizado9"
_help_control_displays_menu;Configurar el(los) control(es) que "muestra el menú"
_help_control_down;Configurar el(los) control(es) que mueven hacia abajo la selección
#_help_control_edit_game;
_help_control_exit_to_desktop;Configura el(los) control(es) que sale del frontend inmediatamente al escritorio
_help_control_exit;Configura el(los) control(es) que cierran el frontend
_help_control_filters_menu;Configurar el(los) control(es) que muestran el "Menú de filtros"
#_help_control_insert_game;
#_help_control_intro;
#_help_control_joystick_map;
_help_control_joystick_threshold;Umbral para los movimientos de palanca registrados, de 1 a 100 (100=menos sensible)
#_help_control_layout_options;
#_help_control_left;
_help_control_mouse_threshold;Umbral para los movimientos del ratón, de 1 a 100 (100=menos sensible)
_help_control_next_display;Configurar el(los) control(es) que mueven hacia la pantalla siguiente
_help_control_next_favourite;Configura el(los) control(es) que mueven hacia el favorito siguiente
_help_control_next_filter;Configurar el(los) control(es) que mueven hacia el filtro siguiente
#_help_control_next_game;
_help_control_next_letter;Configura el(los) control(es) que mueve hacia la letra siguiente
_help_control_next_page;Configurar el(los) control(es) que mueven hacia abajo una página la selección
_help_control_prev_display;Configurar el(los) control(es) que mueven hacia la pantalla previa
_help_control_prev_favourite;Configura el(los) control(es) que mueven hacia el favorito previo
_help_control_prev_filter;Configurar el(los) control(es) que mueven hacia el filtro previo
#_help_control_prev_game;
_help_control_prev_letter;Configura el(los) control(es) que mueve hacia la letra previa
_help_control_prev_page;Configurar el(los) control(es) que mueven hacia arriba una página la selección
_help_control_random_game;Configura el(los) control(es) que selecciona un jego aleatorio de la lista actual
_help_control_reload;Configura el(los) control(es) que recargan el diseño actual
_help_control_replay_last_game;Configura el(los) control(es) que relanza el último juego jugado
#_help_control_right;
_help_control_screen_saver;Configura el(los) control(es) que lanzan el protector de pantalla
_help_control_screenshot;Configura el(los) control(es) que toma una captura de pantalla del frontend
_help_control_select;Configura los el(los) control(es) que lanzan la selción actual
_help_control_toggle_flip;Configura el(los) control(es) que cambia si la pantalla debe ser rotada o no 180 grados
_help_control_toggle_layout;Configura el(los) control(es) que cambia el script de tema a usar (Depende del tema que está usando si esto hace algo)
_help_control_toggle_movie;Configura el(los) control(es) que cambia si los videos son o no reproducidos
_help_control_toggle_mute;Configura el(los) control(es) que silencia o no el sonido del frontend
_help_control_toggle_rotate_left;Configura el(los) control(es) que cambia si la pantalla debe ser rotada o no 90 grados a la izquierda
_help_control_toggle_rotate_right;Configura el(los) control(es) que cambia si lapantalla debe ser rotada o no 90 grados a la derecha
_help_control_up;Configurar el(los) control(es) que mueven hacia arriba la selección
_help_display_add_filter;Agregar un filtro a este conjunto de filtros de pantalla
_help_display_add;Agragar una nueva pantalla
_help_display_delete;Borra esta pantalla
_help_display_filter;Configura este filtro desde el conjunto de filtros de pantalla
_help_display_global_filter;Configura reglas globales de filtros que son aplicados a cada entrada de la lista de roms de esta pantalla
#_help_display_in_cycle;
#_help_display_in_menu;
_help_display_layout_options;Configurar cualquier opción especifica de temas
_help_display_layout;Tema usado para esta pantalla
_help_display_name;Nombre de la pantalla
_help_display_romlist;Colección/lista de roms usada para esta pantalla
_help_display_sel;Configurar pantalla
_help_displaysmenu_exit;configura si la opción de Salir debe ser provista en el "menú de pantallas"
#_help_displaysmenu_layout;
#_help_displaysmenu_prompt;
#_help_displaysmenu;
_help_emu_add;Agrega un nuevo emulador
_help_emu_args;Argumento de linea de comandos usado por este emulador.  Los siguientes pueden ser propiamente sustituidos: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;Borra la entrada para este emulador
_help_emu_executable;Ruta completa y nombre del ejecutable del emulador. $HOME es reemplazado por con el directorio home del usuario
_help_emu_exit_hotkey;Configura una tecla global para salir del emulador. Attract-Mode Plus terminará el proceso del emulador si esta tecla es presionada
_help_emu_gen_romlist;Genera una lista de roms buscando en las rutas de roms configuradas con las extensiones configuradas, incorporando XML e importando información adicional a la lista generada (si está disponible)
_help_emu_import_extras;Ruta de cualquier archivo adicional que neceiste ser leido cuando se genera la lista de roms para este emulador.  Los archivos soportados son: catver.ini (para categorias de juegos) y nplayers.ini (para el número de jugadores). Es posible ingresar multiples rutas separadas por punto y coma.
_help_emu_info_source;Use "listxml" si el emulador prove la salida de mame -listxml, "listsoftware" para la salida de mame/mess -listsoftware, "thegamesdb.net" para extraer información desde thegamesdb.net, o "steam" para leer desde una instalación de steam.  "listsoftware" y "thegamesdb.net" también requieren que sea configurado un identificador de sistema reconocible por esas fuentes
#_help_emu_name;
_help_emu_nb_mode_wait;Configura un tiempo mínimo de ejecución (en segundos).  Attract-Mode Plus esperará después de ejecutar este emulador hasta que haya transcurrido el tiempo mínimo de ejecución y pasará a ejecución de fondo. Esto necesita ser configurado por Steam para funcionar correctamente en Windows. Configure esto en 0 a menos que sepa que lo necesita
#_help_emu_pause_hotkey;
_help_emu_romext;Extensión(es) para este emulador (por ej. .zip). Es posible ingresar multiples extensiones separadas por punto y coma. Especificar "<DIR>" como entrada si los juegos se encuientran en subdirectorios separados
_help_emu_rompath;Ruta a las roms para este emulador.  Es posible ingresar multiples rutas separadas por punto y coma.
_help_emu_scrape_artwork;Scrape missing artwork images for this emulator from TheGamesDB.net and mamedb.com
#_help_emu_sel_auto_detect;
#_help_emu_sel_gen_romlist;
_help_emu_sel;Configura el emulador
_help_emu_system;Identificador(es) de sistema para este emulador. Es posible ingresar multiples valores separadas por punto y coma.
#_help_emu_workdir;
#_help_filter_add_exception;
_help_filter_add_rule;Agrega una regla para este filtro
_help_filter_delete;Borrar este filtro
#_help_filter_exception;
_help_filter_list_limit;Configurar esto a cero si desea limitar el tamaño de una lista ordenada. Use un valor positivo para las X primeras entradas (por ej. "10" entrega las primeras 10 entradas), un valor negativo para las últimas X entradas (por ej. "-25" entrega las últimas 25 entradas), o "0" para ilimitado
_help_filter_name;Name ára este filtro
#_help_filter_reverse_order;
_help_filter_rule;Configura regla para el filtro
_help_filter_sort_by;Atriburo del juego a partir del cual desea que la colección/lista de roms sea ordenada. Configure a "No ordenar" para mantener el orden de la colección/lista de romo
#_help_game_custom_args;
#_help_game_custom_executable;
#_help_game_delete;
#_help_game_edit;
#_help_game_overview;
#_help_generator_build;
#_help_generator_opt;
_help_input_action;
_help_input_add;Agrega una nueva asignación de controles para esta acción
#_help_input_default_action;
_help_input_delete;Remover esta asignación de controles
#_help_layout_file;
#_help_layout_name;
_help_main_control;Configura las entradas de palanca, teclado y ratón que controlan Attract-Mode Plus
_help_main_display;Configura los grupos de lista de roms/temas ("Pantallas") que están disponibles para hacer circular enAttract-Mode Plus
_help_main_emu;Configurar configuraciones del emulador
#_help_main_intro;
_help_main_misc;Configuraciones varias
_help_main_plugin;Configura los plugins disponibles
#_help_main_scraper;
_help_main_screensaver_timeout;Cantidad de tiempo en segundos a esperar antes de lanzar el protector de pantalla. 0 para deshabilitar
_help_main_screensaver;Configura ell protector de pantalla
_help_main_sound;Configura volumenes de sonidos, asignaciones de eventos de sonido y el tema (canción) de ambiente
#_help_misc_anisotropic_filtering;
#_help_misc_antialiasing;
#_help_misc_check_for_updates;
_help_misc_confirm_exit;Confirm before exiting Attract-Mode Plus?
_help_misc_confirm_favs;Confirma la adición/remoción a favoritos
_help_misc_exit_command;Comando seleccionado cuando Salir (con confirmación) es seleccionado [por ej. "sudo shutdown"]
#_help_misc_exit_message;
_help_misc_filter_wrap_mode;Configura que pasa cuando el "Siguiente filtro" o "Filtro previo" alcanza el final del conjunto de filtros
#_help_misc_group_clones;
_help_misc_hide_brackets;Esconde Hide el texto en paréntesis cuando se muestran los títulos de los juegos
#_help_misc_hide_console;
#_help_misc_image_cache_mbytes;
#_help_misc_language;
#_help_misc_layout_preview;
#_help_misc_multiple_monitors;
#_help_misc_power_saving;
_help_misc_quick_menu;Establece si los menús se pueden abrir y cerrar con el mismo botón. También permite cambiar entre menús sin tener que cerrarlos primero
#_help_misc_screen_rotation;
#_help_misc_startup_mode;
_help_misc_track_usage;Configura si Attract-Mode Plus debería registrar el uso (tiempo jugado y cuenta de partidas para cada juego)
#_help_misc_ui_color;
#_help_misc_video_decoder;
_help_misc_window_mode;configura si Attract-Mode Plus llena lapantalla o se ejecuta en una ventana
_help_plugin_command;Ejecutable asociado a este plugin
_help_plugin_enabled;Configura si este plugin está o no habilitado
#_help_plugin_name;
_help_plugin_sel;Configurar plugin
_help_rule_comp;Tipo de comparación para el filtro
_help_rule_delete;Borra esta regla de filtro
_help_rule_target;El atributo de información del juego en el cual quiere basar el fitro
_help_rule_value;Expresión regular para filtrar. Por ejemplo, si el objetivo del filtro es "Año" y la comparación es "igual",un valor de "1984" coincidirá con el año 1984, "198." coincidirá con cualquier año de los 80s, y "(198.)|(199.)" coincidirá con cualquier año de los 80s o 90s
_help_scraper_fanart;Set whether game fan art should be downloaded when scraping
#_help_scraper_flyers;
#_help_scraper_marquees;
#_help_scraper_snaps;
#_help_scraper_vids;
#_help_scraper_wheels;
#_help_shortcut_artwork_name;
#_help_shortcut_delete;
#_help_shortcut_label;
#_help_shortcut_target;
#_help_sound_loudness_normalisation;
_help_sound_sel;Asigna un sonido a este evento/acción
_help_sound_volume;Las configuraciones válidas se volumen van de 0 (silencio) a 100

# -- extra --
XML Mode;Modo XML
Overlay Artwork;superposición de artworks
Play Sound;Reproducir sonido
Ambient Sounds;Sondio ambiente
Command;Comandos
Image collage;Collage de imágenes
All;Todos
Basic Movie;Video básico
Movie collage;Collage de video
Minimum Run Time;Tiempo mínimo de ejecución
Preserve Aspect Ratio;Preservar relación de aspecto
