#@Français

# -- generic --
#$1 Rule(s);
#Blank Game;
#Custom;
#Default;
Disabled;Désactivé
#Empty;
#False;
#Multi;
No Sort;Non classé
No;Non
None;Non
#Off;
#On;
OR;OU
#True;
Yes;Oui

# -- misc --
 Attract-Mode Plus;Bienvenue sur Attract-Mode Plus
Press TAB to Configure;Appuyez sur TAB pour configurer
#Displays Menu Options;
#Action;
Add Artwork;Ajouter Artwork
Add Emulator;Ajouter un émulateur
#Add Exception;
Add Filter;Ajouter un filtre
Add Input;Ajouter un contrôle
Add New Display;Ajouter une nouvelle liste
Add Rule;Ajouter une règle
Allow Exit;Autoriser la sortie
#Anisotropic Filtering;
#Anti-Aliasing;
Artwork Label;Label de l'Artwork
#Artwork Name;
Artwork Path;Chemin de l'Artwork
#Auto-detect Emulators;
#Check for Updates;
Collection/Rom List;Liste de ROM
Comparison;Comparaison
#Confirm Exit;
Confirm Favourites;Confirmer les favoris
Controls;Contrôles
#Create new tag;
#Custom Arguments;
#Custom Executable;
#Default Action;
Delete this Display;Supprimer cette liste
Delete this Emulator;Supprimer cet émulateur
Delete this Filter;Supprimer ce filtre
#Delete this Game;
Delete this Rule;Supprimer cette règle
#Delete this Shortcut;
Displays;Listes d'affichage
Emulator Name;Nom de l'émulateur
Emulators;Emulateurs
#Enable Multiple Monitors;
Enabled;Activé
#Exception;
Exit Attract-Mode Plus;Quitter Attract-Mode Plus
Exit Attract-Mode Plus?;Quitter Attract-Mode Plus?
Exit Command;Commande de sortie
#Exit Message;
Filter Name;Nom du filtre
Filter Value;Filtre de valeur
Filter Wrap Mode;Mode de fin de liste de filtres
Filter;Filtre
General;Général
Global Filter;Filtre global
#Group Clones;
Hide Brackets in Game Title;Cacher les crochets dans le titre du jeu
#Hide Console;
#Image Cache Size;
#Insert Command Shortcut;
#Insert Display Shortcut;
#Insert Game Entry;
#Insert Menu Entry;
#Joystick $1;
#Joystick Mappings;
Joystick Threshold;Seuil du joystick
Language;Langue
#Layout File;
Layout Options;Options du Layout
Layout Preview;Aperçu de la mise en page
Layout;Thème
List Limit;taille maximum de la liste
Menu Colour;Couleur des menus
#Menu Prompt;
Menu Toggle;Basculement de menu
Mouse Threshold;Seuil de la souris
#Overview;
Plug-ins;Plug-in
#Power Saving;
Remove Input;Enlever le contrôle
#Reverse Order;
Rule;Règle
Scrape Artwork;Aspirer les Artworks
Scrape Fanart;Aspire les 'Fanart'
Scrape Flyers/Boxart;Aspire les Flyers/Couvertures
Scrape Game Logos (Wheel Art);Aspire les logos des jeux (Wheel Art)
Scrape Marquees;Aspire les Marquees
Scrape Snaps;Aspire les images des jeux
#Scrape Videos (MAME only);
Scraper;Aspiration
#Screen Rotation;
Screen Saver Timeout;Décompte économiseur d'écran
#Select template to use for emulator settings;
#Show in Cycle;
#Show in Menu;
Sort By;Classé par
Sound;Son
#Startup Mode;
Target;Cible
Title;Titre
Track Usage;Mode de comptage
#Video Decoder;
Window Mode;Mode d'affichage
Wrote $1 entries to Collection/Rom List;Création de $1 entrées dans la liste de ROM

# -- indexStrings --
Name;Nom
Title;Titre
Emulator;Emulateur
CloneOf;Clone de
Year;Année
Manufacturer;Fabriquant
Category;Catégorie
Players;Joueurs
#Rotation;
Control;Contrôle
Status;Etat
DisplayCount;Afficher compteur
DisplayType;Afficher type
AltRomname;Nom de rom alternatif
AltTitle;Titre alternatif
#Extra;
#Buttons;
#Series;
Language;Langue
#Region;
#Rating;
Favourite;Favoris
Tags;Mots clés
PlayedCount;Compteur de jeu
PlayedTime;Temps de jeu
#PlayedLast;
#FileIsAvailable;
#Shuffle;

# -- filterCompDisplayStrings --
contains;contient
does not contain;ne contient pas
does not equal;n'est pas égal à
equals;est égal à

# -- commandDispStrings --
Back;Retour
Up;Haut
Down;Bas
Left;Gauche
Right;Droite
Select;Sélection
#Previous Game;
#Next Game;
Previous Page;Page Suivante
Next Page;Page Précédente
Previous Display;Liste précédente
Next Display;Liste suivante
Displays Menu;Liste des Listes d'affichage
Previous Filter;Filtre précédent
Next Filter;Filtre suivant
Filters Menu;Menu des filtres
Toggle Layout;Basculer le thème
Toggle Movie;Basculer la vidéo
Toggle Mute;Basculer en mode silence
Toggle Rotate Right;Basculer Rotation droite
Toggle Flip;Basculer mode retourné
Toggle Rotate Left;Basculer Rotation gauche
Exit;Sortie (Confirmer)
Exit to Desktop;Sortie vers le bureau
Reload;Recharger
Screenshot;Photo écran
Random Game;Jeu au hasard
Replay Last Game;Rejouer au dernier jeu
Add/Remove Favourite;Ajouter/Supprimer Favoris
Previous Favourite;Favoris précédent
Next Favourite;Favoris suivant
Add/Remove Tags;Ajouter/Supprimer des mots clés
Screen Saver;Economiseur d'écran
Previous Letter;Lettre précédente
Next Letter;Lettre suivante
#Intro;
#Insert Game;
Layout Options;Options du Layout
#Custom1;
#Custom2;
#Custom3;
#Custom4;
#Custom5;
#Custom6;
#Custom7;
#Custom8;
#Custom9;
#Custom10;
Ambient Soundtrack;Musique d'ambiance
Startup Sound;Son au démarrage
Game Return Sound;Son au retour du jeu

# --uiColorDispTokens --
#Indigo;
#Blue;
#Cyan;
#Turquoise;
#Green;
#Acid;
#Gold;
#Yellow;
#Orange;
#Brown;
#Rust;
#Red;
#Pink;
#Magenta;
#Purple;
#Grey;
#Neutral;
#White;

# --windowModeDispTokens --
Fill Screen;Rempli l'écran
Fullscreen Mode;Mode plein écran
Window;Fenêtre
#Window (No Border);

# --screenRotationDispTokens --
Flip;Retourné

# --startupDispTokens --
#Show Last Selection;
#Launch Last Game;
#Show Displays Menu;

# --filterWrapDispTokens --
Wrap within Display;Revient au début de la liste de filtres
Jump to Next Display;Bascule sur la liste de roms suivante
No Wrap;Ne fait rien

# -- antialiasingDispTokens --
#MSAA x2;
#MSAA x4;
#MSAA x8;

# -- FeSettings::anisotropicDispTokens --
#x2;
#x4;
#x8;
#x16;

# -- settingDispStrings --
Sound Volume;Volume général
Ambient Volume;Volume des sons d'ambiances
Movie Volume;Volume des vidéos
#Loudness Normalisation;

# -- splash_message --
Generating Rom List;Génération de la liste de ROM
#Please Wait;
Scraping Artwork;Aspire l'Artwork

# -- confirm_dialog --
#Add '$1' to Favourites?;
#Attract-Mode Plus detected emulator(s) that can be imported automatically.  Import them now?;
#Auto-detect emulators?;
#Clear Hotkey?;
Delete display '$1'?;Supprimer la liste '$1'?
Delete emulator '$1'?;Supprimer l'émulateur '$1'?
Delete filter '$1'?;Supprimer le filtre '$1'?
#Delete game '$1'?;
#Delete shortcut '$1'?;
Overwrite existing '$1' list?;Ecraser la liste de ROM '$1' existante?
#Remove '$1' from Favourites?;
Rom path '$1' not found, proceed anyways?;Chemin des ROM '$1' introuvable, continuer?
This will overwrite an existing mapping ($1).  Proceed?;Ecraser le contrôle existant ($1). Confirmer?

# --input_map_dialog --
#Press Hotkey;
Press Input;Appuyer sur le contrôle

# -- edit_dialog --
Enter Display Name;Entrer le nom de la liste
Enter Emulator Name;Nom de l'émulateur?
Enter Filter Name;Entrer le nom du filtre
#Enter new tag name;
#Enter Romlist Name;

# -- Titles --
#_submenu;
#Configure Layout;
Configure Plug-in;Configurer Plug-in
Configure;Configuration
Display Edit;Edition de la liste
Edit Artwork;Modifier l'Artwork
#Edit Control;
Edit Emulator;Modifier l'émulateur
#Edit Game;
#Edit Shortcut;
#Exception Edit;
Filter Edit;Edition du filtre
Generate Collection/Rom List;Générer la liste de roms
Rule Edit;Editer les règles

# --indexDispStrings --
Executable;Exécutable
Command Arguments;Ligne de commande
#Working Directory;
Rom Path(s);Chemin des ROM
Rom Extension(s);Extension(s) des ROM
System Identifier;Identifiant du système
Info Source/Scraper;Info Source/Aspiration
Additional Import File(s);Fichiers additionnels
#Non-Blocking Mode Wait;
Exit Hotkey;Raccourci clavier pour sortir
#Pause Hotkey;

# -- datetime --
#_datetime;
#A Moment Ago;
#Never;
#$1 Second;
#$1 Minute;
#$1 Hour;
#$1 Day;
#$1 Minute Ago;
#$1 Hour Ago;
#$1 Day Ago;
#$1 Week Ago;
#$1 Month Ago;
#$1 Year Ago;
#$1 Seconds;
#$1 Minutes;
#$1 Hours;
#$1 Days;
#$1 Minutes Ago;
#$1 Hours Ago;
#$1 Days Ago;
#$1 Weeks Ago;
#$1 Months Ago;
#$1 Years Ago;

# -- help --
_help_art_add;Ajouter une nouvelle ressource à l'Artwork (marquee, capture d'écran, etc.)
_help_art_label;Label identifiant cette ressource d'Artwork (utilisé par les thèmes)
_help_art_path;Répertoire contenant les Artworks
#_help_art;
#_help_back;
_help_control_add_favourite;Définit le(s) contrôle(s) qui permet(ent) d'ajouter/supprimer le jeu selectionné à la liste des favoris
_help_control_add_tags;Définit le(s) contrôle(s) qui ajoute(nt)/supprime(nt) des mots clés au jeu sélectionné
#_help_control_back;
_help_control_configure;Définit le(s) contrôle(s) qui affiche(nt) le menu de configuration
_help_control_custom1;Définit le(s) contrôle(s) utilisateur(s) "Custom1"
_help_control_custom10;Définit le(s) contrôle(s) utilisateur(s) "Custom10"
_help_control_custom2;Définit le(s) contrôle(s) utilisateur(s) "Custom2"
_help_control_custom3;Définit le(s) contrôle(s) utilisateur(s) "Custom3"
_help_control_custom4;Définit le(s) contrôle(s) utilisateur(s) "Custom4"
_help_control_custom5;Définit le(s) contrôle(s) utilisateur(s) "Custom5"
_help_control_custom6;Définit le(s) contrôle(s) utilisateur(s) "Custom6"
_help_control_custom7;Définit le(s) contrôle(s) utilisateur(s) "Custom7"
_help_control_custom8;Définit le(s) contrôle(s) utilisateur(s) "Custom8"
_help_control_custom9;Définit le(s) contrôle(s) utilisateur(s) "Custom9"
_help_control_displays_menu;Définit le(s) contrôle(s) qui affiche(nt) la liste des listes
_help_control_down;Définit le(s) contrôle(s) qui décrémente(nt) la séléction d'une valeur
#_help_control_edit_game;
_help_control_exit_to_desktop;Définit le(s) contrôle(s) qui quitte(nt) immédiatement Attract-Mode Plus pour revenir au bureau
_help_control_exit;Définit le(s) contrôle(s) qui quitte(nt) Attract-Mode Plus
_help_control_filters_menu;Définit le(s) contrôle(s) qui affiche(nt) la liste des filtres
#_help_control_insert_game;
#_help_control_intro;
#_help_control_joystick_map;
_help_control_joystick_threshold;Seuil d'amplitude des mouvements du joystick, de 1 à 100 (100=moins sensible)
#_help_control_layout_options;
#_help_control_left;
_help_control_mouse_threshold;Seuil d'amplitude des mouvements de la souris, de 1 à 100 (100=moins sensible)
_help_control_next_display;Définit le(s) contrôle(s) qui bascule(nt) à la liste suivante
_help_control_next_favourite;Définit le(s) contrôle(s) qui selectionne(nt) le jeu favoris suivant
_help_control_next_filter;Définit le(s) contrôle(s) qui bascule(nt) au filtre suivant
#_help_control_next_game;
_help_control_next_letter;Définit le(s) contrôle(s) qui bascule(nt) à la lettre suivante
_help_control_next_page;Définit le(s) contrôle(s) qui décrémente(nt) la séléction d'une page
_help_control_prev_display;Définit le(s) contrôle(s) qui bascule(nt) à la liste précédente
_help_control_prev_favourite;Définit le(s) contrôle(s) qui selectionne(nt) le jeu favoris precedent
_help_control_prev_filter;Définit le(s) contrôle(s) qui bascule(nt) au filtre précédente
#_help_control_prev_game;
_help_control_prev_letter;Définit le(s) contrôle(s) qui bascule(nt) à la lettre précédente
#_help_control_prev_page;
_help_control_random_game;Définit le(s) contrôle(s) qui sélectionne(nt) un jeu aléatoirement dans la liste de rom active
_help_control_reload;Définit le(s) contrôle(s) qui rechargent la mise en page actuelle
_help_control_replay_last_game;Définit le(s) contrôle(s) qui relance(nt) le dernier jeu joué
#_help_control_right;
_help_control_screen_saver;Définit le(s) contrôle(s) qui lance(nt) le mode "économiseur d'écran"
_help_control_screenshot;Définit le(s) contrôle(s) qui enregistre(nt) une impression écran d'Attract-Mode Plus
_help_control_select;Définit le(s) contrôle(s) qui valide(nt) la valeur sélectionnée
_help_control_toggle_flip;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la rotation de l'écran de 180 degrés
_help_control_toggle_layout;Définit le(s) contrôle(s) qui  active(nt)/désactive(nt) le script du theme utilisé (Ceci dépend du theme que vous utilisez)
_help_control_toggle_movie;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la lecture des vidéos.
_help_control_toggle_mute;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) le son.
_help_control_toggle_rotate_left;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la rotation de l'écran de 90 degrés sur la gauche
_help_control_toggle_rotate_right;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la rotation de l'écran de 90 degrés sur la droite
_help_control_up;Définit le(s) contrôle(s) qui incrémente(nt) la séléction d'une valeur
_help_display_add_filter;Ajouter un filtre à cette liste d'affichage
_help_display_add;Ajouter une nouvelle liste d'affichage
_help_display_delete;Suppression de la liste d'affichage
_help_display_filter;Configurer le filtre
_help_display_global_filter;Définit les règles du filtre global. Elles s'appliqueront à l'ensemble des valeurs de la liste de roms affichée.
#_help_display_in_cycle;
#_help_display_in_menu;
_help_display_layout_options;Configurer une option spécifique du Layout
_help_display_layout;Thème à utiliser pour cette liste d'affichage
_help_display_name;Titre de cette liste d'affichage
_help_display_romlist;Liste de ROM à utiliser pour cette liste d'affichage
_help_display_sel;Configurer la liste d'affichage
_help_displaysmenu_exit;Indiquer si une option de sortie doit être prévue dans le menu des listes
#_help_displaysmenu_layout;
#_help_displaysmenu_prompt;
#_help_displaysmenu;
_help_emu_add;Ajouter un nouvel émulateur
_help_emu_args;Arguments de la ligne de commande de cet émulateur. Options de substitution: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;Supprime l'entrée pour cet émulateur
_help_emu_executable;Chemin et nom de l'exécutable de l'émulateur. $HOME sera remplacé par le répertoire de l'utilisateur
_help_emu_exit_hotkey;Définit un raccourci clavier pour sortir de l'émulateur. Attract-Mode Plus arrêtera le process de l'émulateur lorsque ce raccourci clavier sera pressé.
_help_emu_gen_romlist;Génére une liste de ROM en cherchant dans le chemin des ROM avec l'extension choisie, incorporant l'XML et les fichiers additionnels d'information dans la liste générée (si disponible)
_help_emu_import_extras;Fichiers additionels nécessitant d'être lus lors de la génération de la liste de ROM pour cet émulateur. Fichiers supportés: catver.ini (catégories) et nplayers.ini (nombre de joueur). Plusieurs fichiers peuvent être saisis si séparés par un point-virgule
_help_emu_info_source;Saisir "listxml" si cet émulateur propose un fichier de type mame -listxml, "listsoftware" pour les fichiers du type mame/mess -listsoftware, "thegamesdb.net" pour extraire les informations du site thegamesdb.net, ou "steam" pour les lires depuis une installation de steam. Les sources "listsoftware" et "thegamesdb.net" nécessitent que des identifiants systèmes spécifiques soient configurés pour fonctionner correctement
#_help_emu_name;
_help_emu_nb_mode_wait;Définit un temps minimum de fonctionnement (en secondes). Attract-Mode Plus va attendre, après avoir lancé l'émulateur, que ce temps minimum se soit écoulé avant de re-basculer au premier plan. Ceci est nécessaire pour que Steam fonctionne correctement sous Windows. Saisir 0 si vous n'en avez pas besoin
#_help_emu_pause_hotkey;
_help_emu_romext;Extension des ROM pour cet émulateur (ex .zip).  Possibilité d'utiliser des extensions multiples séparées par un point-virgule
_help_emu_rompath;Chemin des ROM pour cet émulateur
_help_emu_scrape_artwork;Aspirer les artworks manquants pour cet émulateur sur TheGamesDB.net et mamedb.com
#_help_emu_sel_auto_detect;
#_help_emu_sel_gen_romlist;
_help_emu_sel;Configuration de l'émulateur
_help_emu_system;Identifiant(s) système(s) pour cet émulateur. Plusieurs valeurs peuvent être saisies, séparées par un point virgule
#_help_emu_workdir;
#_help_filter_add_exception;
_help_filter_add_rule;Ajouter une règle à ce filtre
_help_filter_delete;Supprimer ce filtre
#_help_filter_exception;
_help_filter_list_limit;Saisir un nombre différent de zéro pour limiter la taille de la liste triée. Un nombre positif remonte les X premières valeurs (ex : "10" donne les 10 premières valeurs), un nombre négatif remonte les X dernières valeurs (ex : "-25" donne les 25 dernières valeurs). "0" affiche toute la liste.
_help_filter_name;Nom du filtre
#_help_filter_reverse_order;
_help_filter_rule;Configurer le filtre
_help_filter_sort_by;C'est l'information du jeu par lequel vous souhaitez classer votre liste. Sélectionner "Non classé" pour conserver l'ordre de la liste de rom source.
#_help_game_custom_args;
#_help_game_custom_executable;
#_help_game_delete;
#_help_game_edit;
#_help_game_overview;
#_help_generator_build;
#_help_generator_opt;
_help_input_action;
_help_input_add;Ajouter un nouveau contrôle
#_help_input_default_action;
_help_input_delete;Enlever ce contrôle
#_help_layout_file;
#_help_layout_name;
_help_main_control;Configurer les contrôles
_help_main_display;Configurer les listes d'affichage
_help_main_emu;Configurer les émulateurs
_help_main_intro;Configurer l'intro
_help_main_misc;Configurations diverses
_help_main_plugin;Configurer les plug-ins
_help_main_scraper;Configurer les parametres d'aspiration des artworks
_help_main_screensaver_timeout;Temps total en seconde à attendre pour activer l'économiseur d'écran.  0 pour désactiver
_help_main_screensaver;Configurer l'économiseur d'écran
_help_main_sound;Configurer le volume et les affectations sonores
#_help_misc_anisotropic_filtering;
#_help_misc_antialiasing;
#_help_misc_check_for_updates;
_help_misc_confirm_exit;Confirm before exiting Attract-Mode Plus?
_help_misc_confirm_favs;Confirmer l'addition/suppression des favoris
_help_misc_exit_command;Commande à exécuter en quittant (Confirmer) [exemple "sudo shutdown"]
#_help_misc_exit_message;
_help_misc_filter_wrap_mode;Définit l'action a mener lorsque "Filtre suivant" ou "Filtre précédent" arrivent à une  extrémité de la liste de filtre.
#_help_misc_group_clones;
_help_misc_hide_brackets;Cacher le texte entre crochets lors de l'affichage du titre du jeu
#_help_misc_hide_console;
#_help_misc_image_cache_mbytes;
_help_misc_language;Sélectionner la langue
#_help_misc_layout_preview;
#_help_misc_multiple_monitors;
#_help_misc_power_saving;
_help_misc_quick_menu;Permet d'ouvrir et de fermer les menus avec le même bouton. Permet également de passer d'un menu à l'autre sans avoir à les fermer au préalable
#_help_misc_screen_rotation;
#_help_misc_startup_mode;
_help_misc_track_usage;Active les compteurs d'Attract-Mode Plus (Compteur de jeu et Temps de jeu)
#_help_misc_ui_color;
#_help_misc_video_decoder;
_help_misc_window_mode;Définit si Attract-Mode Plus rempli l'écran, fonctionne en mode plein écran ou si il s'exécute dans une fenêtre.
_help_plugin_command;Exécutable associé à ce plug-in
_help_plugin_enabled;Indiquer si ce plug-in est activé
#_help_plugin_name;
_help_plugin_sel;Configurer le plug-in
_help_rule_comp;Règle de comparaison pour le filtre
_help_rule_delete;Supprimer cette règle de filtrage
_help_rule_target;L'attribut du jeu que vous souhaitez filtrer sur la base de
_help_rule_value;Valeur à filtrer.  Par exemple, si la cible de filtrage est "Année" et le comparateur "est égale à", une valeur de "1984" correspondra à l'année 1984, "198." correspondra à n'importe quelle année des années 1980, et "(198.)|(199.)" correspondra aux années comprises entre 1980 et 1999
_help_scraper_fanart;Définir où les 'fan art' des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scraper_flyers;Définir où les 'flyers' et les couvertures des boîtes des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scraper_marquees;Définir où les 'marquees' et les bannières des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scraper_snaps;Définir où les 'snapshots' des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scraper_vids;Définir où les videos des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scraper_wheels;Définir où les logos des jeux doivent être téléchargés lorsqu'ils sont aspirés
#_help_shortcut_artwork_name;
#_help_shortcut_delete;
#_help_shortcut_label;
#_help_shortcut_target;
#_help_sound_loudness_normalisation;
_help_sound_sel;Assigner un son à cet événement/action
_help_sound_volume;Les valeurs possibles pour le volume vont de 0 (silence) à 100

# -- extra --
XML Mode;Mode XML
Ambient Sounds;Son d'ambiance
Command;Commandes
Next List;Liste suivante
All;Tous
Minimum Run Time;Temps minimum fonctionnement
