#@Français

# -- generic --
$1 Rule(s);$1 règle
Blank Game;Jeu vierge
Custom;Personnalisé
Default;Par défaut
Disabled;Désactivé
Empty;Vide
False;Faux
Multi;Multiple
No Sort;Non classé
No;Non
None;Non
Off;Désactivé
On;Activé
OR;OU
True;Vrai
Yes;Oui
Import;Importer
Cancel;Annuler

# -- misc --
Press TAB to Configure;Appuyez sur TAB pour configurer
Displays Menu Options;Afficher les options du menu
Action;Action
Add Artwork;Ajouter Artwork
Add Emulator;Ajouter un émulateur
Add Exception;Ajouter une exception
Add Filter;Ajouter un filtre
Add Input;Ajouter un contrôle
Add Display;Ajouter un affichage
Add Rule;Ajouter une règle
Allow Exit;Autoriser la sortie
Anisotropic Filtering;Filtrage anisotrope
Anti-Aliasing (MSAA);Anticrénelage (MSAA)
Artwork Label;Label de l'Artwork
Artwork Name;Nom de l'illustration
Artwork Path;Chemin de l'Artwork
Auto-detect Emulators;Détection automatique des émulateurs
Check for Updates;Rechercher des mises à jour
Collection/Romlist;Liste de ROM
Comparison;Comparaison
Confirm Exit;Confirmer la sortie
Confirm Favourites;Confirmer les favoris
Controls;Contrôles
Add Tag;Ajouter une étiquette
Custom Arguments;Arguments personnalisés
Custom Executable;Exécutable personnalisé
Custom Overlay;Superposition personnalisée
Default Action;Action par défaut
Delete this Display;Supprimer cette liste
Delete this Emulator;Supprimer cet émulateur
Delete this Filter;Supprimer ce filtre
Delete this Game;Supprimer ce jeu
Delete this Rule;Supprimer cette règle
Delete this Shortcut;Supprimer ce raccourci
Displays;Listes d'affichage
Emulator Name;Nom de l'émulateur
Emulators;Emulateurs
Multiple Monitors;Plusieurs Moniteurs
Enabled;Activé
Exception;Exception
Exit Attract-Mode Plus;Quitter Attract-Mode Plus
Exit Attract-Mode Plus?;Quitter Attract-Mode Plus?
Exit Command;Commande de sortie
Exit Message;Message de sortie
Filter Name;Nom du filtre
Filter Value;Filtre de valeur
Filter Wrap Mode;Mode de fin de liste de filtres
Filter;Filtre
Settings;Paramètres
Global Filter;Filtre global
Group Clones;Grouper les clones
Hide Game Title Brackets;Masquer les parenthèses du titre du jeu
Format Game Title;Format du titre du jeu
Hide Console;Masquer la console
Image Cache Size;Taille du cache d'images
Insert Command Shortcut;Insérer un raccourci de commande
Insert Display Shortcut;Insérer un raccourci d'affichage
Insert Game Entry;Insérer une entrée de jeu
Insert Menu Entry;Insérer une entrée de menu
Joystick $1;Manette $1
Joystick Mappings;Configuration du joystick
Joystick Threshold;Seuil du joystick
Language;Langue
Layout File;Fichier de configuration
Layout Preview;Aperçu de la mise en page
Layout;Thème
List Limit;taille maximum de la liste
Menu Colour;Couleur des menus
Menu Prompt;Invite de menu
Menu Toggle;Basculement de menu
Mouse Threshold;Seuil de la souris
Overview;Aperçu
Plugins;Plugins
Power Saving;Économie d'énergie
Remove Input;Enlever le contrôle
Reverse Order;Ordre inverse
Rule;Règle
Scrape Artwork;Aspirer les Artworks
Scrape Fanart;Aspire les 'Fanart'
Scrape Flyers/Boxart;Aspire les Flyers/Couvertures
Scrape Game Logos (Wheel Art);Aspire les logos des jeux (Wheel Art)
Scrape Marquees;Aspire les Marquees
Scrape Snaps;Aspire les images des jeux
Scrape Videos (MAME only);Récupérer des vidéos (MAME uniquement)
Scraper;Grattoir
Screen Rotation;Rotation de l'écran
Screen Saver Timeout;Décompte économiseur d'écran
Selection Delay;Délai de sélection
Show in Cycle;Afficher en boucle
Show in Menu;Afficher dans le menu
Sort By;Classé par
Sort Only;Trier uniquement
Sort and Show;Trier et afficher
Sound;Son
Startup Mode;Mode de démarrage
Target;Cible
Title;Titre
Game Stats;Statistiques du jeu
Video Decoder;Décodeur vidéo
Window Mode;Mode d'affichage
Added $1 Collection/Romlist entries;Ajout d'entrées à la collection/liste des ROMs $1

# -- indexStrings --
Name;Nom
Title;Titre
Emulator;Émulateur
CloneOf;Clone de
Year;Année
Manufacturer;Fabriquant
Category;Catégorie
Players;Joueurs
Rotation;Rotation
Control;Contrôle
Status;État
DisplayCount;Afficher compteur
DisplayType;Afficher type
AltRomname;Nom de rom alternatif
AltTitle;Titre alternatif
Extra;Supplémentaire
Buttons;Boutons
Series;Série
Language;Langue
Region;Région
Rating;Classification
Favourite;Favoris
Tags;Mots clés
PlayedCount;Compteur de jeu
PlayedTime;Temps de jeu
PlayedLast;Dernier jeu joué
FileIsAvailable;Fichier disponible
Shuffle;Mélanger

# -- filterCompDisplayStrings --
contains;contient
does not contain;ne contient pas
does not equal;n'est pas égal à
equals;est égal à
greater than;supérieur à
less than;inférieur à
greater than or equal;supérieur ou égal
less than or equal;inférieur ou égal

# -- commandDispStrings --
Back;Retour
Up;Haut
Down;Bas
Left;Gauche
Right;Droite
Select;Sélection
Previous Game;Jeu précédent
Next Game;Jeu suivant
Previous Page;Page Suivante
Next Page;Page Précédente
Previous Display;Liste précédente
Next Display;Liste suivante
Displays Menu;Liste des Listes d'affichage
Previous Filter;Filtre précédent
Next Filter;Filtre suivant
Filters Menu;Menu des filtres
Toggle Layout;Basculer le thème
Toggle Movie;Basculer la vidéo
Toggle Mute;Basculer en mode silence
Toggle Rotate Right;Basculer Rotation droite
Toggle Flip;Basculer mode retourné
Toggle Rotate Left;Basculer Rotation gauche
Exit;Sortie (Confirmer)
Exit to Desktop;Sortie vers le bureau
Reload Layout;Recharger la mise en page
Reload Config;Recharger la configuration
Reset Window;Réinitialiser la fenêtre
Screenshot;Photo écran
Random Game;Jeu au hasard
Replay Last Game;Rejouer au dernier jeu
Toggle Fullscreen;Activer/désactiver le plein écran
Add/Remove Favourite;Ajouter/Supprimer Favoris
Previous Favourite;Favoris précédent
Next Favourite;Favoris suivant
Add/Remove Tags;Ajouter/Supprimer des mots clés
Screen Saver;Economiseur d'écran
Previous Letter;Lettre précédente
Next Letter;Lettre suivante
Intro;Introduction
Insert Game;Insérer un jeu
Layout Options;Options du Layout
Plugin Options;Options du plugin
Custom1;Personnalisé 1
Custom2;Personnalisé 2
Custom3;Personnalisé 3
Custom4;Personnalisé 4
Custom5;Personnalisé 5
Custom6;Personnalisé 6
Custom7;Personnalisé 7
Custom8;Personnalisé 8
Custom9;Personnalisé 9
Custom10;Personnalisé 10
Ambient Soundtrack;Musique d'ambiance
Startup Sound;Son au démarrage
Game Return Sound;Son au retour du jeu

# --uiColorDispTokens --
Indigo;Indigo
Blue;Bleu
Cyan;Cyan
Turquoise;Turquoise
Green;Vert
Acid;Acide
Gold;Or
Yellow;Jaune
Orange;Orange
Brown;Marron
Rust;Rouille
Red;Rouge
Pink;Rose
Magenta;Magenta
Purple;Violet
Grey;Gris
Neutral;Neutre
White;Blanc

# --windowModeDispTokens --
Fill Screen;Rempli l'écran
Fullscreen;Plein écran
Window;Fenêtre
Borderless Window;Fenêtre sans bordure

# --screenRotationDispTokens --
Flip;Retourné

# --startupDispTokens --
Show Last Selection;Afficher la dernière sélection
Show Random Selection;Afficher la sélection aléatoire
Launch Last Game;Lancer le dernier jeu
Show Displays Menu;Afficher le menu des écrans

# --filterWrapDispTokens --
Wrap within Display;Revient au début de la liste de filtres
Jump to Next Display;Bascule sur la liste de roms suivante
No Wrap;Ne fait rien

# -- settingDispStrings --
Sound Volume;Volume général
Ambient Volume;Volume des sons d'ambiances
Movie Volume;Volume des vidéos
Loudness Normalisation;Normalisation du volume sonore

# -- splash_message --
Generating Romlist;Génération de la liste de ROM
Please Wait;Veuillez patienter
Scraping Artwork;Aspire l'Artwork

# -- confirm_dialog --
Add '$1' to Favourites?;Ajouter «$1» aux favoris?
Auto-detect emulators?;Détection automatique des émulateurs?
Found 1 emulator;1 émulateur trouvé
Found $1 emulators;$1 émulateurs trouvés
No emulators found;Aucun émulateur trouvé
+$1 more;+$1 de plus
Clear Hotkey?;Effacer le raccourci clavier?
Delete display '$1'?;Supprimer la liste «$1»?
Delete emulator '$1'?;Supprimer l'émulateur «$1»?
Delete filter '$1'?;Supprimer le filtre «$1»?
Delete game '$1'?;Supprimer le jeu «$1»?
Delete shortcut '$1'?;Supprimer le raccourci «$1»?
Overwrite existing '$1' list?;Ecraser la liste de ROM «$1» existante?
Remove '$1' from Favourites?;Supprimer «$1» des favoris?
Rom path '$1' not found, proceed?;Chemin ROM «$1» introuvable, continuer?
Overwrite existing '$1' mapping?;Écraser le mappage «$1» existant?
A display with this name already exists;Un affichage avec ce nom existe déjà
Configuration files have been migrated\n to the 'config' folder.\nDelete old files?;Les fichiers de configuration ont été migrés\n dans le dossier 'config'.\nSupprimer les anciens fichiers?

# --input_map_dialog --
Press Hotkey;Appuyer sur la touche de raccourci
Press Input;Appuyer sur le contrôle

# -- edit_dialog --
Enter Display Name;Entrer le nom de la liste
Enter Emulator Name;Nom de l'émulateur?
Enter Filter Name;Entrer le nom du filtre
Enter Tag Name;Saisir un nouveau nom d'étiquette
Enter Romlist Name;Saisir le nom de la ROM

# -- Titles --
Configure;Configuration
Default Display Options;Options d'affichage par défaut
Display Options;Options d'affichage
Artwork Options;Options graphiques
Control Options;Options de contrôle
Emulator Options;Options de l'émulateur
Game Options;Options du jeu
Shortcut Options;Options des raccourcis
Exception Options;Options des exceptions
Filter Options;Options de filtrage
Rule Options;Options des règles
Generate Collection/Romlist;Générer la liste de roms

# --indexDispStrings --
Executable;Exécutable
Command Arguments;Ligne de commande
Working Directory;Répertoire de travail
Rom Path(s);Chemin des ROM
Rom Extension(s);Extension(s) des ROM
System Identifier;Identifiant du système
Info Source/Scraper;Info Source/Aspiration
Additional Import File(s);Fichiers additionnels
Non-Blocking Mode Wait;Attente en mode non bloquant
Exit Hotkey;Raccourci clavier pour sortir
Pause Hotkey;Touche de raccourci Pause

# -- datetime --
_datetime;%Y-%m-%d %H:%M:%S
A Moment Ago;Il y a un instant
Never;Jaune
$1 Second;$1 seconde
$1 Minute;$1 minute
$1 Hour;$1 heure
$1 Day;$1 jour
$1 Minute Ago;Il y a $1 minute
$1 Hour Ago;Il y a $1 heure
$1 Day Ago;Il y a $1 jour
$1 Week Ago;Il y a $1 semaine
$1 Month Ago;Il y a $1 mois
$1 Year Ago;Il y a $1 an
$1 Seconds;$1 seconde
$1 Minutes;$1 minute
$1 Hours;Il y a $1 heure
$1 Days;$1 jour
$1 Minutes Ago;Il y a $1 minute
$1 Hours Ago;Il y a $1 heure
$1 Days Ago;Il y a $1 jour
$1 Weeks Ago;Il y a $1 semaine
$1 Months Ago;Il y a $1 mois
$1 Years Ago;Il y a $1 an

# -- help --
_help_art_add;Ajouter une nouvelle ressource à l'Artwork (marquee, capture d'écran, etc.)
_help_art_label;Label identifiant cette ressource d'Artwork (utilisé par les thèmes)
_help_art_path;Répertoire contenant les Artworks
_help_art;Ressource graphique disponible pour les dispositions.
_help_back;Quitter le menu
_help_control_add_favourite;Définit le(s) contrôle(s) qui permet(ent) d'ajouter/supprimer le jeu selectionné à la liste des favoris
_help_control_add_tags;Définit le(s) contrôle(s) qui ajoute(nt)/supprime(nt) des mots clés au jeu sélectionné
_help_control_back;Définir la ou les commandes permettant de revenir en arrière.
_help_control_configure;Définit le(s) contrôle(s) qui affiche(nt) le menu de configuration
_help_control_custom1;Définit le(s) contrôle(s) utilisateur(s) "Custom1"
_help_control_custom10;Définit le(s) contrôle(s) utilisateur(s) "Custom10"
_help_control_custom2;Définit le(s) contrôle(s) utilisateur(s) "Custom2"
_help_control_custom3;Définit le(s) contrôle(s) utilisateur(s) "Custom3"
_help_control_custom4;Définit le(s) contrôle(s) utilisateur(s) "Custom4"
_help_control_custom5;Définit le(s) contrôle(s) utilisateur(s) "Custom5"
_help_control_custom6;Définit le(s) contrôle(s) utilisateur(s) "Custom6"
_help_control_custom7;Définit le(s) contrôle(s) utilisateur(s) "Custom7"
_help_control_custom8;Définit le(s) contrôle(s) utilisateur(s) "Custom8"
_help_control_custom9;Définit le(s) contrôle(s) utilisateur(s) "Custom9"
_help_control_displays_menu;Définit le(s) contrôle(s) qui affiche(nt) la liste des listes
_help_control_down;Définit le(s) contrôle(s) qui décrémente(nt) la séléction d'une valeur
_help_control_edit_game;Définir la ou les commandes permettant de modifier la sélection actuelle
_help_control_exit_to_desktop;Définit le(s) contrôle(s) qui quitte(nt) immédiatement Attract-Mode Plus pour revenir au bureau
_help_control_exit;Définit le(s) contrôle(s) qui quitte(nt) Attract-Mode Plus
_help_control_filters_menu;Définit le(s) contrôle(s) qui affiche(nt) la liste des filtres
_help_control_insert_game;Définir la ou les commandes permettant d'insérer un nouveau jeu
_help_control_intro;Configurer les commandes permettant d'afficher la vidéo d'introduction.
_help_control_joystick_map;Associer les emplacements de joystick de l'interface à des périphériques de jeu spécifiques connectés à votre ordinateur (par exemple, pour forcer l'utilisation de «Manette Microsoft Xbox 360» comme Joystick 0)
_help_control_joystick_threshold;Seuil d'amplitude des mouvements du joystick, de 1 à 100 (100=moins sensible)
_help_control_layout_options;Définissez les commandes qui affichent le menu «Options de mise en page»
_help_control_plugin_options;Définissez les commandes qui affichent le menu «Options du plugin» pour le dernier plugin consulté
_help_control_left;Définir la ou les commandes permettant de déplacer la sélection vers la gauche.
_help_control_mouse_threshold;Seuil d'amplitude des mouvements de la souris, de 1 à 100 (100=moins sensible)
_help_control_next_display;Définit le(s) contrôle(s) qui bascule(nt) à la liste suivante
_help_control_next_favourite;Définit le(s) contrôle(s) qui selectionne(nt) le jeu favoris suivant
_help_control_next_filter;Définit le(s) contrôle(s) qui bascule(nt) au filtre suivant
_help_control_next_game;Définir la ou les commandes permettant de passer au jeu suivant
_help_control_next_letter;Définit le(s) contrôle(s) qui bascule(nt) à la lettre suivante
_help_control_next_page;Définit le(s) contrôle(s) qui décrémente(nt) la séléction d'une page
_help_control_prev_display;Définit le(s) contrôle(s) qui bascule(nt) à la liste précédente
_help_control_prev_favourite;Définit le(s) contrôle(s) qui selectionne(nt) le jeu favoris precedent
_help_control_prev_filter;Définit le(s) contrôle(s) qui bascule(nt) au filtre précédente
_help_control_prev_game;Configurer les commandes permettant de revenir au jeu précédent.
_help_control_prev_letter;Définit le(s) contrôle(s) qui bascule(nt) à la lettre précédente
_help_control_prev_page;Définir la ou les commandes permettant de faire défiler la sélection vers le bas
_help_control_random_game;Définit le(s) contrôle(s) qui sélectionne(nt) un jeu aléatoirement dans la liste de rom active
_help_control_reload_layout;Définir la ou les commandes permettant de recharger la disposition actuelle.
_help_control_reload_config;Définir la ou les commandes permettant de recharger les fichiers de configuration
_help_control_reset_window;Définir la ou les commandes permettant de réinitialiser la taille et la position de la fenêtre.
_help_control_replay_last_game;Définit le(s) contrôle(s) qui relance(nt) le dernier jeu joué
_help_control_right;Définir la ou les commandes permettant de déplacer la sélection vers la droite
_help_control_screen_saver;Définit le(s) contrôle(s) qui lance(nt) le mode "économiseur d'écran"
_help_control_screenshot;Définit le(s) contrôle(s) qui enregistre(nt) une impression écran d'Attract-Mode Plus
_help_control_select;Définit le(s) contrôle(s) qui valide(nt) la valeur sélectionnée
_help_control_selection_delay;Définir le délai en millisecondes avant le début de la répétition des touches (par défaut: 400).
_help_control_toggle_flip;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la rotation de l'écran de 180 degrés
_help_control_toggle_fullscreen;Basculer entre le mode Plein écran et le mode Fenêtré
_help_control_toggle_layout;Définit le(s) contrôle(s) qui  active(nt)/désactive(nt) le script du theme utilisé (Ceci dépend du theme que vous utilisez)
_help_control_toggle_movie;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la lecture des vidéos.
_help_control_toggle_mute;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) le son.
_help_control_toggle_rotate_left;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la rotation de l'écran de 90 degrés sur la gauche
_help_control_toggle_rotate_right;Définit le(s) contrôle(s) qui active(nt)/désactive(nt) la rotation de l'écran de 90 degrés sur la droite
_help_control_up;Définit le(s) contrôle(s) qui incrémente(nt) la séléction d'une valeur
_help_display_add_filter;Ajouter un filtre à cette liste d'affichage
_help_display_add;Ajouter une nouvelle liste d'affichage
_help_display_delete;Suppression de la liste d'affichage
_help_display_filter;Configurer le filtre
_help_display_global_filter;Définit les règles du filtre global. Elles s'appliqueront à l'ensemble des valeurs de la liste de roms affichée.
_help_display_in_cycle;Inclure cet affichage dans le cycle «Affichage précédent»/«Affichage suivant»
_help_display_in_menu;Inclure cet affichage dans le menu «Affichage»
_help_display_layout_options;Configurer une option spécifique du Layout
_help_display_layout;Thème à utiliser pour cette liste d'affichage
_help_display_name;Titre de cette liste d'affichage
_help_display_romlist;Liste de ROM à utiliser pour cette liste d'affichage
_help_display_sel;Configurer la liste d'affichage
_help_display_edit_default;Configurer les options par défaut pour les nouveaux affichages
_help_displaysmenu_exit;Indiquer si une option de sortie doit être prévue dans le menu des listes
_help_displaysmenu_layout;Disposition du menu Affichage. Définir sur «Par défaut» pour utiliser le menu intégré de l'interface
_help_displaysmenu_prompt;Invite du menu Affichage (ex.: «Sélectionner le système»)
_help_displaysmenu;Configure les options du menu Affichage.
_help_emu_add;Ajouter un nouvel émulateur
_help_emu_args;Arguments de la ligne de commande de cet émulateur. Options de substitution: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;Supprime l'entrée pour cet émulateur
_help_emu_executable;Chemin et nom de l'exécutable de l'émulateur. $HOME sera remplacé par le répertoire de l'utilisateur
_help_emu_exit_hotkey;Définit un raccourci clavier pour sortir de l'émulateur. Attract-Mode Plus arrêtera le process de l'émulateur lorsque ce raccourci clavier sera pressé.
_help_emu_gen_romlist;Génére une liste de ROM en cherchant dans le chemin des ROM avec l'extension choisie, incorporant l'XML et les fichiers additionnels d'information dans la liste générée (si disponible)
_help_emu_import_extras;Fichiers additionels nécessitant d'être lus lors de la génération de la liste de ROM pour cet émulateur. Fichiers supportés: catver.ini (catégories) et nplayers.ini (nombre de joueur). Plusieurs fichiers peuvent être saisis si séparés par un point-virgule
_help_emu_info_source;Saisir "listxml" si cet émulateur propose un fichier de type mame -listxml, "listsoftware" pour les fichiers du type mame/mess -listsoftware, "thegamesdb.net" pour extraire les informations du site thegamesdb.net, ou "steam" pour les lires depuis une installation de steam. Les sources "listsoftware" et "thegamesdb.net" nécessitent que des identifiants systèmes spécifiques soient configurés pour fonctionner correctement
_help_emu_name;Modifier l'émulateur
_help_emu_nb_mode_wait;Définit un temps minimum de fonctionnement (en secondes). Attract-Mode Plus va attendre, après avoir lancé l'émulateur, que ce temps minimum se soit écoulé avant de re-basculer au premier plan. Ceci est nécessaire pour que Steam fonctionne correctement sous Windows. Saisir 0 si vous n'en avez pas besoin
_help_emu_pause_hotkey;Définir un raccourci clavier global pour mettre l'émulateur en pause. Lorsque vous appuyez sur ce bouton, Attract-Mode Plus met en pause l'émulateur et retourne à l'interface. Vous pouvez reprendre l'émulateur en sélectionnant à nouveau le même jeu dans l'interface.
_help_emu_romext;Extension des ROM pour cet émulateur (ex .zip).  Possibilité d'utiliser des extensions multiples séparées par un point-virgule
_help_emu_rompath;Chemin des ROM pour cet émulateur
_help_emu_scrape_artwork;Aspirer les artworks manquants pour cet émulateur sur TheGamesDB.net et mamedb.com
_help_emu_sel_auto_detect;Cette commande analyse le dossier parent à la recherche d'émulateurs connus et génère une configuration par défaut pour chaque émulateur trouvé.
_help_emu_sel_gen_romlist;Générer une collection/romlist contenant des jeux pour plusieurs émulateurs
_help_emu_sel;Configuration de l'émulateur
_help_emu_system;Identifiant(s) système(s) pour cet émulateur. Plusieurs valeurs peuvent être saisies, séparées par un point virgule
_help_emu_workdir;Répertoire de travail de cet émulateur. C'est le répertoire depuis lequel l'interface exécute l'émulateur. De plus, tous les chemins relatifs de ROM, d'illustrations ou de fichiers d'importation supplémentaires sont considérés comme relatifs à ce répertoire.
_help_filter_add_exception;Ajouter une exception à ce filtre. Si un jeu correspond à une exception (et n'a pas été filtré par une règle précédente), il sera ajouté au filtre.
_help_filter_add_rule;Ajouter une règle à ce filtre
_help_filter_delete;Supprimer ce filtre
_help_filter_exception;Configurer cette exception de filtre. Si un jeu correspond à une exception, il sera ajouté au filtre. Les règles et exceptions sont appliquées dans l'ordre de leur apparition.
_help_filter_list_limit;Saisir un nombre différent de zéro pour limiter la taille de la liste triée. Un nombre positif remonte les X premières valeurs (ex : "10" donne les 10 premières valeurs), un nombre négatif remonte les X dernières valeurs (ex : "-25" donne les 25 dernières valeurs). "0" affiche toute la liste.
_help_filter_name;Nom du filtre
_help_filter_reverse_order;Inverser l'ordre de tri de la collection/liste de ROM L'ordre par défaut est «A à Z» pour les informations, «Du plus grand au plus petit» pour les statistiques, ou l'ordre de la liste source pour «Aucun tri».
_help_filter_rule;Configurer le filtre
_help_filter_sort_by;C'est l'information du jeu par lequel vous souhaitez classer votre liste. Sélectionner "Non classé" pour conserver l'ordre de la liste de rom source.
_help_game_custom_args;Définir cette option pour remplacer les arguments de ligne de commande par défaut de ce jeu. Laisser vide si vous souhaitez les remplacer sans paramètres. Les éléments suivants sont remplacés correctement: [nom], [romext], [chemin_rom], [émulateur], [nom_fichier_rom], [système], [n_système]
_help_game_custom_executable;Définit cette option pour remplacer l'exécutable par défaut de ce jeu.
_help_game_delete;Supprimer ce jeu de la liste des ROMs
_help_game_edit;Modifier les informations de ce jeu.
_help_game_overview;Modifie la présentation du jeu.
_help_generator_build;Générer la liste des ROM avec le ou les émulateurs sélectionnés
_help_generator_opt;Indiquez si cet émulateur doit être inclus dans la liste des ROM générée.
_help_input_action;
_help_input_add;Ajouter un nouveau contrôle
_help_input_default_action;Définir le comportement par défaut de cette commande
_help_input_delete;Enlever ce contrôle
_help_layout_file;Certaines configurations proposent plusieurs fichiers de configuration *.nut. Sélectionnez le fichier de configuration à utiliser.
_help_layout_name;Configurer la disposition
_help_main_control;Configurer les contrôles
_help_main_display;Configurer les listes d'affichage
_help_main_emu;Configurer les options de l'émulateur
_help_main_intro;Configurer les options d'introduction
_help_main_settings;Configurer les options générales
_help_main_plugin;Configurer les options des plugins
_help_main_scraper;Configurer les options du scraper
_help_main_screensaver_timeout;Temps total en seconde à attendre pour activer l'économiseur d'écran.  0 pour désactiver
_help_main_screensaver;Configurer l'économiseur d'écran
_help_main_sound;Configurer le volume et les affectations sonores
_help_misc_anisotropic_filtering;Définir le niveau de filtrage anisotrope des textures. Cela améliorera la qualité des textures mises à l'échelle.
_help_misc_antialiasing;Définir le niveau d'anticrénelage
_help_misc_check_for_updates;Configurer si Attract-Mode Plus doit rechercher les mises à jour disponibles au démarrage et afficher une notification de mise à jour lorsqu'une nouvelle version est disponible.
_help_misc_confirm_exit;Confirm before exiting Attract-Mode Plus?
_help_misc_confirm_favs;Confirmer l'addition/suppression des favoris
_help_misc_custom_overlay;Autoriser les configurations à personnaliser l'interface utilisée pour les menus Affichage, Filtre, Étiquette et Quitter.
_help_misc_exit_command;Commande à exécuter en quittant (Confirmer) [exemple "sudo shutdown"]
_help_misc_exit_message;Message alternatif pour quitter l'interface [ex.: «Arrêter le système»].
_help_misc_filter_wrap_mode;Définit l'action a mener lorsque "Filtre suivant" ou "Filtre précédent" arrivent à une  extrémité de la liste de filtre.
_help_misc_group_clones;Regrouper tous les clones d'un jeu sous une seule entrée de liste.
_help_misc_hide_brackets;Cacher le texte entre crochets lors de l'affichage du titre du jeu
_help_misc_prefix_modes;Déplacer «The» et «Vs». Préfixe à la fin du titre du jeu
_help_misc_hide_console;Masquer la console au démarrage. Notez que cela fonctionne uniquement si Attract-Mode Plus est lancé depuis une interface graphique Windows. Si le processus est lancé depuis une fenêtre de console existante (par exemple, un fichier batch), il s'y connectera et y affichera sa sortie.
_help_misc_image_cache_mbytes;Configurer la taille maximale du cache d'images interne d'Attract-Mode Plus (en mégaoctets)
_help_misc_language;Sélectionner la langue
_help_misc_layout_preview;Afficher immédiatement les modifications de configuration de la disposition.
_help_misc_multiple_monitors;Activer l'utilisation de plusieurs écrans avec Attract-Mode Plus. Désactiver cette option peut réduire le scintillement de l'écran lors du lancement de jeux.
_help_misc_power_saving;Permet d'économiser de l'énergie en ne redessinant l'écran que lorsque cela est nécessaire. Peut entraîner des saccades d'animation sur certaines dispositions, ou un blocage sous Linux.
_help_misc_quick_menu;Permet d'ouvrir et de fermer les menus avec le même bouton. Permet également de passer d'un menu à l'autre sans avoir à les fermer au préalable
_help_misc_screen_rotation;Définir la rotation de base de l'écran
_help_misc_startup_mode;Définir l'action à effectuer au premier démarrage d'Attract-Mode Plus
_help_misc_track_usage;Active les compteurs d'Attract-Mode Plus (Compteur de jeu et Temps de jeu)
_help_misc_ui_color;Sélectionnez la couleur de l'interface utilisateur d'Attract-Mode Plus.
_help_misc_video_decoder;Configure le décodeur à utiliser pour la lecture vidéo (si plusieurs décodeurs sont disponibles).
_help_misc_window_mode;Définit si Attract-Mode Plus rempli l'écran, fonctionne en mode plein écran ou si il s'exécute dans une fenêtre.
_help_plugin_command;Exécutable associé à ce plugin
_help_plugin_enabled;Indiquer si ce plugin est activé
_help_plugin_name;Configurer le plugin
_help_plugin_sel;Configurer le plugin
_help_rule_comp;Règle de comparaison pour le filtre
_help_rule_delete;Supprimer cette règle de filtrage
_help_rule_target;L'attribut du jeu que vous souhaitez filtrer sur la base de
_help_rule_value;Valeur à filtrer.  Par exemple, si la cible de filtrage est "Année" et le comparateur "est égale à", une valeur de "1984" correspondra à l'année 1984, "198." correspondra à n'importe quelle année des années 1980, et "(198.)|(199.)" correspondra aux années comprises entre 1980 et 1999
_help_scraper_fanart;Définir où les 'fan art' des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scraper_flyers;Définir où les 'flyers' et les couvertures des boîtes des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scraper_marquees;Définir où les 'marquees' et les bannières des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scraper_snaps;Définir où les 'snapshots' des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scraper_vids;Définir où les videos des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_scraper_wheels;Définir où les logos des jeux doivent être téléchargés lorsqu'ils sont aspirés
_help_shortcut_artwork_name;Ajouter éventuellement un nom d'illustration à associer à ce raccourci. L'interface tentera de charger des illustrations portant ce nom lors de l'affichage du raccourci.
_help_shortcut_delete;Supprimer ce raccourci de la liste des ROM.
_help_shortcut_label;Modifier le libellé de ce raccourci
_help_shortcut_target;Modifier la cible de ce raccourci
_help_sound_loudness_normalisation;Activez un effet audio qui augmente automatiquement le volume des contenus multimédias à faible volume.
_help_sound_sel;Assigner un son à cet événement/action
_help_sound_volume;Régler le volume de cette source audio

# -- screensaver --

Basic Movie;Film simple
Movie Collage;Collage vidéo
Image Collage;Collage d'images
RGB Movie;Film RVB
Overlay Artwork;Superposition d'images
Play Sound;Lecture audio
Preserve Aspect Ratio;Conservation du format d'image
Blank Screen Time;Temps d'écran noir
Blank Screen Start Command;Commande de démarrage d'écran noir
Blank Screen Stop Command;Commande d'arrêt d'écran noir
Play intro;Lancer l'intro
Detect aspect ratio;Détecter le format d'image
Default video;Vidéo par défaut
16:9 video;Vidéo 16:9
4:3 video;Vidéo 4:3
9:16 video;Vidéo 9:16
3:4 video;Vidéo 3:4

# -- extra --
