#@Italiano

# -- generic --
$1 Rule(s);$1 regole
Blank Game;Partita vuota
Custom;Personalizzato
Default;Predefinito
Disabled;Disabilitato
Empty;Vuoto
False;Falso
Multi;Multi
No Sort;Nessun ordinamento
No;No
None;Nessuno
Off;Disattivato
On;Attivato
OR;o
True;Vero
Yes;Si
Import;Importare
Cancel;Cancellare

# -- misc --
Press TAB to Configure;Premi TAB per configurare
Displays Menu Options;Opzioni del Menù dei display
Action;Azione
Add Artwork;Aggiungi risorsa immagini
Add Emulator;Aggiungi emulatore
Add Exception;Aggiungi eccezione
Add Filter;Aggiungi filtro
Add Input;Aggiungi controllo
Add Display;Aggiungi visualizzazione
Add Rule;Aggiungi regola
Allow Exit;Consenti uscita
Anisotropic Filtering;Filtro anisotropico
Anti-Aliasing (MSAA);Anti-aliasing (MSAA)
Artwork Label;Nome della risorsa
Artwork Name;Nome immagine
Artwork Path;Percorso della risorsa
Auto-detect Emulators;Rilevamento automatico emulatori
Check for Updates;Controlla aggiornamenti
Collection/Romlist;Lista di ROM
Comparison;Comparazione
Confirm Exit;Conferma l'uscita
Confirm Favourites;Conferma aggiunta preferito
Controls;Controlli
Add Tag;Aggiungi tag
Custom Arguments;Argomenti personalizzati
Custom Executable;Eseguibile personalizzato
Custom Overlay;Sovrapposizione personalizzata
Default Action;Azione predefinita
Delete this Display;Cancella questo display
Delete this Emulator;Cancella questo emulatore
Delete this Filter;Cancella questo filtro
Delete this Game;Cancella il gioco
Delete this Rule;Cancella questa regola
Delete this Shortcut;Elimina questo collegamento
Displays;Display
Emulator Name;Nome dell'emulatore
Emulators;Emulatori
Multiple Monitors;Monitor Multipli
Enabled;Attivo
Exception;Eccezione
Exit Attract-Mode Plus;Esci da Attract-Mode Plus
Exit Attract-Mode Plus?;Uscire da Attract-Mode Plus?
Exit Command;Comando per uscire
Exit Message;Messaggio di uscita
Filter Name;Nome del filtro
Filter Value;Valore da comparare
Filter Wrap Mode;Metodo di scorrimento dei filtri
Filter;Filtro
Settings;Impostazioni
Global Filter;Filtro globale
Group Clones;Cloni di gruppo
Hide Game Title Brackets;Nascondi le parentesi del titolo del gioco
Format Game Title;Formato titolo gioco
Hide Console;Nascondi console
Image Cache Size;Dimensione cache immagini
Insert Command Shortcut;Inserisci scorciatoia di comando
Insert Display Shortcut;Inserisci scorciatoia di visualizzazione
Insert Game Entry;Inserisci voce di gioco
Insert Menu Entry;Inserisci voce di menu
Joystick $1;Joystick $1
Joystick Mappings;Mappature joystick
Joystick Threshold;Soglia del joystick
Language;Lingua
Layout File;File di layout
Layout Preview;Anteprima del layout
Layout;Tema
List Limit;Límite della lista
Menu Colour;Colore del menù
Menu Prompt;Titolo del menù
Menu Toggle;Menu Alterna
Mouse Threshold;Soglia del mouse
Overview;Panoramica
Plugins;Plugin
Power Saving;Risparmio energetico
Remove Input;Eliminare il controllo
Reverse Order;Ordine inverso
Rule;Regola
Scrape Artwork;Recupera le immagini
Scrape Fanart;Recupera le fanart
Scrape Flyers/Boxart;Recupera i flyer/boxart
Scrape Game Logos (Wheel Art);Recupera i logo
Scrape Marquees;Recupera i marquee
Scrape Snaps;Recupera le snap
Scrape Videos (MAME only);Scarica video (solo per MAME)
Scraper;Scratcher
Screen Rotation;Rotazione schermo
Screen Saver Timeout;Timeout salvaschermo
Selection Speed;Velocità di selezione
Selection Delay;Ritardo selezione
Selection Max Step;Passo massimo di selezione
Show in Cycle;Mostra nel ciclo
Show in Menu;Mostra nel menù
Sort By;Ordinato per
Sort Only;Ordina solo
Sort and Show;Ordina e mostra
Sound;Suoni
Startup Mode;Modalità di avvio
Target;Obbiettivo
Title;Titolo
Game Stats;Statistiche di gioco
Video Decoder;Decoder video
Window Mode;Modalità finestra
Added $1 Collection/Romlist entries;Aggiunte voci $1 Collection/Romlist

# -- indexStrings --
Name;Nome
Title;Titolo
Emulator;Emulatore
CloneOf;Clone di
Year;Anno
Manufacturer;Produttore
Category;Categoría
Players;Giocatori
Rotation;Rotazione
Control;Controllo
Status;Stato
DisplayCount;Contatore di display
DisplayType;Tipo di display
AltRomname;Nome alternativo della ROM
AltTitle;Titolo alternativo
Extra;Extra
Buttons;Pulsanti
Series;Serie
Language;Lingua
Region;Regione
Rating;Valutazione
Favourite;Preferito
Tags;Etichette
PlayedCount;Partite giocate
PlayedTime;Tempo giocato
PlayedLast;Ultimo giocato
FileIsAvailable;File disponibile
Shuffle;Riproduzione casuale

# -- filterCompDisplayStrings --
contains;contiene
does not contain;non contiene
does not equal;non è uguale
equals;è uguale
greater than;maggiore di
less than;minore di
greater than or equal;maggiore o uguale
less than or equal;minore o uguale

# -- commandDispStrings --
Back;Indietro
Up;Su
Down;Giù
Left;Sinistra
Right;Destra
Select;Selezione
Previous Game;Gioco precedente
Next Game;Gioco successivo
Previous Page;Pagina precedente
Next Page;Pagina successiva
Previous Display;Display precedente
Next Display;Display successivo
Displays Menu;Menù dei display
Previous Filter;Filtro precedente
Next Filter;Filtro successivo
Filters Menu;Menù dei filtri
Toggle Layout;Pagina successiva tema
Toggle Movie;Pausa video
Toggle Mute;Muto
Toggle Rotate Right;Rotazione a destra
Toggle Flip;Invertire
Toggle Rotate Left;Rotazione a sinistra
Exit;Uscita (Conferma)
Exit to Desktop;Esci al desktop
Reload Layout;Ricarica disposizione
Reload Config;Configurazione di ricarica
Reset Window;Reimposta finestra
Screenshot;Screenshot
Random Game;Gioco casuale
Replay Last Game;Esegui l'ultimo gioco
Toggle Fullscreen;Attiva/disattiva schermo intero
Add/Remove Favourite;Aggiungi/rimuovi preferito
Previous Favourite;Preferito precedente
Next Favourite;Preferito successivo
Add/Remove Tags;Aggiungi/rimuovi etichetta
Screen Saver;Salvaschermo
Previous Letter;Lettera precedente
Next Letter;Lettera successiva
Intro;Introduzione
Insert Game;Inserisci gioco
Layout Options;Opzioni del tema
Plugin Options;Opzioni plugin
Custom1;Personalizzato 1
Custom2;Personalizzato 2
Custom3;Personalizzato 3
Custom4;Personalizzato 4
Custom5;Personalizzato 5
Custom6;Personalizzato 6
Custom7;Personalizzato 7
Custom8;Personalizzato 8
Custom9;Personalizzato 9
Custom10;Personalizzato 10
Ambient Soundtrack;Musica di sottofondo
Startup Sound;Volume avvio
Game Return Sound;Suono di ritorno al gioco

# --uiColorDispTokens --
Indigo;Indaco
Blue;Blu
Cyan;Ciano
Turquoise;Turchese
Green;Verde
Acid;Acido
Gold;Oro
Yellow;Giallo
Orange;Arancione
Brown;Marrone
Rust;Ruggine
Red;Rosso
Pink;Rosa
Magenta;Magenta
Purple;Viola
Grey;Grigio
Neutral;Neutro
White;Bianco

# --windowModeDispTokens --
Fill Screen;Riempi schermo
Fullscreen;A schermo intero
Window;Finestra
Borderless Window;Finestra senza bordi

# --screenRotationDispTokens --
Flip;Inverti

# --startupDispTokens --
Show Last Selection;Mostra l'ultima selezione
Show Random Selection;Mostra selezione casuale
Launch Last Game;Esegui l'ultimo gioco
Show Displays Menu;Mostra menù dei display

# --filterWrapDispTokens --
Wrap within Display;Non cambiare display
Jump to Next Display;Salta al display successivo
No Wrap;Non ciclare

# -- settingDispStrings --
Sound Volume;Volume generale
Ambient Volume;Volume musica di sottofondo
Movie Volume;Volume dei video
Loudness Normalisation;Normalizzazione volume

# -- splash_message --
Generating Romlist;Generazione lista
Please Wait;Attendi
Scraping Artwork;Sto recuperando le immagini

# -- confirm_dialog --
Add '$1' to Favourites?;Aggiungo '$1' ai preferiti?
Auto-detect emulators?;Rilevamento automatico emulatori?
Found 1 emulator;Trovato 1 emulatore
Found $1 emulators;Trovati $1 emulatore
No emulators found;Nessun emulatore trovato
+$1 more;+$1 altro
Clear Hotkey?;Cancella tasto di scelta rapida?
Delete display '$1'?;Cancello il display '$1'?
Delete emulator '$1'?;Cancello l'emulatore '$1'?
Delete filter '$1'?;Cancello il filtro '$1'?
Delete game '$1'?;Cancello il gioco '$1'?
Delete shortcut '$1'?;Elimina collegamento '$1'?
Overwrite existing '$1' list?;Sovrascrivere la lista '$1'?
Remove '$1' from Favourites?;Elimino '$1' dai preferiti?
Rom path '$1' not found, proceed?;Percorso ROM '$1' non trovato, procedere?
Overwrite existing '$1' mapping?;Sovrascrivere la mappatura '$1' esistente?
A display with this name already exists;Esiste già un display con questo nome
Configuration files have been migrated\n to the 'config' folder.\nDelete old files?;I file di configurazione sono stati migrati\n nella cartella 'config'.\nEliminare i vecchi file?

# --input_map_dialog --
Press Hotkey;Premi il tasto di scelta rapida
Press Input;Premi il tasto

# -- edit_dialog --
Enter Display Name;Inserisci il nome del display
Enter Emulator Name;Inserisci il nome dell'emulatore
Enter Filter Name;Inserisci il nome del filtro
Enter Tag Name;Inserisci il nome dell'etichetta
Enter Romlist Name;Inserisci il nome della Romlist

# -- Titles --
Configure;Configurazione
Default Display Options;Opzioni di visualizzazione predefinite
Display Options;Opzioni di visualizzazione
Artwork Options;Opzioni grafiche
Control Options;Opzioni di controllo
Emulator Options;Opzioni dell'emulatore
Game Options;Opzioni di gioco
Shortcut Options;Opzioni di scelta rapida
Exception Options;Opzioni di eccezione
Filter Options;Opzioni di filtro
Rule Options;Opzioni di regola
Generate Collection/Romlist;Genera la lista di ROM

# --indexDispStrings --
Executable;Eseguibile
Command Arguments;Argomenti del comando
Working Directory;Directory di lavoro
Rom Path(s);Percorsi delle ROM
Rom Extension(s);Estensioni delle ROM
System Identifier;Identificatore del sistema
Info Source/Scraper;Sorgente informazioni/Recupero
Additional Import File(s);File aggiuntivo di import
Non-Blocking Mode Wait;Attendi modalità non bloccante
Exit Hotkey; Tasto per uscire
Pause Hotkey;Tasto di scelta rapida per la pausa

# -- datetime --
_datetime;%Y-%m-%d %H:%M:%S
A Moment Ago;Un attimo fa
Never;Mai
$1 Second;$1 secondo
$1 Minute;$1 minuto
$1 Hour;$1 ora
$1 Day;$1 giorno
$1 Minute Ago;$1 minuto fa
$1 Hour Ago;$1 ora fa
$1 Day Ago;$1 giorno fa
$1 Week Ago;$1 settimana fa
$1 Month Ago;$1 mese fa
$1 Year Ago;$1 anno fa
$1 Seconds;$1 secondo
$1 Minutes;$1 minuto
$1 Hours;$1 ora
$1 Days;$1 giorno
$1 Minutes Ago;$1 minuto fa
$1 Hours Ago;$1 ora fa
$1 Days Ago;$1 giorno fa
$1 Weeks Ago;$1 settimana fa
$1 Months Ago;$1 mese fa
$1 Years Ago;$1 anno fa

# -- help --
_help_art_add;Aggiunge una nuova risorsa immagini (marquee, flyer, screenshot, etc.)
_help_art_label;Nome che identifica questa risorsa immagini (viene utilizzato nei temi)
_help_art_path;Percorso nel quale è possibile trovare le immagini. Possono essere specificate più directory separandole con il punto e virgola.
_help_art;Una sorgente di immagini disponible per essere utilizzata con questo tema
_help_back;Menù precedente
_help_control_add_favourite;Configura i controlli per aggiungere/togliere dai preferiti il gioco selezionato
_help_control_add_tags;Configura i controlli per aggiungere/togliere etichette al gioco selezionato
_help_control_back;Configura i controlli per tornare indietro
_help_control_configure;Configura i controlli per mostrare il menù di configurazione
_help_control_custom1;Configura i controlli per il "Personalizzato 1"
_help_control_custom10;Imposta il controllo "Personalizzato 10"
_help_control_custom2;Configura i controlli per il "Personalizzato 2"
_help_control_custom3;Imposta il controllo "Personalizzato 3"
_help_control_custom4;Imposta il controllo "Personalizzato 4"
_help_control_custom5;Imposta il controllo "Personalizzato 5"
_help_control_custom6;Imposta il controllo "Personalizzato 6"
_help_control_custom7;Imposta il controllo "Personalizzato 7"
_help_control_custom8;Imposta il controllo "Personalizzato 8"
_help_control_custom9;Imposta il controllo "Personalizzato 9"
_help_control_displays_menu;Configura i controlli per mostrare il menù dei display
_help_control_down;Configura i controlli che muovono la selezione in basso
_help_control_edit_game;Configura i controlli per modificare la selezione corrente
_help_control_exit_to_desktop;Configura i controlli che permettono di uscire immediatamente dal programma e tornare al desktop
_help_control_exit;Configura i controlli che permettono di uscire dal frontend
_help_control_filters_menu;Configura i controlli per mostrare il menù dei filtri
_help_control_insert_game;Imposta il/i controllo/i che inseriscono una nuova voce di gioco
_help_control_intro;Configura i controlli per riprodurre il video introduttivo
_help_control_joystick_map;Assegna gli slot del joystick del frontend a dispositivi joystick/gamepad con nomi specifici collegati al computer (puoi usare questa opzione per forzare il frontend a usare sempre "Microsoft X-Box 360 pad" come Joystick 0, ad esempio).
_help_control_joystick_threshold;Umbral para los movimientos de palanca registrados, de 1 a 100 (100=menos sensible)
_help_control_layout_options;Imposta i controlli che mostrano il menu "Opzioni layout"
_help_control_plugin_options;Imposta i controlli che mostrano il menu "Opzioni plugin" per l'ultimo plugin visualizzato
_help_control_left;Configura i controlli per spostare la selezione a sinistra
_help_control_mouse_threshold;Sogla per il riconoscimento dei movimenti del mouse, accetta un valore da 1 a 100 (100 = meno sensibile)
_help_control_next_display;Configura i controlli per passare al display successivo
_help_control_next_favourite;Configura i controlli per passare al preferito successivo
_help_control_next_filter;Configura i controlli per passare al filtro successivo
_help_control_next_game;Configura i controlli per spostarsi al gioco successivo
_help_control_next_letter;Configura i controlli per passare alla lettera successiva
_help_control_next_page;Configura i controlli per spostarsi alla pagina successiva
_help_control_prev_display;Configura i controlli per passare al display precedente
_help_control_prev_favourite;Configura i controlli per passare al preferito precedente
_help_control_prev_filter;Configura i controlli per passare al filtro precedente
_help_control_prev_game;Configura i controlli per spostarsi al gioco precedente
_help_control_prev_letter;Configura i controlli per passare alla lettera precedente
_help_control_prev_page;Configura i controlli per spostarsi alla pagina precedente
_help_control_random_game;Configura i controlli per saltare ad un gioco casuale
_help_control_reload_layout;Imposta i controlli che ricaricano il layout corrente
_help_control_reload_config;Imposta i controlli che ricaricano i file di configurazione.
_help_control_reset_window;Imposta i controlli che reimpostano le dimensioni e la posizione della finestra
_help_control_replay_last_game;Configura i controlli per eseguire nuovamente l'ultimo titolo giocato
_help_control_right;Configura i controlli per spostare la selezione a destra
_help_control_screen_saver;Configura i controlli per eseguire immediatamente il salvaschermo
_help_control_screenshot;Configura i controlli per realizzare uno screenshot
_help_control_select;Configura i controlli per eseguire la selezione attuale
_help_control_selection_speed;Imposta la velocità del movimento di selezione in millisecondi per passo. Il valore predefinito è 40.
_help_control_selection_delay;Imposta il ritardo in millisecondi prima dell'inizio della ripetizione dei tasti. Il valore predefinito è 400.
_help_control_selection_max_step;Imposta la dimensione massima del passo per il movimento di selezione. Il valore predefinito è 128.
_help_control_toggle_flip;Configura i controlli per ruotare display di 180 gradi
_help_control_toggle_fullscreen;Alterna la modalità finestra tra Schermo intero e Finestra
_help_control_toggle_layout;Configura i controlli per cambiare la pagina del tema. Tale funzione dipende da come è stato costruito il tema stesso: con alcuni potrebbe non succedere nulla.
_help_control_toggle_movie;Configura i controlli per attivare/disattivare l'esecuzione dei video
_help_control_toggle_mute;Configura i controlli che disabilitano e riabilitano l'audio del frontend
_help_control_toggle_rotate_left;Configura i controlli per ruotare il display a sinistra di 90 gradi
_help_control_toggle_rotate_right;Configura i controlli per ruotare il display a destra di 90 gradi
_help_control_up;Configura i controlli che muovono la selezione in alto
_help_display_add_filter;Aggiungere un filtro al gruppo di filtri di questo display
_help_display_add;Aggiunge un nuovo display
_help_display_delete;Cancella questo display
_help_display_filter;Modifica la configurazione di questo filtro
_help_display_global_filter;Configura regole ed eccezioni che verranno applicate a ciascun titolo presente nella lista di ROM di questo display
_help_display_in_cycle;Includere questo display nel ciclo "Display precedente"/"Display successivo"
_help_display_in_menu;Includere questo display nel menù dei display
_help_display_layout_options;Configura le impostazioni specifiche per questo tema
_help_display_layout;Tema da utilizzare con questo display
_help_display_name;Il nome di questo display
_help_display_romlist;Lista di ROM da utilizzare con questo display
_help_display_sel;Configura il display
_help_display_edit_default;Configura le opzioni predefinite da utilizzare per i nuovi display
_help_displaysmenu_exit;Definisce se l'opzione di uscita dal programma deve essere presente nel menù dei display
_help_displaysmenu_layout;Il tema da utilizzare per il Menù dei display. Imposta su 'Predefinito' per utilizzare quello interno del frontend.
_help_displaysmenu_prompt;Il titolo del Menù dei display (es: "Scegli l'emulatore")
_help_displaysmenu;Configura le opzioni per il Menù dei display
_help_emu_add;Aggiungere un nuovo emulatore
_help_emu_args;Gli argomenti della linea di comando di questo emulatore. I seguenti parametri verranno sostituiti appropriatamente: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;Cancella le impostazioni di questo emulatore
_help_emu_executable;Percorso completo e nome dell'eseguibile dell'emulatore. $HOME verrà rimpiazzato con la home directory dell'utente
_help_emu_exit_hotkey;Configura una hotkey per uscire dall'emulatore. Attract-Mode Plus terminerà l'emulatore se questa hotkey verrà premuta
_help_emu_gen_romlist;Genera la lista di ROM cercando all'interno dei percorsi indicati file con le estensioni specificate, incorporando anche le informazioni recuperate dai file aggiuntivi quando disponibili
_help_emu_import_extras;Percorso per ogni file aggiuntivo che deve essere letto quando viene generata una lista di ROM per questo emulatore. I file supportati sono: catver.ini (per le categorie dei giochi), nplayers.ini (per il numero dei giocatori) e mame.xml. Possono essere specificate più directory separandole con il punto e virgola.
_help_emu_info_source;Usare "listxml" se l'emulatore restituisce un output compatibile MAME -listxml, "listsoftware" per le liste software compatibili mame/mess -listsoftware, "thegamesdb.net" per recuperare le informazioni da thegamesdb.net, o "steam" per leggere da una installazione Steam, o "scummvm" se l'emulatore è ScummVM.  "listsoftware" e "thegamesdb.net" richiedono che venga configurato un identificatore di sistema riconosciuto da queste sorgenti.
_help_emu_name;Modifica emulatore.
_help_emu_nb_mode_wait;Configura un tempo mínimo di esecuzione (in secondi).  Attract-Mode Plus aspetterà dopo aver eseguito l'emulatore finché è scaduto il tempo minimo, dopodiché passerà in primo piano. Questo deve essere impostato con Steam per funzionare correttamente su Windows. Impostare questo valore a 0 a meno che non si sappia quello che si fa.
_help_emu_pause_hotkey;Imposta un tasto di scelta rapida globale per mettere in pausa l'emulatore. Se premuto, Attract-Mode Plus metterà in pausa il processo dell'emulatore e tornerà al frontend. Il processo dell'emulatore può essere ripreso selezionando nuovamente lo stesso gioco nel frontend.
_help_emu_romext;Estensioni dei file ROM per questo emulatore (per es. .zip) Più estensioni possono essere inserite utilizzando il punto e virgola. Specificare "<DIR>" come valore se i giochi sono memorizzati in sottodirectory separate.
_help_emu_rompath;Percorsi per le ROM di questo emulatore. Possono essere specificate più directory separandole con il punto e virgola.
_help_emu_scrape_artwork;Recupera le immagini mancanti per questo emulatore dai siti specializzati
_help_emu_sel_auto_detect;Questo analizzerà la cartella principale alla ricerca di emulatori noti e genererà configurazioni predefinite per ogni emulatore trovato
_help_emu_sel_gen_romlist;Genera una Collezione/Romlist contenente giochi per più emulatori
_help_emu_sel;Configura le impostazioni dell'emulatore
_help_emu_system;Identificatori del sistema per questo emulatore. Più valori possono essere inseriti utilizzando il punto e virgola.
_help_emu_workdir;Imposta la directory di lavoro per questo emulatore: si tratta della directory dalla quale il frontend eseguirà l'emulatore. Tutti i percorsi relativi di ROM, artwork paths o altro faranno riferimento a questa directory.
_help_filter_add_exception;Aggiunge un'eccezione per questo filtro. Se un gioco soddisfa l'eccezione (e non è già stato escluso da una regola precedente), questo verrà incluso nel filtro.
_help_filter_add_rule;Aggiunge una regola per questo filtro
_help_filter_delete;Cancella questo filtro
_help_filter_exception;Configura l'eccezione
_help_filter_list_limit;Imposta un valore diverso da zero se vuoi limitare il numero di voci presenti nella lista. Utilizza un valore positivo per recuperare i primi titoli (per esempio "10" restituirà i primi 10 titoli), un valore negativo per recuperare gli ultimi (per esempio "-25" restituirà gli ultimi 25 titoli), oppure "0" per averli tutti
_help_filter_name;Il nome di questo filtro
_help_filter_reverse_order;Inverti l'ordine della raccolta/elenco rom ordinati. L'ordine predefinito è "dalla A alla Z" per le informazioni, "dal più grande al più piccolo" per le statistiche o l'ordine dell'elenco sorgente per "Nessun ordinamento".
_help_filter_rule;Configura le regole per il filtro
_help_filter_sort_by;L'attributo del gioco che deve essere utilizzato per ordinare la lista. Imposta "Nessun ordinamento" per mantenere l'ordinamento originale della lista
_help_game_custom_args;Imposta dei parametri differenti per questo gioco
_help_game_custom_executable;Imposta un eseguibile differente per eseguire questo gioco
_help_game_delete;Cancella questo gioco dalla lista
_help_game_edit;Modifica le informazioni del gioco
_help_game_overview;Modifica la panoramica del gioco
_help_generator_build;Genera la Romlist utilizzando gli emulatori selezionati
_help_generator_opt;Permette di specificare se includere i giochi di questo emulatore nella Romlist
_help_input_action;
_help_input_add;Aggiunge una nuova associazione dei tasti per questa azione
_help_input_default_action;Configura l'azione predefinita per questo controllo
_help_input_delete;Cancella questa associazione dei tasti
_help_layout_file;Alcuni layout forniscono più file layout*.nut. Seleziona il file di layout da utilizzare
_help_layout_name;Configura il layout
_help_main_control;Configura gli input di joystick, tastiera e mouse per controllare Attract-Mode Plus
_help_main_display;I display sono associazioni lista di ROM/tema che possono essere utilizzati in Attract-Mode Plus per visualizzare liste di giochi e selezionare quello che si vuole giocare
_help_main_emu;Configura le opzioni dell'emulatore
_help_main_intro;Configura le opzioni di introduzione
_help_main_settings;Configura le opzioni generali
_help_main_plugin;Configura le opzioni del plugin
_help_main_scraper;Configura le opzioni dello scraper
_help_main_screensaver_timeout;Numero di secondi da attendere prima di attivare il salvaschermo. Inserire 0 per disabilitarlo
_help_main_screensaver;Configura il salvaschermo
_help_main_sound;Configura il volume dei suoni, l'associazione dei suoni agli eventi e la musica d'ambiente
_help_misc_anisotropic_filtering;Imposta il livello di filtro anisotropico per le texture. Questo migliorerà la qualità delle texture ridimensionate
_help_misc_antialiasing;Imposta il livello di anti-aliasing.
_help_misc_check_for_updates;Configura se Attract-Mode Plus deve verificare la disponibilità di aggiornamenti all'avvio e visualizzare una finestra di notifica di aggiornamento quando viene trovata una nuova versione.
_help_misc_confirm_exit;Permette di chiedere la conferma prima di uscire da Attract-Mode Plus
_help_misc_confirm_favs;Conferma l'aggiunta/rimozione del gioco dai preferiti
_help_misc_custom_overlay;Consenti ai layout di personalizzare l'overlay utilizzato per i menu Display, Filtro, Tag ed Esci
_help_misc_exit_command;Comando da eseguire quando viene selezionata l'uscita dal programma (con conferma) [per es. "sudo shutdown"]
_help_misc_exit_message;Messaggio alternativo per uscire dal frontend [ad esempio "Spegni il sistema"]
_help_misc_filter_wrap_mode;Configura cosa succede quando i comandi "Filtro successivo" o "Filtro precedente" raggiungono il termine della lista
_help_misc_group_clones;Raggruppa tutti i cloni di un gioco in un'unica voce dell'elenco
_help_misc_hide_brackets;Nasconde il testo tra parentesi quando viene mostrato il titolo del gioco
_help_misc_prefix_modes;Sposta "The" e "Vs." prefissi alla fine del titolo del gioco
_help_misc_hide_console;Nascondi la console all'avvio. Nota: questo funziona solo se Attract-Mode Plus viene avviato da un'interfaccia utente grafica di Windows. Se avviato da una finestra della console esistente (ad esempio, un file batch), il processo si "collegherà" sempre alla console esistente e vi invierà l'output.
_help_misc_image_cache_mbytes;Configura la dimensione massima della cache immagini interna di Attract-Mode Plus (in megabyte)
_help_misc_language;Seleziona la lingua dell'interfaccia di Attract-Mode Plus
_help_misc_layout_preview;Mostra immediatamente le modifiche alla configurazione del layout
_help_misc_multiple_monitors;Abilita l'utilizzo di monitor multipli
_help_misc_power_saving;Aiuta a risparmiare energia ridisegnando lo schermo solo quando necessario. Può causare interruzioni nell'animazione su alcuni layout o blocchi su Linux
_help_misc_quick_menu;Imposta se i menu possono essere aperti e chiusi con lo stesso pulsante. Permette anche di passare da un menu all'altro senza doverli prima chiudere
_help_misc_screen_rotation;Imposta la rotazione di base dello schermo
_help_misc_startup_mode;Configura come si deve comportare Attract-Mode Plus quando viene eseguito
_help_misc_track_usage;Configura se Attract-Mode Plus deve gestire le statistiche di utilizzo (tempo complessivo e numero di partite giocate per ciascun titolo)
_help_misc_ui_color;Seleziona il colore da utilizzare nell'interfaccia utente di Attract-Mode Plus
_help_misc_video_decoder;Configura il decoder da utilizzare per riprodurre i video (nel caso siano disponibili più decoder)
_help_misc_window_mode;Configura se il frontend deve lavorare a tutto schermo o essere eseguito in una finestra
_help_plugin_command;Eseguibile associato a questo plugin
_help_plugin_enabled;Configura se questo plugin è abilitato
_help_plugin_name;Configura il plugin
_help_plugin_sel;Configura i plugin
_help_rule_comp;Tipo di comparazione per questo filtro
_help_rule_delete;Cancellare questa regola
_help_rule_target;L'attributo del gioco sul quale basare il filtro
_help_rule_value;Espressione regolare con la quale filtrare. Per esempio, se l'obbiettivo del filtro è "Anno" e la comparazione è "Uguale", un valore di "1984" restituirà tutti i giochi prodotti nel 1984, mentre "198." restituirà tutti i giochi prodotti negli anni '80
_help_scraper_fanart;Stabilisce se le fanart devono essere recuperate dalla rete
_help_scraper_flyers;Stabilisce se i flyers e le copertine delle confezioni devono essere recuperate dalla rete
_help_scraper_marquees;Stabilisce se i marquee devono essere recuperati dalla rete
_help_scraper_snaps;Stabilisce se gli snapshot devono essere recuperati dalla rete
_help_scraper_vids;Stabilisce se i video devono essere recuperati dalla rete
_help_scraper_wheels;Stabilisce se i logo devono essere recuperati dalla rete
_help_shortcut_artwork_name;Facoltativamente, fornisci un nome di grafica da associare a questa scorciatoia. Il frontend proverà a caricare le illustrazioni con questo nome quando visualizza la scorciatoia
_help_shortcut_delete;Elimina questa scorciatoia dalla Romlist
_help_shortcut_label;Modifica l'etichetta di questa scorciatoia
_help_shortcut_target;Modifica la destinazione di questo collegamento
_help_sound_loudness_normalisation;Abilita un effetto audio che aumenta automaticamente il volume dei contenuti multimediali a volume basso a un livello costante
_help_sound_sel;Assegna un suono a questo evento/azione
_help_sound_volume;Imposta il volume per questa sorgente audio

# -- screensaver --

Basic Movie;Filmato base
Movie Collage;Collage di filmati
Image Collage;Collage di immagini
RGB Movie;Filmato RGB
Overlay Artwork;Sovrapposizione grafica
Play Sound;Riproduci audio
Preserve Aspect Ratio;Mantieni proporzioni
Blank Screen Time;Tempo di visualizzazione schermo vuoto
Blank Screen Start Command;Comando di avvio schermata vuota
Blank Screen Stop Command;Comando di arresto schermata vuota
Play intro;Riproduci intro
Detect aspect ratio;Rileva proporzioni
Default video;Video predefinito
16:9 video;Video 16:9
4:3 video;Video 4:3
9:16 video;Video 9:16
3:4 video;Video 3:4

# -- extra --
