#@Italiano

# -- generic --
$1 Rule(s);$1 regole
#Blank Game;
#Custom;
Default;Predefinito
Disabled;Disabilitato
Empty;Vuoto
#False;
#Multi;
No Sort;Nessun ordinamento
#No;
None;Nessuno
#Off;
#On;
OR;o
#True;
Yes;Si

# -- misc --
Displays Menu Options;Opzioni del Menù dei display
Action;Azione
Add Artwork;Aggiungi risorsa immagini
Add Emulator;Aggiungi emulatore
Add Exception;Aggiungi eccezione
Add Filter;Aggiungi filtro
Add Input;Aggiungi controllo
Add New Display;Aggiungi nuovo display
Add Rule;Aggiungi regola
Allow Exit;Consenti uscita
#Anisotropic Filtering;
#Anti-Aliasing;
Artwork Label;Nome della risorsa
#Artwork Name;
Artwork Path;Percorso della risorsa
#Auto-detect Emulators;
#Check for Updates;
Collection/Rom List;Lista di ROM
Comparison;Comparazione
Confirm Exit;Conferma l'uscita
Confirm Favourites;Conferma aggiunta preferito
Controls;Controlli
Create new tag;Crea una nuova etichetta
Custom Arguments;Argomenti personalizzati
Custom Executable;Eseguibile personalizzato
Default Action;Azione predefinita
Delete this Display;Cancella questo display
Delete this Emulator;Cancella questo emulatore
Delete this Filter;Cancella questo filtro
Delete this Game;Cancella il gioco
Delete this Rule;Cancella questa regola
#Delete this Shortcut;
Displays;Display
Emulator Name;Nome dell'emulatore
Emulators;Emulatori
Enable Multiple Monitors;Abilita monitor multipli
Enabled;Attivo
Exception;Eccezione
Exit Attract-Mode Plus;Esci da Attract-Mode Plus
Exit Attract-Mode Plus?;Uscire da Attract-Mode Plus?
Exit Command;Comando per uscire
#Exit Message;
Filter Name;Nome del filtro
Filter Value;Valore da comparare
Filter Wrap Mode;Metodo di scorrimento dei filtri
Filter;Filtro
General;Varie
Global Filter;Filtro globale
#Group Clones;
Hide Brackets in Game Title;Nascondere le parentesi nei titoli
#Hide Console;
#Image Cache Size;
#Insert Command Shortcut;
#Insert Display Shortcut;
#Insert Game Entry;
#Insert Menu Entry;
#Joystick $1;
#Joystick Mappings;
Joystick Threshold;Soglia del joystick
Language;Lingua
#Layout File;
Layout Options;Opzioni del tema
Layout Preview;Anteprima del layout
Layout;Tema
List Limit;Límite della lista
Menu Colour;Colore del menù
Menu Prompt;Titolo del menù
Menu Toggle;Menu Alterna
Mouse Threshold;Soglia del mouse
Overview;Panoramica
Plug-ins;Plugin
#Power Saving;
Remove Input;Eliminare il controllo
#Reverse Order;
Rule;Regola
Scrape Artwork;Recupera le immagini
Scrape Fanart;Recupera le fanart
Scrape Flyers/Boxart;Recupera i flyer/boxart
Scrape Game Logos (Wheel Art);Recupera i logo
Scrape Marquees;Recupera i marquee
Scrape Snaps;Recupera le snap
Scrape Videos (MAME only);Scarica video (solo per MAME)
Scraper;Recupera dalla rete
#Screen Rotation;
Screen Saver Timeout;Timeout salvaschermo
#Select template to use for emulator settings;
Show in Cycle;Mostra nel ciclo
Show in Menu;Mostra nel menù
Sort By;Ordinato per
Sound;Suoni
Startup Mode;Modalità di avvio
Target;Obbiettivo
Title;Titolo
Track Usage;Memorizza statistiche di utilizzo
Video Decoder;Decoder video
Window Mode;Modalità finestra
Wrote $1 entries to Collection/Rom List;$1 titoli scritti nella lista di ROM

# -- indexStrings --
Name;Nome
Title;Titolo
Emulator;Emulatore
CloneOf;Clone di
Year;Anno
Manufacturer;Produttore
Category;Categoría
Players;Giocatori
Rotation;Rotazione
Control;Controllo
Status;Stato
DisplayCount;Contatore di display
DisplayType;Tipo di display
AltRomname;Nome alternativo della ROM
AltTitle;Titolo alternativo
#Extra;
Buttons;Pulsanti
#Series;
Language;Lingua
#Region;
#Rating;
Favourite;Preferito
Tags;Etichette
PlayedCount;Partite giocate
PlayedTime;Tempo giocato
#PlayedLast;
#FileIsAvailable;
#Shuffle;

# -- filterCompDisplayStrings --
contains;contiene
does not contain;non contiene
does not equal;non è uguale
equals;è uguale

# -- commandDispStrings --
Back;Indietro
Up;Su
Down;Giù
Left;Sinistra
Right;Destra
Select;Selezione
Previous Game;Gioco precedente
Next Game;Gioco successivo
Previous Page;Pagina precedente
Next Page;Pagina successiva
Previous Display;Display precedente
Next Display;Display successivo
Displays Menu;Menù dei display
Previous Filter;Filtro precedente
Next Filter;Filtro successivo
Filters Menu;Menù dei filtri
Toggle Layout;Pagina successiva tema
Toggle Movie;Pausa video
Toggle Mute;Muto
Toggle Rotate Right;Rotazione a destra
Toggle Flip;Invertire
Toggle Rotate Left;Rotazione a sinistra
Exit;Uscita (Conferma)
Exit to Desktop;Esci al desktop
Reload;Ricaricare
#Screenshot;
Random Game;Gioco casuale
Replay Last Game;Esegui l'ultimo gioco
Add/Remove Favourite;Aggiungi/rimuovi preferito
Previous Favourite;Preferito precedente
Next Favourite;Preferito successivo
Add/Remove Tags;Aggiungi/rimuovi etichetta
Screen Saver;Salvaschermo
Previous Letter;Lettera precedente
Next Letter;Lettera successiva
Intro;Video introduttivo
#Insert Game;
Layout Options;Opzioni del tema
Custom1; Personalizzato 1
Custom2; Personalizzato 2
Custom3; Personalizzato 3
Custom4; Personalizzato 4
Custom5; Personalizzato 5
Custom6; Personalizzato 6
Custom7; Personalizzato 7
Custom8; Personalizzato 8
Custom9; Personalizzato 9
Custom10; Personalizzato 10
Ambient Soundtrack;Musica di sottofondo
Startup Sound;Volume avvio
Game Return Sound;Suono di ritorno al gioco

# --uiColorDispTokens --
#Indigo;
#Blue;
#Cyan;
#Turquoise;
#Green;
#Acid;
#Gold;
#Yellow;
#Orange;
#Brown;
#Rust;
#Red;
#Pink;
#Magenta;
#Purple;
#Grey;
#Neutral;
#White;

# --windowModeDispTokens --
Fill Screen;Riempi schermo
Fullscreen Mode;A tutto schermo
Window;Finestra
Window (No Border);Finestra (Senza bordi)

# --screenRotationDispTokens --
Flip;Inverti

# --startupDispTokens --
Show Last Selection;Mostra l'ultima selezione
Launch Last Game;Esegui l'ultimo gioco
Show Displays Menu;Mostra menù dei display

# --filterWrapDispTokens --
Wrap within Display;Non cambiare display
Jump to Next Display;Salta al display successivo
No Wrap;Non ciclare

# -- antialiasingDispTokens --
#MSAA x2;
#MSAA x4;
#MSAA x8;

# -- FeSettings::anisotropicDispTokens --
#x2;
#x4;
#x8;
#x16;

# -- settingDispStrings --
Sound Volume;Volume generale
Ambient Volume;Volume musica di sottofondo
Movie Volume;Volume dei video
#Loudness Normalisation;

# -- splash_message --
#Generating index ($1%);
Generating Rom List: $1%;Generazione lista: $1%
#Please Wait;
Scraping Artwork: $1%;Sto recuperando le immagini: $1%

# -- confirm_dialog --
Add '$1' to Favourites?;Aggiungo '$1' ai preferiti?
#Attract-Mode Plus detected emulator(s) that can be imported automatically.  Import them now?;
#Auto-detect emulators?;
#Clear Hotkey?;
Delete display '$1'?;Cancello il display '$1'?
Delete emulator '$1'?;Cancello l'emulatore '$1'?
Delete filter '$1'?;Cancello il filtro '$1'?
Delete game '$1'?;Cancello il gioco '$1'?
#Delete shortcut '$1'?;
Overwrite existing '$1' list?;Sovrascrivere la lista '$1'?
Remove '$1' from Favourites?;Elimino '$1' dai preferiti?
Rom path '$1' not found, proceed anyways?;Percorso delle rom '$1' non trovato, continuare?
This will overwrite an existing mapping ($1).  Proceed?;Sovrascrivere l'associazione esistente ($1)?

# --input_map_dialog --
#Press Hotkey;
Press Input;Premi il tasto

# -- edit_dialog --
Enter Display Name;Inserisci il nome del display
Enter Emulator Name;Inserisci il nome dell'emulatore
Enter Filter Name;Inserisci il nome del filtro
Enter new tag name;Inserisci il nome dell'etichetta
Enter Romlist Name;Inserisci il nome della Romlist

# -- Titles --
#_submenu;
Configure Layout;Configura il tema
Configure Plug-in;Configura i plugin
Configure;Configurazione
Display Edit;Modifica il display
Edit Artwork;Modifica risorsa immagini
Edit Control;Modifica controllo
Edit Emulator;Modifica emulatore
Edit Game;Modifica il gioco
#Edit Shortcut;
Exception Edit;Modifica l'eccezione
Filter Edit;Modifica filtro
Generate Collection/Rom List;Genera la lista di ROM
Rule Edit;Modifica la regola

# --indexDispStrings --
Executable;Eseguibile
Command Arguments;Argomenti del comando
Working Directory;Directory di lavoro
Rom Path(s);Percorsi delle ROM
Rom Extension(s);Estensioni delle ROM
System Identifier;Identificatore del sistema
Info Source/Scraper;Sorgente informazioni/Recupero
Additional Import File(s);File aggiuntivo di import
#Non-Blocking Mode Wait;
Exit Hotkey; Tasto per uscire
#Pause Hotkey;

# -- datetime --
#_datetime;
#A Moment Ago;
#Never;
#$1 Second;
#$1 Minute;
#$1 Hour;
#$1 Day;
#$1 Minute Ago;
#$1 Hour Ago;
#$1 Day Ago;
#$1 Week Ago;
#$1 Month Ago;
#$1 Year Ago;
#$1 Seconds;
#$1 Minutes;
#$1 Hours;
#$1 Days;
#$1 Minutes Ago;
#$1 Hours Ago;
#$1 Days Ago;
#$1 Weeks Ago;
#$1 Months Ago;
#$1 Years Ago;

# -- help --
_help_art_add;Aggiunge una nuova risorsa immagini (marquee, flyer, screenshot, etc.)
_help_art_label;Nome che identifica questa risorsa immagini (viene utilizzato nei temi)
_help_art_path;Percorso nel quale è possibile trovare le immagini. Possono essere specificate più directory separandole con il punto e virgola.
_help_art;Una sorgente di immagini disponible per essere utilizzata con questo tema
_help_back;Menù precedente
_help_control_add_favourite;Configura i controlli per aggiungere/togliere dai preferiti il gioco selezionato
_help_control_add_tags;Configura i controlli per aggiungere/togliere etichette al gioco selezionato
_help_control_back;Configura i controlli per tornare indietro
_help_control_configure;Configura i controlli per mostrare il menù di configurazione
_help_control_custom1;Configura i controlli per il "Personalizzato 1"
_help_control_custom10;Imposta il controllo "Personalizzato 10"
_help_control_custom2;Configura i controlli per il "Personalizzato 2"
_help_control_custom3;Imposta il controllo "Personalizzato 3"
_help_control_custom4;Imposta il controllo "Personalizzato 4"
_help_control_custom5;Imposta il controllo "Personalizzato 5"
_help_control_custom6;Imposta il controllo "Personalizzato 6"
_help_control_custom7;Imposta il controllo "Personalizzato 7"
_help_control_custom8;Imposta il controllo "Personalizzato 8"
_help_control_custom9;Imposta il controllo "Personalizzato 9"
_help_control_displays_menu;Configura i controlli per mostrare il menù dei display
_help_control_down;Configura i controlli che muovono la selezione in basso
_help_control_edit_game;Configura i controlli per modificare la selezione corrente
_help_control_exit_to_desktop;Configura i controlli che permettono di uscire immediatamente dal programma e tornare al desktop
_help_control_exit;Configura i controlli che permettono di uscire dal frontend
_help_control_filters_menu;Configura i controlli per mostrare il menù dei filtri
#_help_control_insert_game;
_help_control_intro;Configura i controlli per riprodurre il video introduttivo
#_help_control_joystick_map;
_help_control_joystick_threshold;Umbral para los movimientos de palanca registrados, de 1 a 100 (100=menos sensible)
#_help_control_layout_options;
_help_control_left;Configura i controlli per spostare la selezione a sinistra
_help_control_mouse_threshold;Sogla per il riconoscimento dei movimenti del mouse, accetta un valore da 1 a 100 (100 = meno sensibile)
_help_control_next_display;Configura i controlli per passare al display successivo
_help_control_next_favourite;Configura i controlli per passare al preferito successivo
_help_control_next_filter;Configura i controlli per passare al filtro successivo
_help_control_next_game;Configura i controlli per spostarsi al gioco successivo
_help_control_next_letter;Configura i controlli per passare alla lettera successiva
_help_control_next_page;Configura i controlli per spostarsi alla pagina successiva
_help_control_prev_display;Configura i controlli per passare al display precedente
_help_control_prev_favourite;Configura i controlli per passare al preferito precedente
_help_control_prev_filter;Configura i controlli per passare al filtro precedente
_help_control_prev_game;Configura i controlli per spostarsi al gioco precedente
_help_control_prev_letter;Configura i controlli per passare alla lettera precedente
_help_control_prev_page;Configura i controlli per spostarsi alla pagina precedente
_help_control_random_game;Configura i controlli per saltare ad un gioco casuale
_help_control_reload;Configura i controlli che ricaricano il layout corrente
_help_control_replay_last_game;Configura i controlli per eseguire nuovamente l'ultimo titolo giocato
_help_control_right;Configura i controlli per spostare la selezione a destra
_help_control_screen_saver;Configura i controlli per eseguire immediatamente il salvaschermo
_help_control_screenshot;Configura i controlli per realizzare uno screenshot
_help_control_select;Configura i controlli per eseguire la selezione attuale
_help_control_toggle_flip;Configura i controlli per ruotare display di 180 gradi
_help_control_toggle_layout;Configura i controlli per cambiare la pagina del tema. Tale funzione dipende da come è stato costruito il tema stesso: con alcuni potrebbe non succedere nulla.
_help_control_toggle_movie;Configura i controlli per attivare/disattivare l'esecuzione dei video
_help_control_toggle_mute;Configura i controlli che disabilitano e riabilitano l'audio del frontend
_help_control_toggle_rotate_left;Configura i controlli per ruotare il display a sinistra di 90 gradi
_help_control_toggle_rotate_right;Configura i controlli per ruotare il display a destra di 90 gradi
_help_control_up;Configura i controlli che muovono la selezione in alto
_help_display_add_filter;Aggiungere un filtro al gruppo di filtri di questo display
_help_display_add;Aggiunge un nuovo display
_help_display_delete;Cancella questo display
_help_display_filter;Modifica la configurazione di questo filtro
_help_display_global_filter;Configura regole ed eccezioni che verranno applicate a ciascun titolo presente nella lista di ROM di questo display
_help_display_in_cycle;Includere questo display nel ciclo "Display precedente"/"Display successivo"?
_help_display_in_menu;Includere questo display nel menù dei display?
_help_display_layout_options;Configura le impostazioni specifiche per questo tema
_help_display_layout;Tema da utilizzare con questo display
_help_display_name;Il nome di questo display
_help_display_romlist;Lista di ROM da utilizzare con questo display
_help_display_sel;Configura il display
_help_displaysmenu_exit;Definisce se l'opzione di uscita dal programma deve essere presente nel menù dei display
_help_displaysmenu_layout;Il tema da utilizzare per il Menù dei display. Imposta su 'Predefinito' per utilizzare quello interno del frontend.
_help_displaysmenu_prompt;Il titolo del Menù dei display (es: "Scegli l'emulatore")
_help_displaysmenu;Configura le opzioni per il Menù dei display
_help_emu_add;Aggiungere un nuovo emulatore
_help_emu_args;Gli argomenti della linea di comando di questo emulatore. I seguenti parametri verranno sostituiti appropriatamente: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;Cancella le impostazioni di questo emulatore
_help_emu_executable;Percorso completo e nome dell'eseguibile dell'emulatore. $HOME verrà rimpiazzato con la home directory dell'utente
_help_emu_exit_hotkey;Configura una hotkey per uscire dall'emulatore. Attract-Mode Plus terminerà l'emulatore se questa hotkey verrà premuta
_help_emu_gen_romlist;Genera la lista di ROM cercando all'interno dei percorsi indicati file con le estensioni specificate, incorporando anche le informazioni recuperate dai file aggiuntivi quando disponibili
_help_emu_import_extras;Percorso per ogni file aggiuntivo che deve essere letto quando viene generata una lista di ROM per questo emulatore. I file supportati sono: catver.ini (per le categorie dei giochi), nplayers.ini (per il numero dei giocatori) e mame.xml. Possono essere specificate più directory separandole con il punto e virgola.
_help_emu_info_source;Usare "listxml" se l'emulatore restituisce un output compatibile MAME -listxml, "listsoftware" per le liste software compatibili mame/mess -listsoftware, "thegamesdb.net" per recuperare le informazioni da thegamesdb.net, o "steam" per leggere da una installazione Steam, o "scummvm" se l'emulatore è ScummVM.  "listsoftware" e "thegamesdb.net" richiedono che venga configurato un identificatore di sistema riconosciuto da queste sorgenti.
#_help_emu_name;
_help_emu_nb_mode_wait;Configura un tempo mínimo di esecuzione (in secondi).  Attract-Mode Plus aspetterà dopo aver eseguito l'emulatore finché è scaduto il tempo minimo, dopodiché passerà in primo piano. Questo deve essere impostato con Steam per funzionare correttamente su Windows. Impostare questo valore a 0 a meno che non si sappia quello che si fa.
#_help_emu_pause_hotkey;
_help_emu_romext;Estensioni dei file ROM per questo emulatore (per es. .zip) Più estensioni possono essere inserite utilizzando il punto e virgola. Specificare "<DIR>" come valore se i giochi sono memorizzati in sottodirectory separate.
_help_emu_rompath;Percorsi per le ROM di questo emulatore. Possono essere specificate più directory separandole con il punto e virgola.
_help_emu_scrape_artwork;Recupera le immagini mancanti per questo emulatore dai siti specializzati
#_help_emu_sel_auto_detect;
_help_emu_sel_gen_romlist;Genera una Collezione/Romlist contenente giochi per più emulatori
_help_emu_sel;Configura le impostazioni dell'emulatore
_help_emu_system;Identificatori del sistema per questo emulatore. Più valori possono essere inseriti utilizzando il punto e virgola.
_help_emu_workdir;Imposta la directory di lavoro per questo emulatore: si tratta della directory dalla quale il frontend eseguirà l'emulatore. Tutti i percorsi relativi di ROM, artwork paths o altro faranno riferimento a questa directory.
_help_filter_add_exception;Aggiunge un'eccezione per questo filtro. Se un gioco soddisfa l'eccezione (e non è già stato escluso da una regola precedente), questo verrà incluso nel filtro.
_help_filter_add_rule;Aggiunge una regola per questo filtro
_help_filter_delete;Cancella questo filtro
_help_filter_exception;Configura l'eccezione
_help_filter_list_limit;Imposta un valore diverso da zero se vuoi limitare il numero di voci presenti nella lista. Utilizza un valore positivo per recuperare i primi titoli (per esempio "10" restituirà i primi 10 titoli), un valore negativo per recuperare gli ultimi (per esempio "-25" restituirà gli ultimi 25 titoli), oppure "0" per averli tutti
_help_filter_name;Il nome di questo filtro
#_help_filter_reverse_order;
_help_filter_rule;Configura le regole per il filtro
_help_filter_sort_by;L'attributo del gioco che deve essere utilizzato per ordinare la lista. Imposta "Nessun ordinamento" per mantenere l'ordinamento originale della lista
_help_game_custom_args;Imposta dei parametri differenti per questo gioco
_help_game_custom_executable;Imposta un eseguibile differente per eseguire questo gioco
_help_game_delete;Cancella questo gioco dalla lista
_help_game_edit;Modifica le informazioni del gioco
_help_game_overview;Modifica la panoramica del gioco
_help_generator_build;Genera la Romlist utilizzando gli emulatori selezionati
_help_generator_opt;Permette di specificare se includere i giochi di questo emulatore nella RomList
_help_input_action;
_help_input_add;Aggiunge una nuova associazione dei tasti per questa azione
_help_input_default_action;Configura l'azione predefinita per questo controllo
_help_input_delete;Cancella questa associazione dei tasti
#_help_layout_file;
#_help_layout_name;
_help_main_control;Configura gli input di joystick, tastiera e mouse per controllare Attract-Mode Plus
_help_main_display;I display sono associazioni lista di ROM/tema che possono essere utilizzati in Attract-Mode Plus per visualizzare liste di giochi e selezionare quello che si vuole giocare
_help_main_emu;Configura le impostazioni degli emulatori
_help_main_intro;Configura il video di introduzione
_help_main_misc;Configurazioni varie
_help_main_plugin;Configura i plugin disponibili
_help_main_scraper;Configura le impostazioni per il recupero delle immagini dalla rete
_help_main_screensaver_timeout;Numero di secondi da attendere prima di attivare il salvaschermo. Inserire 0 per disabilitarlo
_help_main_screensaver;Configura il salvaschermo
_help_main_sound;Configura il volume dei suoni, l'associazione dei suoni agli eventi e la musica d'ambiente
#_help_misc_anisotropic_filtering;
#_help_misc_antialiasing;
#_help_misc_check_for_updates;
_help_misc_confirm_exit;Permette di chiedere la conferma prima di uscire da Attract-Mode Plus
_help_misc_confirm_favs;Conferma l'aggiunta/rimozione del gioco dai preferiti
_help_misc_exit_command;Comando da eseguire quando viene selezionata l'uscita dal programma (con conferma) [per es. "sudo shutdown"]
#_help_misc_exit_message;
_help_misc_filter_wrap_mode;Configura cosa succede quando i comandi "Filtro successivo" o "Filtro precedente" raggiungono il termine della lista
#_help_misc_group_clones;
_help_misc_hide_brackets;Nasconde il testo tra parentesi quando viene mostrato il titolo del gioco
#_help_misc_hide_console;
#_help_misc_image_cache_mbytes;
_help_misc_language;Seleziona la lingua dell'interfaccia di Attract-Mode Plus
#_help_misc_layout_preview;
_help_misc_multiple_monitors;Abilita l'utilizzo di monitor multipli
#_help_misc_power_saving;
_help_misc_quick_menu;Imposta se i menu possono essere aperti e chiusi con lo stesso pulsante. Permette anche di passare da un menu all'altro senza doverli prima chiudere
#_help_misc_screen_rotation;
_help_misc_startup_mode;Configura come si deve comportare Attract-Mode Plus quando viene eseguito
_help_misc_track_usage;Configura se Attract-Mode Plus deve gestire le statistiche di utilizzo (tempo complessivo e numero di partite giocate per ciascun titolo)
_help_misc_ui_color;Seleziona il colore da utilizzare nell'interfaccia utente di Attract-Mode Plus
_help_misc_video_decoder;Configura il decoder da utilizzare per riprodurre i video (nel caso siano disponibili più decoder)
_help_misc_window_mode;Configura se il frontend deve lavorare a tutto schermo o essere eseguito in una finestra
_help_plugin_command;Eseguibile associato a questo plugin
_help_plugin_enabled;Configura se questo plugin è abilitato
#_help_plugin_name;
_help_plugin_sel;Configura i plugin
_help_rule_comp;Tipo di comparazione per questo filtro
_help_rule_delete;Cancellare questa regola
_help_rule_target;L'attributo del gioco sul quale basare il filtro
_help_rule_value;Espressione regolare con la quale filtrare. Per esempio, se l'obbiettivo del filtro è "Anno" e la comparazione è "Uguale", un valore di "1984" restituirà tutti i giochi prodotti nel 1984, mentre "198." restituirà tutti i giochi prodotti negli anni '80
_help_scraper_fanart;Stabilisce se le fanart devono essere recuperate dalla rete
_help_scraper_flyers;Stabilisce se i flyers e le copertine delle confezioni devono essere recuperate dalla rete
_help_scraper_marquees;Stabilisce se i marquee devono essere recuperati dalla rete
_help_scraper_snaps;Stabilisce se gli snapshot devono essere recuperati dalla rete
_help_scraper_vids;Stabilisce se i video devono essere recuperati dalla rete
_help_scraper_wheels;Stabilisce se i logo devono essere recuperati dalla rete
#_help_shortcut_artwork_name;
#_help_shortcut_delete;
#_help_shortcut_label;
#_help_shortcut_target;
#_help_sound_loudness_normalisation;
_help_sound_sel;Assegna un suono a questo evento/azione
_help_sound_volume;I valori consentiti per il volume vanno da 0 (silenzio) a 100 (massimo)

# -- extra --
XML Mode;Modo XML
Overlay Artwork;Overlay artwork
Play Sound;Esegui il suono
Ambient Sounds;Suono ambiente
Command;Comando
Image collage;Collezione di immagini
All;Tutto
Minutes;minuti
Basic Movie;Video base
Movie collage;Collezione di video
Minimum Run Time;Tempo minimo di esecuzione
Preserve Aspect Ratio;Rispetta le proporzioni
