#@日本語 (Japanese)

# -- generic --
$1 Rule(s);ルール $1 件
Blank Game;空白のゲーム
Custom;カスタム
Default;デフォルト
Disabled;無効
Empty;空
False;間違い
Multi;マルチ
No Sort;並び替えない
No;いいえ
None;0°
Off;オフ
On;オン
OR;又は
True;有効
Yes;はい
Import;輸入
Cancel;キャンセル

# -- misc --
Press TAB to Configure;TABキーを押して設定してください
Displays Menu Options;メニューオプションを表示しますか?
Action;アクション
Add Artwork;アートワークを追加
Add Emulator;エミュレータを追加
Add Exception;例外を追加
Add Filter;フィルターを追加
Add Input;キー追加
Add Display;ディスプレイを追加
Add Rule;ルールを追加
Allow Exit;終了を許可する
Anisotropic Filtering;異方性フィルタリング
Anti-Aliasing (MSAA);アンチエイリアシング (MSAA)
Artwork Label;アートワークのレーベル
Artwork Name;アートワーク名
Artwork Path;アートワークの位置
Auto-detect Emulators;エミュレータを自動検出
Check for Updates;アップデートを確認
Collection/Romlist;Romファイルリスト
Comparison;ルールの比較方式
Confirm Exit;終了を確認
Confirm Favourites;お気に入りの確認
Controls;入力
Add Tag;タグを追加
Custom Arguments;カスタム引数
Custom Executable;カスタム実行ファイル
Custom Overlay;カスタムオーバーレイ
Default Action;デフォルトアクション
Delete this Display;このディスプレイを削除
Delete this Emulator;エミュレータを削除
Delete this Filter;このフィルターを削除
Delete this Game;このゲームを削除
Delete this Rule;このルールを削除
Delete this Shortcut;このショートカットを削除しますか?
Displays;ディスプレイ
Emulator Name;エミュレータの名前
Emulators;エミュレータ
Multiple Monitors;複数のモニター
Enabled;使用する
Exception;例外
Exit Attract-Mode Plus;プログラムを終了
Exit Attract-Mode Plus?;終了しますか?
Exit Command;終了コマンド
Exit Message;終了メッセージ
Filter Name;フィルターの名前
Filter Value;フィルターの表現式
Filter Wrap Mode;リストの最後のフィルターに着いた時
Filter;フィルター
Settings;設定
Global Filter;グローバルフィルターの設定
Group Clones;グループクローン
Hide Game Title Brackets;ゲームタイトルの括弧を非表示にする
Format Game Title;ゲームタイトルのフォーマット
Hide Console;コンソールを非表示
Image Cache Size;画像キャッシュサイズ
Insert Command Shortcut;コマンドショートカットを挿入
Insert Display Shortcut;ディスプレイショートカットを挿入
Insert Game Entry;ゲームエントリを挿入
Insert Menu Entry;メニューエントリを挿入
Joystick $1;ジョイスティック$1
Joystick Mappings;ジョイスティックマッピング
Joystick Threshold;ジョイスティックの感度
Language;言語
Layout File;レイアウトファイル
Layout Preview;レイアウトのプレビュー
Layout;レイアウットの名前
List Limit;リストのサイズ限度
Menu Colour;メニューの色
Menu Prompt;メニュープロンプト
Menu Toggle;メニュー切り替え
Mouse Threshold;マウスの感度
Overview;概要
Plugins;プラグイン
Power Saving;省電力
Remove Input;キー削除
Reverse Order;逆順
Rule;ルール
Scrape Artwork;ファンアートーワークをダウンロード
Scrape Fanart;ファンアートをスクレイピング
Scrape Flyers/Boxart;箱のアートーワーク, ポスターをダウンロード
Scrape Game Logos (Wheel Art);ゲームロゴをダウンロード (Wheel Art)
Scrape Marquees;Marqueeをダウンロード
Scrape Snaps;スクリーンショットをダウンロード
Scrape Videos (MAME only);ビデオをスクレイピング (MAMEのみ)
Scraper;スクレーパー
Screen Rotation;画面の回転
Screen Saver Timeout;スクリーンセーバーのタイムアウト時間
Selection Delay;選択の遅延
Show in Cycle;サイクルで表示
Show in Menu;メニューに表示
Sort By;並び替え
Sort Only;並べ替えのみ
Sort and Show;並べ替えと表示
Sound;サウンド
Startup Mode;起動モード
Target;ルールのターゲット
Title;タイトル(Title)
Game Stats;ゲーム統計
Video Decoder;ビデオデコーダー
Window Mode;スクリーンモードー
Added $1 Collection/Romlist entries;$1 個のコレクション/ROMリストエントリを追加しました。

# -- indexStrings --
Name;名前
Title;タイトル(Title)
Emulator;エミュレータ
CloneOf;クローン(CloneOf)
Year;発売年(Year)
Manufacturer;発売元(Manufacturer)
Category;ジャンル(Category)
Players;プレイヤー数(Players)
Rotation;回転
Control;コントローラ(Control)
Status;ステータス
DisplayCount;ディスプレイの数(DisplayCount)
DisplayType;ディスプレイタイプ(DisplayType)
AltRomname;Romの別称(AltRomname)
AltTitle;タイトルの別称(AltTitle)
Extra;追加
Buttons;ボタン
Series;シリーズ
Language;言語
Region;地域
Rating;評価
Favourite;お気に入り
Tags;タッグ
PlayedCount;プレイ数
PlayedTime;プレイ時間
PlayedLast;前回のプレイ日時
FileIsAvailable;Romファイルの存在
Shuffle;シャッフル

# -- filterCompDisplayStrings --
contains;含む
does not contain;含まない
does not equal;一致しない
equals;一致する
greater than;より大きい
less than;より小さい
greater than or equal;より大きいか等しい
less than or equal;より小さいか等しい

# -- commandDispStrings --
Back;戻る
Up;上
Down;下
Left;270°
Right;90°
Select;選択
Previous Game;前のゲーム
Next Game;次のゲーム
Previous Page;前のページ
Next Page;次のページ
Previous Display;前のディスプレイ
Next Display;次のディスプレイ
Displays Menu;ディスプレイメニュー
Previous Filter;前のフィルター
Next Filter;次のフィルター
Filters Menu;フィルターメニュー
Toggle Layout;レイアウット選択
Toggle Movie;ムービー再生
Toggle Mute;ミュート
Toggle Rotate Right;画面 90°回転
Toggle Flip;画面 180°回転
Toggle Rotate Left;画面 270°回転
Exit;終了 (Yes/No 確認)
Exit to Desktop;終了
Reload Layout;レイアウトの再読み込み
Reload Config;設定を再読み込み
Reset Window;ウィンドウをリセット
Screenshot;スクリーンショット
Random Game;任意のゲーム選択
Replay Last Game;最後にプレイしたゲームを再プレイ
Toggle Fullscreen;全画面表示の切り替え
Add/Remove Favourite;お気に入り追加/削除
Previous Favourite;次のお気に入り
Next Favourite;前のお気に入り
Add/Remove Tags;タッグ追加/削除
Screen Saver;スクリーンセーバー
Previous Letter;前の文字
Next Letter;次の文字
Intro;イントロ
Insert Game;ゲームを挿入
Layout Options;レイアウト別設定
Plugin Options;プラグインオプション
Custom1;カスタム 1
Custom2;カスタム 2
Custom3;カスタム 3
Custom4;カスタム 4
Custom5;カスタム 5
Custom6;カスタム 6
Custom7;カスタム 7
Custom8;カスタム 8
Custom9;カスタム 9
Custom10;カスタム 10
Ambient Soundtrack;BGMファイル
Startup Sound;プログラム起動のサウンド
Game Return Sound;ゲーム終了のサウンド

# --uiColorDispTokens --
Indigo;藍
Blue;青
Cyan;シアン
Turquoise;ターコイズ
Green;緑
Acid;アシッド
Gold;ゴールド
Yellow;黄
Orange;オレンジ
Brown;茶
Rust;さび
Red;赤
Pink;ピンク
Magenta;マゼンタ
Purple;紫
Grey;灰色
Neutral;ニュートラル
White;白

# --windowModeDispTokens --
Fill Screen;全画面に広げる
Fullscreen;全画面表示
Window;ウィンドウモード
Borderless Window;ボーダーレスウィンドウ

# --screenRotationDispTokens --
Flip;180°

# --startupDispTokens --
Show Last Selection;前回の選択を表示
Show Random Selection;ランダム選択を表示
Launch Last Game;最後のゲームを起動
Show Displays Menu;ディスプレイメニューを表示

# --filterWrapDispTokens --
Wrap within Display;リストの最初のフィルターに
Jump to Next Display;次のリストに
No Wrap;何もしない

# -- settingDispStrings --
Sound Volume;サウンドボリューム
Ambient Volume;BGMボリューム
Movie Volume;ムービーボリューム
Loudness Normalisation;音量の正規化

# -- splash_message --
Generating Romlist;Romファイルリストを作成しています
Please Wait;お待ちください
Scraping Artwork;オンラインから をダウンロード中です

# -- confirm_dialog --
Add '$1' to Favourites?;「$1」をお気に入りに追加しますか?
Auto-detect emulators?;エミュレータを自動検出?
Found 1 emulator;エミュレータが1つ見つかりました
Found $1 emulators;エミュレータが$1つ見つかりました
No emulators found;エミュレータが見つかりません
+$1 more;+$1件以上
Clear Hotkey?;ホットキーをクリア?
Delete display '$1'?;ディスプレイ「$1」を削除してもよろしいですか?
Delete emulator '$1'?;「$1」エミュレータを削除しますか?
Delete filter '$1'?;「$1」フィルターを削除しますか?
Delete game '$1'?;ゲーム「$1」を削除しますか?
Delete shortcut '$1'?;ショートカット「$1」を削除しますか?
Overwrite existing '$1' list?;既存のRomファイルリスト「$1」に上書きしてもよろしいですか?
Remove '$1' from Favourites?;お気に入りから「$1」を削除?
Rom path '$1' not found, proceed?;ROMパス '$1' が見つかりません。続行しますか?
Overwrite existing '$1' mapping?;既存の '$1' マッピングを上書きしますか?
A display with this name already exists;この名前のディスプレイは既に存在します
Configuration files have been migrated\n to the 'config' folder.\nDelete old files?;設定ファイルが 'config' フォルダに移行されました。\n古いファイルを削除しますか？

# --input_map_dialog --
Press Hotkey;ホットキーを押す
Press Input;キーを押してください

# -- edit_dialog --
Enter Display Name;新しいディスプレイの名前を入力して下さい
Enter Emulator Name;エミュレータの名前を入力して下さい
Enter Filter Name;フィルターの名前を入れて下さい
Enter Tag Name;新しいタグ名を入力
Enter Romlist Name;ROMリスト名を入力

# -- Titles --
Configure;設定
Default Display Options;デフォルト表示オプション
Display Options;表示オプション
Artwork Options;アートワークオプション
Control Options;コントロールオプション
Emulator Options;エミュレータオプション
Game Options;ゲームオプション
Shortcut Options;ショートカットオプション
Exception Options;例外オプション
Filter Options;フィルターオプション
Rule Options;ルールオプション
Generate Collection/Romlist;Romファイルリストを作成

# --indexDispStrings --
Executable;実行ファイル
Command Arguments;実行パラメータ
Working Directory;作業ディレクトリ
Rom Path(s);Romファイルの位置
Rom Extension(s);Romファイルの拡張子
System Identifier;システムのID
Info Source/Scraper;情報元 設定
Additional Import File(s);追加入力ファイル
Non-Blocking Mode Wait;非ブロッキングモード待機
Exit Hotkey;終了ホットキー
Pause Hotkey;一時停止ホットキー

# -- datetime --
_datetime;%Y年%m月%d日 %H:%M:%S
A Moment Ago;少し前
Never;なし
$1 Second;$1秒
$1 Minute;$1分
$1 Hour;$1時間
$1 Day;$1日
$1 Minute Ago;$1分前
$1 Hour Ago;$1時間前
$1 Day Ago;$1日前
$1 Week Ago;$1週間前
$1 Month Ago;$1か月前
$1 Year Ago;$1年前
$1 Seconds;$1秒
$1 Minutes;$1分
$1 Hours;$1時間
$1 Days;$1日
$1 Minutes Ago;$1分前
$1 Hours Ago;$1時間前
$1 Days Ago;$1日前
$1 Weeks Ago;$1週間前
$1 Months Ago;$1か月前
$1 Years Ago;$1年前

# -- help --
_help_art_add;新しいアートワーク (スクリンショット, タイトル, ムービー) を追加します
_help_art_label;指定したレーベルがレイアウトに使われます
_help_art_path;アートワークの位置です
_help_art;レイアウトで使用できるアートワークリソース
_help_back;終了メニュー
_help_control_add_favourite;現在選択されたゲームをお気に入りに追加/削除するキーを設定します
_help_control_add_tags;現在選択されたゲームのタッグを編集するキーを設定します
_help_control_back;戻るためのコントロールを設定します
_help_control_configure;この '設定画面' を表示するキーを設定します
_help_control_custom1;カスタムキー1を設定します
_help_control_custom10;カスタムキー10を設定します
_help_control_custom2;カスタムキー2を設定します
_help_control_custom3;カスタムキー3を設定します
_help_control_custom4;カスタムキー4を設定します
_help_control_custom5;カスタムキー5を設定します
_help_control_custom6;カスタムキー6を設定します
_help_control_custom7;カスタムキー7を設定します
_help_control_custom8;カスタムキー8を設定します
_help_control_custom9;カスタムキー9を設定します
_help_control_displays_menu;'リストメニュー' を表示するキーを設定します
_help_control_down;下に移動するキーを設定します
_help_control_edit_game;現在の選択範囲を編集するコントロールを設定します
_help_control_exit_to_desktop;このプログラムを確認無しで終了するキーを設定します
_help_control_exit;このプログラムを終了するキーを設定します
_help_control_filters_menu;'フィルターメニュー' を表示するキーを設定します
_help_control_insert_game;新しいゲームエントリを挿入するコントロールを設定します
_help_control_intro;イントロビデオを表示するコントロールを設定します
_help_control_joystick_map;フロントエンドのジョイスティックスロットを、コンピューターに接続された特定の名前のジョイスティック/ゲームパッドデバイスにマッピングします (例えば、フロントエンドで「Microsoft X-Box 360 pad」をジョイスティック 0 として常に使用するように強制できます)。
_help_control_joystick_threshold;ジョイスティックの感度を設定します. (1から100まで), 高いほど鈍感です
_help_control_layout_options;「レイアウトオプション」メニューを表示するコントロールを設定します
_help_control_plugin_options;最後に表示したプラグインの「プラグインオプション」メニューを表示するコントロールを設定します
_help_control_left;選択範囲を左に移動するコントロールを設定します
_help_control_mouse_threshold;マウスの感度を設定します. (1から100まで), 高いほど鈍感です
_help_control_next_display;次のリストに移動するキーを設定します
_help_control_next_favourite;次のお気に入りゲームに移動するキーを設定します
_help_control_next_filter;次のフィルターに移動するキーを設定します
_help_control_next_game;次のゲームに移動するコントロールを設定します。
_help_control_next_letter;次のアルファベットに移動するキーを設定します
_help_control_next_page;選択範囲を1ページ上に移動するコントロールを設定します。
_help_control_prev_display;前のリストに移動するキーを設定します
_help_control_prev_favourite;前のお気に入りゲームに移動するキーを設定します
_help_control_prev_filter;前のフィルターに移動するキーを設定します
_help_control_prev_game;前のゲームに移動するコントロールを設定します
_help_control_prev_letter;前のアルファベットに移動するキーを設定します
_help_control_prev_page;選択範囲を1ページ下に移動するコントロールを設定します。
_help_control_random_game;任意のゲームを選択するキーを設定します
_help_control_reload_layout;現在のレイアウトを再読み込みするコントロールを設定します。
_help_control_reload_config;設定ファイルを再読み込みするコントロールを設定します
_help_control_reset_window;ウィンドウのサイズと位置をリセットするためのコントロールを設定します
_help_control_replay_last_game;最後にプレイしたゲームを再びプレイするキーを設定します
_help_control_right;選択範囲を右に移動するコントロールを設定します。
_help_control_screen_saver;スクリーンショットを起動するキーを設定します
_help_control_screenshot;スクリーンショットを撮るキーを設定します
_help_control_select;現在選択されたゲームをプレイするキーを設定します
_help_control_selection_delay;キーリピート開始までの遅延時間をミリ秒単位で設定します。デフォルトは400です。
_help_control_toggle_flip;画面を180°回転するキーを設定します
_help_control_toggle_fullscreen;ウィンドウモードをフルスクリーンとウィンドウの間で切り替えます。
_help_control_toggle_layout;レイアウットを変更するキーを設定します. (レイアウットにより無視される場合があります)
_help_control_toggle_movie;ムービーの再生をオン/オフにするキーを設定します
_help_control_toggle_mute;ミュートするキーを設定します
_help_control_toggle_rotate_left;画面を反時計回りに90°回転するキーを設定します
_help_control_toggle_rotate_right;画面を時計回りに90°回転するキーを設定します
_help_control_up;上に移動するキーを設定します
_help_display_add_filter;ディスプレイに新しいフィルターを追加します
_help_display_add;新しいディスプレイを追加します
_help_display_delete;このディスプレイを削除します
_help_display_filter;このディスプレイのフィルターを設定します
_help_display_global_filter;このリスト全体に適用するグローバルフィルターを設定します
_help_display_in_cycle;このディスプレイを「前のディスプレイ」/「次のディスプレイ」サイクルに含めますか
_help_display_in_menu;このディスプレイを「ディスプレイメニュー」に含めますか
_help_display_layout_options;レイアウトで指定されたオプションを設定できます
_help_display_layout;このディスプレイが使うレイアウットを設定します
_help_display_name;このディスプレイの名前です
_help_display_romlist;このディスプレイが使うRomファイルリストを設定します
_help_display_sel;このディスプレイを設定します
_help_display_edit_default;新しいディスプレイで使用するデフォルトオプションを設定します
_help_displaysmenu_exit;ディスプレイメニューに"プログラム終了"項目を追加するか設定します
_help_displaysmenu_layout;ディスプレイメニューで使用するレイアウトです。フロントエンドの組み込みメニューを使用する場合は「Default」に設定します
_help_displaysmenu_prompt;ディスプレイメニューのプロンプト (「システムを選択」など）
_help_displaysmenu;ディスプレイメニューのオプションを設定します
_help_emu_add;新しいエミュレータを登録します
_help_emu_args;エミュレータの実行パラメータを設定します. 以下のパラメータはその内容で置換されます : [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;エミュレータに関する設定を削除します
_help_emu_executable;エミュレータの実行ファイルの位置を指定します. $HOMEはユーザーのホームディレクトリに置換されます
_help_emu_exit_hotkey;このエミュレータを終了するグローバルホットキーを設定します. このホットキーを押せばこのエミュレータを強制終了できます.
_help_emu_gen_romlist;指定されたRomファイルの位置, XML モード, 追加ファイル (catver.ini 等) を使ってRomファイルリストを作成します
_help_emu_import_extras;Romファイルリストの作成時に追加で使うファイルを指定します. ジャンル (catver.ini), またはプレイ人数 (nplayers.ini) などを使えます
_help_emu_info_source;mess : MAME タイプの -listxml, mess : MESS タイプの -listsoftware, thegamesdb.net : このサイトを使う, steam : steamサイトを使う. mess, thegamesdb.net の場合IDを正しく設定する必要があります.
_help_emu_name;エミュレータを編集
_help_emu_nb_mode_wait;最小の実行時間を秒単位で設定します. 普通は0で構わないですが,一部のゲーム(steam等)には適当に設定する必要があります
_help_emu_pause_hotkey;エミュレータを一時停止するためのグローバルホットキーを設定します。このボタンを押すと、Attract-Mode Plus はエミュレータプロセスを一時停止し、フロントエンドに戻ります。エミュレータプロセスは、フロントエンドで同じゲームを再度選択することで再開できます。
_help_emu_romext;Romファイルの拡張子(.zip 等)を指定します. セミコロン(
_help_emu_rompath;エミュレータのRomファイルの位置を指定します
_help_emu_scrape_artwork;TheGamesDB.net または mamedb.com からゲームの情報をダウンロードします
_help_emu_sel_auto_detect;親フォルダをスキャンして既知のエミュレータを検索し、見つかったすべてのエミュレータのデフォルト設定を生成します
_help_emu_sel_gen_romlist;複数のエミュレータ用のゲームを含むコレクション/ROMリストを生成します
_help_emu_sel;エミュレータの設定を変更します
_help_emu_system;このエミュレータのIDです. セミコロン(
_help_emu_workdir;このエミュレータの作業ディレクトリ。フロントエンドがエミュレータを実行するディレクトリです。また、相対ROMパス、アートワークパス、その他のインポートファイルパスはすべて、このディレクトリからの相対パスとして扱われます
_help_filter_add_exception;このフィルターに例外を追加します。ゲームが例外に一致し (かつ以前のルールで除外されていない場合)、フィルターにリストされます
_help_filter_add_rule;このフィルターに新しいルールを追加します
_help_filter_delete;このフィルターを削除します
_help_filter_exception;このフィルター例外を構成します。ゲームが例外に一致する場合、フィルターにリストされます。ルールと例外は、リストされている順序で適用されます。
_help_filter_list_limit;リストのサイズに制限を付けます. プラスで上からの××個, マイナスで下からの××個を設定します. 0 は無限です.
_help_filter_name;フィルターの名前
_help_filter_reverse_order;ソートされたコレクション/ROMリストの順序を反転します。デフォルトの順序は、情報の場合は「AからZ」、統計情報の場合は「最大から最小」、または「ソートなし」の場合はソースリストの順序です。
_help_filter_rule;フィルターのルールを設定します
_help_filter_sort_by;リストの並び方を設定します. "並び替えない" で元の順番で並べます.
_help_game_custom_args;このゲームのデフォルトのコマンドライン引数をオーバーライドするには、これを設定します。パラメータなしでオーバーライドする場合は、[nothing] に設定します。以下の項目は適切に置換されます: [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_game_custom_executable;このゲームのデフォルトの実行ファイルを上書きするには、これを設定します
_help_game_delete;このゲームをRomリストから削除します
_help_game_edit;このゲーム情報を編集します
_help_game_overview;ゲームの概要を編集します
_help_generator_build;選択したエミュレータで romlist を生成します
_help_generator_opt;このエミュレータを生成される ROM リストに含めるかどうかを設定します
_help_input_action;
_help_input_add;入力キーを追加します
_help_input_default_action;このコントロールのデフォルトの動作を設定します
_help_input_delete;入力キーを削除します
_help_layout_file;レイアウトによっては、複数のlayout*.nutファイルが用意されています。使用するレイアウトファイルを選択してください
_help_layout_name;レイアウトの設定
_help_main_control;様々な入力を設定します
_help_main_display;ディスプレイ(ゲームリスト)を設定します
_help_main_emu;エミュレータオプションを設定します
_help_main_intro;導入オプションを設定します
_help_main_settings;一般オプションを設定します
_help_main_plugin;プラグインオプションを設定します
_help_main_scraper;スクレーパーオプションを設定します
_help_main_screensaver_timeout;何秒まで入力が無ければスクリーンセーバーを起動するかを設定します. 0 でスクリーンセーバーをオフにします
_help_main_screensaver;スクリーンセーバーを設定します
_help_main_sound;効果音, 背景音楽, ボリューム等を設定します
_help_misc_anisotropic_filtering;テクスチャの異方性フィルタリングレベルを設定します。これにより、スケーリングされたテクスチャの品質が向上します
_help_misc_antialiasing;アンチエイリアシングのレベルを設定します
_help_misc_check_for_updates;Attract-Mode Plus が起動時に利用可能なアップデートをチェックし、新しいバージョンが見つかった場合にアップデート通知ダイアログを表示するかどうかを設定します
_help_misc_confirm_exit;Attract-Mode Plusの終了を確認します
_help_misc_confirm_favs;お気に入りのゲームを追加,削除する時, Yes/Noで確認するかを設定します
_help_misc_custom_overlay;レイアウトで、表示、フィルター、タグ、終了メニューで使用するオーバーレイをカスタマイズできるようにします
_help_misc_exit_command;終了 (Yes/No 確認) でプログラムを終了する時に実行する外部コマンドを設定します (例. "sudo shutdown")
_help_misc_exit_message;フロントエンドを終了するための代替メッセージ (例： 「システムをシャットダウン」
_help_misc_filter_wrap_mode;リストの最後のフィルターで"次のフィルター"が押された時, どのように反応するかを設定します.
_help_misc_group_clones;ゲームのクローンをすべて1つのリストエントリにグループ化します。
_help_misc_hide_brackets;ゲームのタイトルを表示する時, ブラケットに囲まれた部分は隠すかを設定します
_help_misc_prefix_modes;「The」と「Vs.」を移動しますゲームタイトルの末尾にプレフィックスを付けます
_help_misc_hide_console;起動時にコンソールを非表示にします。これは、Attract-Mode PlusをWindows GUIから起動した場合にのみ機能します。既存のコンソールウィンドウ (例：バッチファイル) から開始された場合、プロセスは常に既存のコンソールに「アタッチ」され、そこに出力されます。
_help_misc_image_cache_mbytes;Attract-Mode Plus の内部イメージキャッシュの最大サイズ (MB単位) を設定します
_help_misc_language;言語を設定します
_help_misc_layout_preview;レイアウト設定の変更をすぐに表示します
_help_misc_multiple_monitors;Attract-Mode Plus でマルチモニターの使用を有効にします。これを「いいえ」に設定すると、ゲーム起動時の画面のちらつきが軽減される可能性があります
_help_misc_power_saving;必要な場合にのみ画面を再描画することで電力を節約します。一部のレイアウトではアニメーションが途切れたり、Linux ではフリーズしたりする可能性があります
_help_misc_quick_menu;同じボタンでメニューを開いたり閉じたりできるかどうかを設定します。また、メニューを閉じなくてもメニューを切り替えることができます
_help_misc_screen_rotation;画面の基本回転を設定します。
_help_misc_startup_mode;Attract-Mode Plus の初回起動時の動作を設定します
_help_misc_track_usage;ゲームのプレイ内容(プレイ数,プレイ時間)を記録するかを設定します.
_help_misc_ui_color;Attract-Mode Plus のユーザーインターフェースで使用する色を選択します
_help_misc_video_decoder;ビデオ再生に使用するデコーダーを設定します (複数のデコーダーが利用可能な場合)
_help_misc_window_mode;.Attract-Mode Plus がウィンドウモードで起動するかフルスクリーンモードで起動するかを設定します
_help_plugin_command;プラグインのコマンドを設定します
_help_plugin_enabled;プラグインを使うかを設定します
_help_plugin_name;プラグインの設定
_help_plugin_sel;プラグインを設定します
_help_rule_comp;フィルターのルールを比較する方式を設定します
_help_rule_delete;このルールを削除します
_help_rule_target;フィルターが使うゲームのカテゴリーを設定します
_help_rule_value;フィルターのルールを正規表現で設定します. 例えばターゲットが"発売年"で,比較方式が"一致する"で,表現式が"1984"の場合,1984年に発売されたゲームのみ表示されます．"198."の場合 1980年代の全てのゲームが表示されます.　"(198.)|(199.)"の場合1980年代と1990年代の全てのゲームを表示します
_help_scraper_fanart;オンラインからファンアートーワークをダウンロードするかを設定します
_help_scraper_flyers;オンラインから箱のアートーワーク, ポスターをダウンロードするかを設定します
_help_scraper_marquees;オンラインからMarqueeをダウンロードするかを設定します
_help_scraper_snaps;オンラインからスクリーンショットをダウンロードするかを設定します
_help_scraper_vids;スクレイピング時にゲームビデオをダウンロードするかどうかを設定します
_help_scraper_wheels;オンラインからWheel Artタイプのゲームロゴをダウンロードするかを設定します
_help_shortcut_artwork_name;このショートカットに関連付けるアートワーク名を任意で指定します。フロントエンドはショートカットを表示するときに、この名前のアートワークを読み込もうとします
_help_shortcut_delete;このショートカットをROMリストから削除します
_help_shortcut_label;このショートカットのラベルを編集します
_help_shortcut_target;このショートカットのターゲットを編集します
_help_sound_loudness_normalisation;静かなメディアを自動的に一定の音量に増幅するオーディオ効果を有効にします
_help_sound_sel;この状態でプレイするサウンドを設定します
_help_sound_volume;このオーディオソースの音量を設定します

# -- screensaver --

Basic Movie;基本ムービー
Movie Collage;ムービーコラージュ
Image Collage;画像コラージュ
RGB Movie;RGBムービー
Overlay Artwork;オーバーレイアートワーク
Play Sound;サウンド再生
Preserve Aspect Ratio;アスペクト比維持
Blank Screen Time;ブランクスクリーン時間
Blank Screen Start Command;ブランクスクリーン開始コマンド
Blank Screen Stop Command;ブランクスクリーン停止コマンド
Play intro;イントロを再生
Detect aspect ratio;アスペクト比を検出
Default video;デフォルトのビデオ
16:9 video;16:9 ビデオ
4:3 video;4:3 ビデオ
9:16 video;9:16 ビデオ
3:4 video;3:4 ビデオ

# -- extra --
