#@日本語 (Japanese)

# -- generic --
#$1 Rule(s);
#Blank Game;
#Custom;
#Default;
Disabled;無効
#Empty;
#False;
#Multi;
No Sort;並び替えない
No;いいえ
None;0°
#Off;
#On;
OR;又は
#True;
Yes;はい

# -- misc --
#'Displays Menu' Options;
Action;アクション
Add Artwork;アートワークを追加
Add Emulator;エミュレータを追加
#Add Exception;
Add Filter;フィルターを追加
Add Input;キー追加
Add New Display;ディスプレイを追加
Add Rule;ルールを追加
Allow Exit from 'Displays Menu';ディスプレイメニューからのプログラム終了可能
#Anisotropic Filtering;
#Anti-Aliasing;
Artwork Label;アートワークのレーベル
#Artwork Name;
Artwork Path;アートワークの位置
#Auto-detect Emulators;
#Check for Updates;
Collection/Rom List;Romファイルリスト
Comparison;ルールの比較方式
#Confirm Exit;
Confirm Favourites;お気に入りの確認
Controls;入力
#Create new tag;
#Custom Arguments;
#Custom Executable;
#Default Action;
Delete this Display;このディスプレイを削除
Delete this Emulator;エミュレータを削除
Delete this Filter;このフィルターを削除
#Delete this Game;
Delete this Rule;このルールを削除
#Delete this Shortcut;
Displays;ディスプレイ
Emulator Name;エミュレータの名前
Emulators;エミュレータ
#Enable Multiple Monitors;
Enabled;使用する
#Exception;
Exit Attract-Mode;プログラムを終了
Exit Attract-Mode?;終了しますか?
Exit Command;終了コマンド
#Exit Message;
Filter Name;フィルターの名前
Filter Value;フィルターの表現式
Filter Wrap Mode;リストの最後のフィルターに着いた時
Filter;フィルター
General;その他
Global Filter;グローバルフィルターの設定
#Group Clones;
Hide Brackets in Game Title;ゲームタイトルのブラケットを隠す
#Hide Console;
#Image Cache Size;
#Insert Command Shortcut;
#Insert Display Shortcut;
#Insert Game Entry;
#Insert Menu Entry;
#Joystick $1;
#Joystick Mappings;
Joystick Threshold;ジョイスティックの感度
Language;言語
#Layout File;
Layout Options;レイアウト別設定
Layout Preview;レイアウトのプレビュー
Layout;レイアウットの名前
List Limit;リストのサイズ限度
Menu Colour;メニューの色
#Menu Prompt;
#Menu Toggle;
Mouse Threshold;マウスの感度
#Overview;
Plug-ins;プラグイン
#Power Saving;
Remove Input;キー削除
#Reverse Order;
Rule;ルール
Scrape Artwork;ファンアートーワークをダウンロード
#Scrape Fanart;
Scrape Flyers/Boxart;箱のアートーワーク, ポスターをダウンロード
Scrape Game Logos (Wheel Art);ゲームロゴをダウンロード (Wheel Art)
Scrape Marquees;Marqueeをダウンロード
Scrape Snaps;スクリーンショットをダウンロード
#Scrape Videos (MAME only);
Scraper;オンラインゲーム情報出典
#Screen Rotation;
Screen Saver Timeout;スクリーンセーバーのタイムアウト時間
#Select template to use for emulator settings;
#Show in Cycle;
#Show in Menu;
Sort By;並び替え
Sound;サウンド
#Startup Mode;
Target;ルールのターゲット
Title;タイトル(Title)
Track Usage;プレイ時間記録
#Video Decoder;
Window Mode;スクリーンモードー
Wrote $1 entries to Collection/Rom List;$1 個のRomファイルをリストに記録しました

# -- indexStrings --
Name;名前
Title;タイトル(Title)
Emulator;エミュレータ(Emulator)
CloneOf;クローン(CloneOf)
Year;発売年(Year)
Manufacturer;発売元(Manufacturer)
Category;ジャンル(Category)
Players;プレイヤー数(Players)
Rotation;ディスプレイ回転(Rotation)
Control;コントローラ(Control)
Status;エミュレーションレベル(Status)
DisplayCount;ディスプレイの数(DisplayCount)
DisplayType;ディスプレイタイプ(DisplayType)
AltRomname;Romの別称(AltRomname)
AltTitle;タイトルの別称(AltTitle)
Extra;その他(Extra)
#Buttons;
#Series;
Language;言語
#Region;
#Rating;
Favourite;お気に入り
Tags;タッグ
PlayedCount;プレイ数
PlayedTime;プレイ時間
#PlayedLast;
FileIsAvailable;Romファイルの存在
#Shuffle;

# -- filterCompDisplayStrings --
contains;含む
does not contain;含まない
does not equal;一致しない
equals;一致する

# -- commandDispStrings --
Back;戻る
Up;上
Down;下
Left;270°
Right;90°
Select;選択
#Previous Game;
#Next Game;
#Previous Page;
#Next Page;
Previous Display;前のディスプレイ
Next Display;次のディスプレイ
Displays Menu;ディスプレイメニュー
Previous Filter;前のフィルター
Next Filter;次のフィルター
Filters Menu;フィルターメニュー
Toggle Layout;レイアウット選択
Toggle Movie;ムービー再生
Toggle Mute;ミュート
Toggle Rotate Right;画面 90°回転
Toggle Flip;画面 180°回転
Toggle Rotate Left;画面 270°回転
Exit;終了 (Yes/No 確認)
Exit to Desktop;終了
Reload;リロード
Screenshot;スクリーンショット
Random Game;任意のゲーム選択
Replay Last Game;最後にプレイしたゲームを再プレイ
Add/Remove Favourite;お気に入り追加/削除
Previous Favourite;次のお気に入り
Next Favourite;前のお気に入り
Add/Remove Tags;タッグ追加/削除
Screen Saver;スクリーンセーバー
Previous Letter;前の文字
Next Letter;次の文字
Intro;イントロ
#Insert Game;
Layout Options;レイアウト別設定
Custom1;カスタム 1
Custom2;カスタム 2
Custom3;カスタム 3
Custom4;カスタム 4
Custom5;カスタム 5
Custom6;カスタム 6
Custom7;カスタム 7
Custom8;カスタム 8
Custom9;カスタム 9
Custom10;カスタム 10
Ambient Soundtrack;BGMファイル
Startup Sound;プログラム起動のサウンド
Game Return Sound;ゲーム終了のサウンド

# --uiColorDispTokens --
#Indigo;
#Blue;
#Cyan;
#Turquoise;
#Green;
#Acid;
#Gold;
#Yellow;
#Orange;
#Brown;
#Rust;
#Red;
#Pink;
#Magenta;
#Purple;
#Grey;
#Neutral;
#White;

# --windowModeDispTokens --
Fill Screen;全画面に広げる
Fullscreen Mode;全画面モード
Window;ウィンドウモード
#Window (No Border);

# --screenRotationDispTokens --
Flip;180°

# --startupDispTokens --
#Show Last Selection;
#Launch Last Game;
#Show Displays Menu;

# --filterWrapDispTokens --
Wrap within Display;リストの最初のフィルターに
Jump to Next Display;次のリストに
No Wrap;何もしない

# -- antialiasingDispTokens --
#MSAA x2;
#MSAA x4;
#MSAA x8;

# -- FeSettings::anisotropicDispTokens --
#x2;
#x4;
#x8;
#x16;

# -- settingDispStrings --
Sound Volume;サウンドボリューム
Ambient Volume;BGMボリューム
Movie Volume;ムービーボリューム
#Loudness Normalisation;

# -- splash_message --
#Generating index ($1%);
Generating Rom List: $1%;Romファイルリストを作成しています: $1%
#Please Wait;
Scraping Artwork: $1%;オンラインから $1% をダウンロード中です

# -- confirm_dialog --
#Add '$1' to Favourites?;
#Attract-Mode detected emulator(s) that can be imported automatically.  Import them now?;
#Auto-detect emulators?;
#Clear Hotkey?;
Delete display '$1'?;ディスプレイ '$1' を削除してもよろしいですか？
Delete emulator '$1'?;'$1' エミュレータを削除しますか?
Delete filter '$1'?;'$1' フィルターを削除しますか？
#Delete game '$1'?;
#Delete shortcut '$1'?;
Overwrite existing '$1' list?;既存のRomファイルリスト '$1' に上書きしてもよろしいですか?
#Remove '$1' from Favourites?;
Rom path '$1' not found, proceed anyways?;Romファイル経路 '$1' が存在しません. 続きますか?
This will overwrite an existing mapping ($1).  Proceed?;既存の入力 ($1) を上書きしてもよろしいですか？

# --input_map_dialog --
#Press Hotkey;
Press Input;キーを押してください

# -- edit_dialog --
Enter Display Name;新しいディスプレイの名前を入力して下さい
Enter Emulator Name;エミュレータの名前を入力して下さい
Enter Filter Name;フィルターの名前を入れて下さい
#Enter new tag name;
#Enter Romlist Name;

# -- Titles --
#_submenu;
#Configure Layout;
Configure Plug-in;プラグインを設定
Configure;設定
Display Edit;ディスプレイを設定
Edit Artwork;アートワークを編集
#Edit Control;
Edit Emulator;エミュレータを編集
#Edit Game;
#Edit Shortcut;
#Exception Edit;
Filter Edit;フィルターを編集
Generate Collection/Rom List;Romファイルリストを作成
Rule Edit;ルール編集

# --indexDispStrings --
Executable;実行ファイル
Command Arguments;実行パラメータ
#Working Directory;
Rom Path(s);Romファイルの位置
Rom Extension(s);Romファイルの拡張子
System Identifier;システムのID
Info Source/Scraper;情報元 設定
Additional Import File(s);追加入力ファイル
#Non-Blocking Mode Wait;
Exit Hotkey;終了ホットキー
#Pause Hotkey;

# -- datetime --
#_datetime;
#A Moment Ago;
#Never;
#$1 Second;
#$1 Minute;
#$1 Hour;
#$1 Day;
#$1 Minute Ago;
#$1 Hour Ago;
#$1 Day Ago;
#$1 Week Ago;
#$1 Month Ago;
#$1 Year Ago;
#$1 Seconds;
#$1 Minutes;
#$1 Hours;
#$1 Days;
#$1 Minutes Ago;
#$1 Hours Ago;
#$1 Days Ago;
#$1 Weeks Ago;
#$1 Months Ago;
#$1 Years Ago;

# -- help --
_help_art_add;新しいアートワーク (スクリンショット, タイトル, ムービー) を追加します
_help_art_label;指定したレーベルがレイアウトに使われます
_help_art_path;アートワークの位置です
#_help_art;
#_help_back;
_help_control_add_favourite;現在選択されたゲームをお気に入りに追加/削除するキーを設定します
_help_control_add_tags;現在選択されたゲームのタッグを編集するキーを設定します
#_help_control_back;
_help_control_configure;この '設定画面' を表示するキーを設定します
_help_control_custom1;カスタムキー1を設定します
_help_control_custom10;カスタムキー10を設定します
_help_control_custom2;カスタムキー2を設定します
#_help_control_custom3;
#_help_control_custom4;
#_help_control_custom5;
#_help_control_custom6;
_help_control_custom7;カスタムキー7を設定します
_help_control_custom8;カスタムキー8を設定します
_help_control_custom9;カスタムキー9を設定します
_help_control_displays_menu;'リストメニュー' を表示するキーを設定します
_help_control_down;下に移動するキーを設定します
#_help_control_edit_game;
_help_control_exit_to_desktop;このプログラムを確認無しで終了するキーを設定します
_help_control_exit;このプログラムを終了するキーを設定します
_help_control_filters_menu;'フィルターメニュー' を表示するキーを設定します
#_help_control_insert_game;
#_help_control_intro;
#_help_control_joystick_map;
_help_control_joystick_threshold;ジョイスティックの感度を設定します. (1から100まで), 高いほど鈍感です
#_help_control_layout_options;
#_help_control_left;
_help_control_mouse_threshold;マウスの感度を設定します. (1から100まで), 高いほど鈍感です
_help_control_next_display;次のリストに移動するキーを設定します
_help_control_next_favourite;次のお気に入りゲームに移動するキーを設定します
_help_control_next_filter;次のフィルターに移動するキーを設定します
#_help_control_next_game;
_help_control_next_letter;次のアルファベットに移動するキーを設定します
#_help_control_next_page;
_help_control_prev_display;前のリストに移動するキーを設定します
_help_control_prev_favourite;前のお気に入りゲームに移動するキーを設定します
_help_control_prev_filter;前のフィルターに移動するキーを設定します
#_help_control_prev_game;
_help_control_prev_letter;前のアルファベットに移動するキーを設定します
#_help_control_prev_page;
_help_control_random_game;任意のゲームを選択するキーを設定します
_help_control_reload;現在のレイアウトを再ロードするコントロールを設定します
_help_control_replay_last_game;最後にプレイしたゲームを再びプレイするキーを設定します
#_help_control_right;
_help_control_screen_saver;スクリーンショットを起動するキーを設定します
_help_control_screenshot;スクリーンショットを撮るキーを設定します
_help_control_select;現在選択されたゲームをプレイするキーを設定します
_help_control_toggle_flip;画面を180°回転するキーを設定します
_help_control_toggle_layout;レイアウットを変更するキーを設定します. (レイアウットにより無視される場合があります)
_help_control_toggle_movie;ムービーの再生をオン/オフにするキーを設定します
_help_control_toggle_mute;ミュートするキーを設定します
_help_control_toggle_rotate_left;画面を反時計回りに90°回転するキーを設定します
_help_control_toggle_rotate_right;画面を時計回りに90°回転するキーを設定します
_help_control_up;上に移動するキーを設定します
_help_display_add_filter;ディスプレイに新しいフィルターを追加します
_help_display_add;新しいディスプレイを追加します
_help_display_delete;このディスプレイを削除します
_help_display_filter;このディスプレイのフィルターを設定します
_help_display_global_filter;このリスト全体に適用するグローバルフィルターを設定します
#_help_display_in_cycle;
#_help_display_in_menu;
_help_display_layout_options;レイアウトで指定されたオプションを設定できます
_help_display_layout;このディスプレイが使うレイアウットを設定します
_help_display_name;このディスプレイの名前です
_help_display_romlist;このディスプレイが使うRomファイルリストを設定します
_help_display_sel;このディスプレイを設定します
_help_displaysmenu_exit;ディスプレイメニューに"プログラム終了"項目を追加するか設定します
#_help_displaysmenu_layout;
#_help_displaysmenu_prompt;
#_help_displaysmenu;
_help_emu_add;新しいエミュレータを登録します
_help_emu_args;エミュレータの実行パラメータを設定します. 以下のパラメータはその内容で置換されます : [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;エミュレータに関する設定を削除します
_help_emu_executable;エミュレータの実行ファイルの位置を指定します. $HOMEはユーザーのホームディレクトリに置換されます
_help_emu_exit_hotkey;このエミュレータを終了するグローバルホットキーを設定します. このホットキーを押せばこのエミュレータを強制終了できます.
_help_emu_gen_romlist;指定されたRomファイルの位置, XML モード, 追加ファイル (catver.ini 等) を使ってRomファイルリストを作成します
_help_emu_import_extras;Romファイルリストの作成時に追加で使うファイルを指定します. ジャンル (catver.ini), またはプレイ人数 (nplayers.ini) などを使えます
_help_emu_info_source;mess : MAME タイプの -listxml, mess : MESS タイプの -listsoftware, thegamesdb.net : このサイトを使う, steam : steamサイトを使う. mess, thegamesdb.net の場合IDを正しく設定する必要があります.
#_help_emu_name;
_help_emu_nb_mode_wait; 最小の実行時間を秒単位で設定します. 普通は0で構わないですが,一部のゲーム(steam等)には適当に設定する必要があります
#_help_emu_pause_hotkey;
_help_emu_romext;Romファイルの拡張子(.zip 等)を指定します. セミコロン(
_help_emu_rompath;エミュレータのRomファイルの位置を指定します
_help_emu_scrape_artwork;TheGamesDB.net または mamedb.com からゲームの情報をダウンロードします
#_help_emu_sel_auto_detect;
#_help_emu_sel_gen_romlist;
_help_emu_sel;エミュレータの設定を変更します
_help_emu_system;このエミュレータのIDです. セミコロン(
#_help_emu_workdir;
#_help_filter_add_exception;
_help_filter_add_rule;このフィルターに新しいルールを追加します
_help_filter_delete;このフィルターを削除します
#_help_filter_exception;
_help_filter_list_limit;リストのサイズに制限を付けます. プラスで上からの××個, マイナスで下からの××個を設定します. 0 は無限です.
_help_filter_name;フィルターの名前
#_help_filter_reverse_order;
_help_filter_rule;フィルターのルールを設定します
_help_filter_sort_by;リストの並び方を設定します. "並び替えない" で元の順番で並べます.
#_help_game_custom_args;
#_help_game_custom_executable;
#_help_game_delete;
#_help_game_edit;
#_help_game_overview;
#_help_generator_build;
#_help_generator_opt;
_help_input_action;
_help_input_add;入力キーを追加します
#_help_input_default_action;
_help_input_delete;入力キーを削除します
#_help_layout_file;
#_help_layout_name;
_help_main_control;様々な入力を設定します
_help_main_display;ディスプレイ(ゲームリスト)を設定します
_help_main_emu;エミュレータを設定します
#_help_main_intro;
_help_main_misc;その他を設定します
_help_main_plugin;外部プラグインを設定します
_help_main_scraper;ゲームの情報を担当するオンラインサイトを設定します
_help_main_screensaver_timeout;何秒まで入力が無ければスクリーンセーバーを起動するかを設定します. 0 でスクリーンセーバーをオフにします
_help_main_screensaver;スクリーンセーバーを設定します
_help_main_sound;効果音, 背景音楽, ボリューム等を設定します
#_help_misc_anisotropic_filtering;
#_help_misc_antialiasing;
#_help_misc_check_for_updates;
_help_misc_confirm_exit;Confirm before exiting Attract-Mode?
_help_misc_confirm_favs;お気に入りのゲームを追加,削除する時, Yes/Noで確認するかを設定します
_help_misc_exit_command;終了 (Yes/No 確認) でプログラムを終了する時に実行する外部コマンドを設定します (例. "sudo shutdown")
#_help_misc_exit_message;
_help_misc_filter_wrap_mode;リストの最後のフィルターで"次のフィルター"が押された時, どのように反応するかを設定します.
#_help_misc_group_clones;
_help_misc_hide_brackets;ゲームのタイトルを表示する時, ブラケットに囲まれた部分は隠すかを設定します
#_help_misc_hide_console;
#_help_misc_image_cache_mbytes;
_help_misc_language;言語を設定します
#_help_misc_layout_preview;
#_help_misc_multiple_monitors;
#_help_misc_power_saving;
_help_misc_quick_menu;同じボタンでメニューを開いたり閉じたりできるかどうかを設定します。また、メニューを閉じなくてもメニューを切り替えることができます
#_help_misc_screen_rotation;
#_help_misc_startup_mode;
_help_misc_track_usage;ゲームのプレイ内容(プレイ数,プレイ時間)を記録するかを設定します.
#_help_misc_ui_color;
#_help_misc_video_decoder;
_help_misc_window_mode;.Attract-Mode がウィンドウモードで起動するかフルスクリーンモードで起動するかを設定します
_help_plugin_command;プラグインのコマンドを設定します
_help_plugin_enabled;プラグインを使うかを設定します
#_help_plugin_name;
_help_plugin_sel;プラグインを設定します
_help_rule_comp;フィルターのルールを比較する方式を設定します
_help_rule_delete;このルールを削除します
_help_rule_target;フィルターが使うゲームのカテゴリーを設定します
_help_rule_value;フィルターのルールを正規表現で設定します. 例えばターゲットが"発売年"で,比較方式が"一致する"で,表現式が"1984"の場合,1984年に発売されたゲームのみ表示されます．"198."の場合 1980年代の全てのゲームが表示されます.　"(198.)|(199.)"の場合1980年代と1990年代の全てのゲームを表示します
_help_scraper_fanart;オンラインからファンアートーワークをダウンロードするかを設定します
_help_scraper_flyers;オンラインから箱のアートーワーク, ポスターをダウンロードするかを設定します
_help_scraper_marquees;オンラインからMarqueeをダウンロードするかを設定します
_help_scraper_snaps;オンラインからスクリーンショットをダウンロードするかを設定します
#_help_scraper_vids;
_help_scraper_wheels;オンラインからWheel Artタイプのゲームロゴをダウンロードするかを設定します
#_help_shortcut_artwork_name;
#_help_shortcut_delete;
#_help_shortcut_label;
#_help_shortcut_target;
#_help_sound_loudness_normalisation;
_help_sound_sel;この状態でプレイするサウンドを設定します
_help_sound_volume;ボリュームを設定します(0から100まで), 0はミュートです

# -- extra --
XML Mode;XML モード
Ambient Sounds;BGMファイル
Command;コマンド
All;全て
Minimum Run Time;最小実行時間
