#@한국어 (Korean)

# -- generic --
$1 Rule(s);$1 규칙
Blank Game;빈 게임
Custom;사용자 지정
Default;기본값
Disabled;비활성
Empty;(없음)
False;거짓
Multi;다중
No Sort;정렬 안 함
No;아니요
None;0도
Off;끄기
On;켜기
OR;또는
True;참
Yes;예
Import;수입
Cancel;취소

# -- misc --
Press TAB to Configure;TAB을 눌러 구성하세요
Displays Menu Options;메뉴 옵션 표시
Action;동작
Add Artwork;동영상/그림 추가
Add Emulator;새 에뮬레이터 등록
Add Exception;예외 추가
Add Filter;필터 추가
Add Input;입력 추가
Add Display;디스플레이 추가
Add Rule;규칙 추가
Allow Exit;종료 허용
Anisotropic Filtering;이방성 필터링
Anti-Aliasing (MSAA);앤티앨리어싱 (MSAA)
Artwork Label;아트워크 라벨
Artwork Name;이트워크 이름
Artwork Path;아트워크 경로
Auto-detect Emulators;에뮬레이터 자동 감지
Check for Updates;업데이트 확인
Collection/Romlist;롬 목록 파일
Comparison;비교 조건
Confirm Exit;종료 확인
Confirm Favourites;즐겨하는 게임 확인 창 표시
Controls;입력
Add Tag;태그 추가
Custom Arguments;사용자 정의 매개변수
Custom Executable;사용자 정의 실행 파일
Custom Overlay;사용자 지정 오버레이
Default Action;기본 행동
Delete this Display;목록 삭제
Delete this Emulator;에뮬레이터 삭제
Delete this Filter;필터 삭제
Delete this Game;게임 삭제
Delete this Rule;규칙 삭제
Delete this Shortcut;바로가기 삭제
Displays;목록
Emulator Name;에뮬레이터 이름
Emulators;에뮬레이터
Multiple Monitors;여러 대의 모니터
Enabled;활성화 여부
Exception;예외
Exit Attract-Mode Plus;프로그램 종료
Exit Attract-Mode Plus?;종료하시겠습니까?
Exit Command;종료 명령어
Exit Message;종료 메시지
Filter Name;필터 이름
Filter Value;필터 값
Filter Wrap Mode;목록의 마지막 필터에 도달하였을 때
Filter;필터
Settings;설정
Global Filter;전역 필터 설정
Group Clones;그룹 클론
Hide Game Title Brackets;게임 제목 대괄호 숨기기
Format Game Title;게임 제목 형식
Hide Console;콘솔 숨기기
Image Cache Size;이미지 캐시 크기
Insert Command Shortcut;명령어 바로가기 추가
Insert Display Shortcut;창 바로가기 추가
Insert Game Entry;게임 추가
Insert Menu Entry;메뉴 추가
Joystick $1;조이스틱 $1
Joystick Mappings;조이스틱 매핑
Joystick Threshold;조이스틱 민감도
Language;언어 설정
Layout File;레이아웃 파일
Layout Preview;레이아웃 미리보기
Layout;레이아웃 이름
List Limit;목록 크기 제한
Menu Colour;메뉴 색상
Menu Prompt;화면에 표시할 메뉴 이름
Menu Toggle;메뉴 토글
Mouse Threshold;마우스 민감도
Overview;설명
Plugins;플러그인
Power Saving;절전
Remove Input;입력 삭제
Reverse Order;역순
Rule;규칙
Scrape Artwork;팬 아트워크 다운로드
Scrape Fanart;외부 팬아트 다운로드
Scrape Flyers/Boxart;박스 아트, 홍보 포스터 다운로드
Scrape Game Logos (Wheel Art);게임 로고 (Wheel Art) 다운로드
Scrape Marquees;Marquee 다운로드
Scrape Snaps;스크린샷 다운로드
Scrape Videos (MAME only);외부 영상 다운로드 (MAME 전용)
Scraper;스크래퍼
Screen Rotation;화면 회전
Screen Saver Timeout;화면 보호기 타임아웃 시간
Selection Delay;선택 지연
Show in Cycle;사이클에 보이기
Show in Menu;목록 관리 메뉴에 보이기
Sort By;목록 정렬 기준
Sort Only;정렬만
Sort and Show;정렬 및 표시
Sound;소리
Startup Mode;시작 모드
Target;규칙의 대상
Title;제목(Title)
Game Stats;게임 통계
Video Decoder;비디오 디코더
Window Mode;화면 모드
Added $1 Collection/Romlist entries;$1 컬렉션/Romlist 항목을 추가했습니다.

# -- indexStrings --
Name;이름
Title;제목(Title)
Emulator;에뮬레이터
CloneOf;원작(CloneOf)
Year;제작연도(Year)
Manufacturer;제작사(Manufacturer)
Category;장르(Category)
Players;플레이어 수(Players)
Rotation;회전
Control;입력 장치(Control)
Status;상태
DisplayCount;디스플레이 수(DisplayCount)
DisplayType;디스플레이 종류(DisplayType)
AltRomname;롬 별칭(AltRomname)
AltTitle;제목 별칭(AltTitle)
Extra;추가
Buttons;버튼
Series;시리즈
Language;언어 설정
Region;지역
Rating;등급
Favourite;즐겨찾기
Tags;태그 정보
PlayedCount;플레이 횟수
PlayedTime;플레이 시간
PlayedLast;마지막 재생 시간
FileIsAvailable;롬파일 존재여부
Shuffle;셔플

# -- filterCompDisplayStrings --
contains;포함
does not contain;미포함
does not equal;불일치
equals;일치
greater than;보다 크다
less than;보다 작다
greater than or equal;크거나 같음
less than or equal;작거나 같음

# -- commandDispStrings --
Back;뒤로 가기
Up;위
Down;아래
Left;270도
Right;90도
Select;선택
Previous Game;이전 게임
Next Game;다음 게임
Previous Page;이전 페이지
Next Page;다음 페이지
Previous Display;이전 목록
Next Display;다음 목록으로
Displays Menu;목록 관리 메뉴
Previous Filter;이전 필터로
Next Filter;다음 필터로
Filters Menu;필터 관리 메뉴
Toggle Layout;레이아웃 변경
Toggle Movie;동영상 켜기/끄기
Toggle Mute;음소거
Toggle Rotate Right;화면 90도 회전
Toggle Flip;화면 180도 회전
Toggle Rotate Left;화면 270도 회전
Exit;확인 후 종료
Exit to Desktop;바탕화면으로 나가기
Reload Layout;레이아웃 새로고침
Reload Config;구성 다시 로드
Reset Window;창 재설정
Screenshot;스크린샷
Random Game;랜덤 게임 선택
Replay Last Game;마지막으로 한 게임 다시 실행
Toggle Fullscreen;전체 화면 전환
Add/Remove Favourite;즐겨하는 게임 추가/삭제
Previous Favourite;이전 즐겨하는 게임
Next Favourite;다음 즐겨하는 게임
Add/Remove Tags;태그 추가/삭제
Screen Saver;화면 보호기
Previous Letter;이전 글자
Next Letter;다음 글자
Intro;소개
Insert Game;게임 삽입
Layout Options;레이아웃 별 옵션
Plugin Options;플러그인 옵션
Custom1;사용자 정의 1
Custom2;사용자 정의 2
Custom3;사용자 정의 3
Custom4;사용자 정의 4
Custom5;사용자 정의 5
Custom6;사용자 정의 6
Custom7;사용자 정의 7
Custom8;사용자 정의 8
Custom9;사용자 정의 9
Custom10;사용자 정의 10
Ambient Soundtrack;배경 음악
Startup Sound;프로그램 시작 소리 파일
Game Return Sound;게임 종료 시 소리 파일

# --uiColorDispTokens --
Indigo;남색
Blue;파란색
Cyan;청록색
Turquoise;청록색
Green;녹색
Acid;산성
Gold;금색
Yellow;노란색
Orange;주황색
Brown;갈색
Rust;녹
Red;빨간색
Pink;분홍색
Magenta;자홍색
Purple;보라색
Grey;회색
Neutral;중립
White;흰색

# --windowModeDispTokens --
Fill Screen;전체 화면 크기로 확장
Fullscreen;전체 화면
Window;창 모드
Borderless Window;테두리 없는 창

# --screenRotationDispTokens --
Flip;180도

# --startupDispTokens --
Show Last Selection;마지막 메뉴 표시
Show Random Selection;무작위 선택 표시
Launch Last Game;마지막 게임 실행
Show Displays Menu;목록 관리 메뉴 표시

# --filterWrapDispTokens --
Wrap within Display;해당 목록의 첫 필터로
Jump to Next Display;다음 목록
No Wrap;아무 것도 하지 않음

# -- settingDispStrings --
Sound Volume;효과음 음량
Ambient Volume;배경 음악 음량
Movie Volume;동영상 음량
Loudness Normalisation;음량 정규화

# -- splash_message --
Generating Romlist;롬 목록을 생성중입니다
Please Wait;잠시 기다려 주십시오
Scraping Artwork;온라인에서 을 다운로드하는 중입니다

# -- confirm_dialog --
Add '$1' to Favourites?;'$1' 게임을 즐겨하는 목록에 추가하겠습니까?
Auto-detect emulators?;에뮬레이터 자동 감지?
Found 1 emulator;에뮬레이터 1개를 찾았습니다
Found $1 emulators;에뮬레이터 $1개를 찾았습니다
No emulators found;에뮬레이터를 찾을 수 없습니다
+$1 more;+$1개 더
Clear Hotkey?;단축키 지우기?
Delete display '$1'?;'$1' 목록을 제거하시겠습니까?
Delete emulator '$1'?;'$1' 에뮬레이터를 삭제하시겠습니까?
Delete filter '$1'?;'$1' 필터를 삭제하시겠습니까?
Delete game '$1'?;'$1' 게임을 삭제하겠습니까?
Delete shortcut '$1'?;'$1' 바로가기를 삭제하겠습니까?
Overwrite existing '$1' list?;기존의 롬 목록 '$1' 에 덮어써도 좋습니까?
Remove '$1' from Favourites?;'$1' 게임을 즐겨하는 목록에서 제거하겠습니까?
Rom path '$1' not found, proceed?;Rom 경로 '$1'을(를) 찾을 수 없습니다. 계속하시겠습니까?
Overwrite existing '$1' mapping?;기존 '$1' 매핑을 덮어쓰시겠습니까?
A display with this name already exists;이 이름의 디스플레이가 이미 존재합니다
Configuration files have been migrated\n to the 'config' folder.\nDelete old files?;구성 파일이 'config' 폴더로 마이그레이션되었습니다.\n이전 파일을 삭제하시겠습니까?

# --input_map_dialog --
Press Hotkey;단축키 누르기
Press Input;키를 누르십시오

# -- edit_dialog --
Enter Display Name;새 목록의 이름을 입력하여 주십시오
Enter Emulator Name;에뮬레이터의 이름을 입력하여 주십시오
Enter Filter Name;필터 이름을 입력하여 주십시오
Enter Tag Name;새 태그 이름을 입력하십시오
Enter Romlist Name;새 롬 목록 이름을 입력하십시오

# -- Titles --
Configure;설정
Default Display Options;기본 표시 옵션
Display Options;표시 옵션
Artwork Options;아트워크 옵션
Control Options;제어 옵션
Emulator Options;에뮬레이터 옵션
Game Options;게임 옵션
Shortcut Options;바로가기 옵션
Exception Options;예외 옵션
Filter Options;필터 옵션
Rule Options;규칙 옵션
Generate Collection/Romlist;롬 목록 생성

# --indexDispStrings --
Executable;실행 파일
Command Arguments;실행 인자
Working Directory;작업 디렉토리
Rom Path(s);롬 파일 경로
Rom Extension(s);롬 파일 확장자
System Identifier;시스템 식별자
Info Source/Scraper;외부 정보 제공자 설정
Additional Import File(s);기타 입력 파일
Non-Blocking Mode Wait;비차단 모드 대기
Exit Hotkey;종료 핫키
Pause Hotkey;단축키 일시 정지

# -- datetime --
_datetime;%Y년%m월%d일 %H:%M:%S
A Moment Ago;잠시 전
Never;안 함
$1 Second;$1초
$1 Minute;$1분
$1 Hour;$1시간
$1 Day;$1일
$1 Minute Ago;$1분 전
$1 Hour Ago;$1시간 전
$1 Day Ago;$1일 전
$1 Week Ago;$1주일 전
$1 Month Ago;$1개월 전
$1 Year Ago;$1년 전
$1 Seconds;$1초
$1 Minutes;$1분
$1 Hours;$1시간 전
$1 Days;$1일
$1 Minutes Ago;$1분 전
$1 Hours Ago;$1시간 전
$1 Days Ago;$1일 전
$1 Weeks Ago;$1주일 전
$1 Months Ago;$1개월 전
$1 Years Ago;$1년 전

# -- help --
_help_art_add;새로운 아트워크 (스크린샷, 타이틀 화면, 기타 동영상 등) 를 추가할 수 있습니다
_help_art_label;지정된 라벨명이 레이아웃에서 사용됩니다
_help_art_path;해당 동영상/그림 파일의 경로입니다
_help_art;레이아웃에서 사용되는 아트워크 등 리소스의 경로를 설정합니다
_help_back;메뉴를 빠져나갑니다
_help_control_add_favourite;현재 선택된 게임을 즐겨찾기에 추가/삭제 하는 키를 설정합니다
_help_control_add_tags;현재 선택된 게임의 태그를 편집하는 키를 설정합니다
_help_control_back;뒤로 가기 버튼을 설정합니다
_help_control_configure;본 '설정 화면' 을 띄우는 키를 설정합니다
_help_control_custom1;사용자 지정 키 1을 설정합니다
_help_control_custom10;사용자 지정 키 10을 설정합니다
_help_control_custom2;사용자 지정 키 2를 설정합니다
_help_control_custom3;사용자 지정 키 3을 설정합니다
_help_control_custom4;사용자 지정 키 4를 설정합니다
_help_control_custom5;사용자 지정 키 5를 설정합니다
_help_control_custom6;사용자 지정 키 6을 설정합니다
_help_control_custom7;사용자 지정 키 7을 설정합니다
_help_control_custom8;사용자 지정 키 8을 설정합니다
_help_control_custom9;사용자 지정 키 9을 설정합니다
_help_control_displays_menu;'목록 메뉴' 를 호출하는 키를 설정합니다
_help_control_down;아래 항목으로 한 칸 이동하는 키를 설정합니다
_help_control_edit_game;선택한 게임을 편집하는 키를 설정합니다
_help_control_exit_to_desktop;본 프로그램을 확인 창 없이 바로 종료하는 키를 설정합니다.
_help_control_exit;본 프로그램을 종료하는 키를 설정합니다
_help_control_filters_menu;'필터 메뉴' 를 호출하는 키를 설정합니다.
_help_control_insert_game;새로운 게임 항목을 삽입하는 컨트롤을 설정합니다.
_help_control_intro;인트로 영상을 표시할 키를 설정합니다
_help_control_joystick_map;프런트엔드의 조이스틱 슬롯을 컴퓨터에 연결된 특정 조이스틱/게임패드 장치에 매핑합니다. (예를 들어 프런트엔드가 항상 "Microsoft X-Box 360 pad"를 조이스틱 0으로 사용하도록 할 수 있습니다.)
_help_control_joystick_threshold;조이스틱 입력 민감도를 설정합니다. 1에서 100까지이며, 클수록 덜 민감합니다
_help_control_layout_options;"레이아웃 옵션" 메뉴를 표시하는 컨트롤을 설정합니다.
_help_control_plugin_options;마지막으로 본 플러그인의 "플러그인 옵션" 메뉴를 표시하는 컨트롤을 설정합니다.
_help_control_left;왼쪽 항목으로 한 칸 이동하는 키를 설정합니다
_help_control_mouse_threshold;마우스 입력 민감도를 설정합니다. 1 에서 100까지이며, 클수록 덜 민감합니다
_help_control_next_display;다음 항목으로 이동하는 키를 설정합니다.
_help_control_next_favourite;다음 즐겨찾기 게임으로 이동하는 키를 설정합니다.
_help_control_next_filter;다음 필터로 이동하는 키를 설정합니다.
_help_control_next_game;다음 게임으로 이동하는 키를 설정힙니다
_help_control_next_letter;다음 글자로 이동하는 키를 설정합니다.
_help_control_next_page;다음 페이지로 이동하는 키를 설정힙니다
_help_control_prev_display;이전 목록으로 이동하는 키를 설정합니다.
_help_control_prev_favourite;이전 즐겨찾기 게임으로 이동하는 키를 설정합니다.
_help_control_prev_filter;이전 필터로 이동하는 키를 설정합니다.
_help_control_prev_game;이전 게임으로 이동하는 키를 설정힙니다
_help_control_prev_letter;이전 글자로 이동하는 키를 설정합니다.
_help_control_prev_page;이전 페이지로 이동하는 키를 설정힙니다
_help_control_random_game;랜덤한 게임을 선택하는 키를 설정합니다.
_help_control_reload_layout;현재 레이아웃을 다시 로드하는 컨트롤을 설정합니다.
_help_control_reload_config;구성 파일을 다시 로드하는 컨트롤을 설정합니다.
_help_control_reset_window;창 크기와 위치를 재설정하는 컨트롤을 설정합니다.
_help_control_replay_last_game;마지막으로 실행했던 게임을 다시 실행하는 키를 설정합니다.
_help_control_right;오른쪽 항목으로 한 칸 이동하는 키를 설정합니다
_help_control_screen_saver;화면 보호기를 활성화하는 키를 설정합니다.
_help_control_screenshot;스크린샷을 찍는 키를 설정합니다.
_help_control_select;현재 선택된 게임을 실행하는 키를 설정합니다.
_help_control_selection_delay;키 반복 시작 전 지연 시간을 밀리초 단위로 설정합니다. 기본값은 400입니다.
_help_control_toggle_flip;화면을 180도 회전하는 키를 설정합니다.
_help_control_toggle_fullscreen;창 모드를 전체 화면과 창 모드로 전환합니다.
_help_control_toggle_layout;레이아웃을 변경하는 키를 설정합니다. (사용중인 레이아웃에 따라 동작 여부가 달라질 수 있습니다.)
_help_control_toggle_movie;동영상 재생을 켜고 끄는 키를 설정합니다.
_help_control_toggle_mute;음소거 키를 설정합니다.
_help_control_toggle_rotate_left;화면을 반시계 방향으로 90도 회전하는 키를 설정합니다.
_help_control_toggle_rotate_right;화면을 시계 방향으로 90도 회전하는 키를 설정합니다.
_help_control_up;위 항목으로 한 칸 이동하는 키를 설정합니다.
_help_display_add_filter;목록에 새로운 필터를 추가합니다
_help_display_add;새로운 목록을 추가합니다
_help_display_delete;목록를 삭제합니다
_help_display_filter;목록의 필터 정보를 관리합니다
_help_display_global_filter;전체 목록에 적용될 전역 필터를 설정합니다.
_help_display_in_cycle;이 목록을 "이전 목록"/"다음 목록" 사이클에 보일 지 여부를 설정합니다
_help_display_in_menu;목록 관리 메뉴에 이 화면을 추가할 지 여부를 설정합니다
_help_display_layout_options;레이아웃에서 지정한 옵션을 바꿀 수 있습니다
_help_display_layout;목록이 사용할 레이아웃을 지정합니다
_help_display_name;목록의 이름을 나타냅니다
_help_display_romlist;목록이 사용할 롬 목록 파일을 지정합니다
_help_display_sel;목록의 설정을 변경합니다
_help_display_edit_default;새 디스플레이에 사용할 기본 옵션을 구성합니다.
_help_displaysmenu_exit;목록 관리 메뉴에 '프로그램 종료' 항목을 넣을 지 여부를 설정합니다
_help_displaysmenu_layout;목록 관리 메뉴에 사용할 레이아웃을 설정합니다
_help_displaysmenu_prompt;목록 관리 메뉴의 이름을 지정합니다 (예: "기종 선택")
_help_displaysmenu;목록 관리 메뉴를 설정합니다
_help_emu_add;새로운 에뮬레이터를 등록합니다.
_help_emu_args;에뮬레이터에 전달할 실행 인자를 설정합니다. 이하의 항목은 각각 알맞게 치환되어 전달됩니다 : [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_emu_delete;에뮬레이터에 대한 항목을 삭제합니다.
_help_emu_executable;에뮬레이터의 실행파일 위치를 지정합니다. $HOME 은 사용자의 홈 디렉토리로 치환됩니다.
_help_emu_exit_hotkey;해당 에뮬레이터를 종료할 전역 핫키를 지정합니다. 해당 핫키가 눌리면 에뮬레이터를 강제종료합니다.
_help_emu_gen_romlist;지정된 롬 파일 경로와 XML 옵션, 추가 파일 (catver.ini 등) 을 이용하여 롬 목록을 생성합니다.
_help_emu_import_extras;롬 파일 목록 생성시에 추가로 활용할 파일을 지정합니다. 장르 (catver.ini) 나 게임 플레이 인원 (nplayers.ini) 정보를 담은 파일을 지정할 수 있습니다.
_help_emu_info_source;mess : MAME 방식의 -listxml, mess : MESS 방식의 -listsoftware, thegamesdb.net : 해당 사이트에서 정보를 취득할 경우, steam : 스팀 사이트에서 정보를 취득할 경우. mess, thegamesdb.net 의 경우 식별자가 해당 방식에 맞게 설정되어 있어야 합니다.
_help_emu_name;에뮬레이터 편집
_help_emu_nb_mode_wait;최소 실행 시간을 초 단위로 지정합니다. 게임 실행 시 적어도 해당 시간 만큼이 지난 후 이 프로그램으로 제어가 돌아가게 됩니다. 보통은 0 으로 설정하면 되지만, 스팀 게임은 적절한 값을 설정해주어야 합니다.
_help_emu_pause_hotkey;에뮬레이터를 일시 중지하는 전역 단축키를 설정합니다. 이 단축키를 누르면 Attract-Mode Plus가 에뮬레이터 프로세스를 일시 중지하고 프런트엔드로 돌아갑니다. 프런트엔드에서 동일한 게임을 다시 선택하면 에뮬레이터 프로세스를 다시 시작할 수 있습니다.
_help_emu_romext;롬 파일들의 확장자 (.zip 등) 을 지정합니다. 세미콜론을 사용해 여러 개를 지정할 수 있습니다.
_help_emu_rompath;에뮬레이터의 롬 파일들이 위치한 경로를 지정합니다. 세미콜론을 사용해 여러 개를 지정할 수 있습니다.
_help_emu_scrape_artwork;TheGamesDB.net 및 mamedb.com 에서 게임 관련 데이터를 다운로드 합니다.
_help_emu_sel_auto_detect;상위 폴더에서 알려진 에뮬레이터를 검색하고 발견된 모든 에뮬레이터에 대한 기본 구성을 생성합니다.
_help_emu_sel_gen_romlist;여러 에뮬레이터의 게임을 포함한 목록을 생성합니다
_help_emu_sel;에뮬레이터의 설정을 변경합니다.
_help_emu_system;에뮬레이터의 식별자입니다. 세미콜론을 사용해 여러 개를 지정할 수 있습니다.
_help_emu_workdir;에뮬레이터의 작업 디렉토리를 설정합니다. 프론트엔드에서 에뮬레이터를 실행하는 데 사용되는 경로입니다. 또한 모든 상대 경로는 이 경로의 하위 경로로 취급됩니다
_help_filter_add_exception;필터의 예외 사항을 추가합니다. 게임이 이 규칙을 만족하고 앞의 필터에서 걸러지지 않았다면 필터에 추가될 것입니다
_help_filter_add_rule;필터에 새 규칙을 추가합니다
_help_filter_delete;본 필터를 삭제합니다.
_help_filter_exception;이 필터의 예외 사항을 설정합니다. 게임이 이 규칙을 만족하면 필터에 추가됩니다. 규칙과 필터는 추가된 순서대로 적용됩니다
_help_filter_list_limit;목록의 크기 제한을 설정할 수 있습니다. 양수는 상위 X 개, 음수는 하위 X 개를 지정하는 데 사용할 수 있습니다. 0 은 무제한입니다.
_help_filter_name;필터의 이름
_help_filter_reverse_order;정렬된 컬렉션/ROM 목록의 순서를 반대로 바꿉니다. 기본 순서는 정보의 경우 "A-Z", 통계의 경우 "내림차순", "정렬 안 함"의 경우 소스 목록 순서입니다.
_help_filter_rule;필터의 규칙을 정의합니다.
_help_filter_sort_by;목록을 정렬할 기준을 설정합니다. 원래 목록 순서대로 표시하려면 '정렬 안 함' 을 선택하십시오.
_help_game_custom_args;이 게임을 실행할 에뮬레이터의 기본 매개변수를 덮어씁니다. 빈 값으로 덮어쓰려면 [nothing]을 입력하여 주십시오. 사용 가능한 매크로는 다음과 같습니다. [name], [romext], [rompath], [emulator], [romfilename], [system], [systemn]
_help_game_custom_executable;이 게임을 실행할 실행 파일을 덮어씁니다
_help_game_delete;롬 목록에서 게임을 제거합니다
_help_game_edit;게임의 정보를 편집합니다
_help_game_overview;게임의 설명을 편집합니다
_help_generator_build;선택한 에뮬레이터를 포함한 롬 목록을 생성합니다
_help_generator_opt;생성된 목록에 포함할 에뮬레이터를 선택합니다
_help_input_action;
_help_input_add;입력 키를 추가합니다
_help_input_default_action;이 키의 기본 행동을 설정합니다
_help_input_delete;해당 입력 키를 삭제합니다
_help_layout_file;일부 레이아웃은 여러 개의 layout*.nut 파일을 제공합니다. 사용할 레이아웃 파일을 선택하세요.
_help_layout_name;레이아웃 구성
_help_main_control;각종 입력을 설정합니다
_help_main_display;목록을 설정합니다
_help_main_emu;에뮬레이터 옵션을 구성합니다.
_help_main_intro;인트로 옵션을 구성합니다.
_help_main_settings;일반 옵션을 구성합니다.
_help_main_plugin;플러그인 옵션을 구성합니다.
_help_main_scraper;스크래퍼 옵션을 구성합니다.
_help_main_screensaver_timeout;몇 초 동안 입력이 없을 시 화면 보호기를 작동시킬 지를 설정합니다. 0 이면 화면 보호기 기능을 정지합니다
_help_main_screensaver;화면 보호기를 설정합니다
_help_main_sound;효과음, 배경음악, 볼륨 조절 등을 설정합니다
_help_misc_anisotropic_filtering;텍스처의 이방성 필터링 수준을 설정합니다. 이렇게 하면 크기 조정된 텍스처의 품질이 향상됩니다.
_help_misc_antialiasing;앤티앨리어싱 수준을 설정합니다.
_help_misc_check_for_updates;Attract-Mode Plus가 시작 시 사용 가능한 업데이트를 확인하고 새 버전이 발견되면 업데이트 알림 대화 상자를 표시할지 여부를 설정합니다.
_help_misc_confirm_exit;프로그램을 정말로 종료할 것인지 묻습니다
_help_misc_confirm_favs;즐겨하는 게임을 추가/삭제할 때에 사용자에게 Yes/No 로 물을 지 여부를 설정합니다
_help_misc_custom_overlay;레이아웃에서 디스플레이, 필터, 태그 및 종료 메뉴에 사용되는 오버레이를 사용자 정의할 수 있도록 허용
_help_misc_exit_command;확인 후 종료 명령으로 프로그램을 끌 때 실행할 외부 명령어 입니다. (예. "sudo shutdown")
_help_misc_exit_message;프런트엔드를 종료하기 위한 대체 메시지 [예: "시스템 종료"]
_help_misc_filter_wrap_mode;목록의 마지막 필터에서 '다음 필터' 키가 입력되었을 때 처리 방식을 결정합니다.
_help_misc_group_clones;모든 게임 클론을 하나의 목록 항목으로 그룹화합니다.
_help_misc_hide_brackets;게임 제목을 표시할 때에, 괄호로 둘러싸인 부분은 표시하지 않을 지 여부를 설정합니다
_help_misc_prefix_modes;"The"와 "Vs."를 이동합니다. 게임 제목 끝에 접두사 추가
_help_misc_hide_console;콘솔 창을 숨깁니다. 이 옵션은 프로그램을 윈도우 GUI상에서 실행할 때에만 적용됩니다. 이미 띄워진 콘솔 창에서 실행하는 경우 (예: 배치 파일에서 실행하는 경우) Attract-Mode Plus 프로세스는 해당 창에 달라붙을 것입니다.
_help_misc_image_cache_mbytes;Attract-Mode Plus 내부 이미지 캐시의 최대 크기(MB)를 설정합니다.
_help_misc_language;언어를 설정합니다
_help_misc_layout_preview;레이아웃 구성 변경 사항을 즉시 표시합니다.
_help_misc_multiple_monitors;다중 모니터 환경을 사용할 지 여부를 설정합니다
_help_misc_power_saving;필요한 경우에만 화면을 다시 그려 전력을 절약합니다. 일부 레이아웃에서는 애니메이션이 끊기거나 Linux에서 정지될 수 있습니다.
_help_misc_quick_menu;같은 버튼을 사용하여 메뉴를 열고 닫을 수 있는지 여부를 설정합니다. 또한, 메뉴를 먼저 닫지 않고도 메뉴 간 전환이 가능합니다
_help_misc_screen_rotation;화면의 기본 회전을 설정합니다.
_help_misc_startup_mode;프로그램이 처음 실행될 때 무엇을 해야하는 지를 설정합니다
_help_misc_track_usage;플레이 내역 (플레이 횟수, 시간) 을 기록할지 설정합니다.
_help_misc_ui_color;Attract-Mode Plus의 사용자 인터페이스에 사용할 색상을 선택하세요.
_help_misc_video_decoder;영상을 재생하는 데 사용할 디코더를 선택합니다
_help_misc_window_mode;창 모드로 동작할지 전체 화면으로 동작할지를 설정합니다.
_help_plugin_command;플러그 인의 실행 파일을 지정합니다
_help_plugin_enabled;플러그 인을 사용할 지 여부를 설정합니다
_help_plugin_name;플러그인 구성
_help_plugin_sel;플러그 인을 설정합니다
_help_rule_comp;필터에 속한 규칙을 설정합니다
_help_rule_delete;해당 규칙을 삭제합니다
_help_rule_target;필터가 게임의 어떤 특성을 가지고 걸러낼 지를 설정합니다
_help_rule_value;필터의 규칙을 정규 표현식으로 설정합니다. 예를 들어 규칙 대상이 '연도' 이며 비교 조건이 '일치' 에 표현식이 "1984" 이면 1984년도에 제작된 게임만 표시합니다. "198." 이면 1980년도에 제작된 모든 게임이 표시됩니다. "(198.)|(199.)" 은 1980년도 및 1990년도의 모든 게임을 표시합니다.
_help_scraper_fanart;온라인에서 팬들이 그린 그림을 다운로드 할지 설정합니다.
_help_scraper_flyers;온라인에서 게임 홍보 포스터 > 박스 아트를 다운로드 할지 설정합니다.
_help_scraper_marquees;온라인에서 Marquee를 다운로드 할지 설정합니다.
_help_scraper_snaps;온라인에서 스크린샷을 다운로드 할지 설정합니다.
_help_scraper_vids;게임 영상을 가져올 지 여부를 설정합니다
_help_scraper_wheels;온라인에서 Wheel Art 형식의 게임 로고를 다운로드 할지 설정합니다.
_help_shortcut_artwork_name;이 바로가기에 연결될 아트워크를 설정합니다. 바로가기를 표시할 때 이 이름으로 된 아트워크를 찾을 것입니다
_help_shortcut_delete;롬 목록에서 이 바로가기를 제거합니다
_help_shortcut_label;이 바로가기의 이름을 설정합니다
_help_shortcut_target;이 바로가기의 목적지를 설정합니다
_help_sound_loudness_normalisation;조용한 미디어의 볼륨을 자동으로 일정한 볼륨 레벨로 높이는 오디오 효과를 활성화합니다.
_help_sound_sel;해당 상황에 재생할 소리를 지정합니다
_help_sound_volume;이 오디오 소스의 볼륨을 설정합니다.

# -- screensaver --

Basic Movie;기본 동영상
Movie Collage;동영상 콜라주
Image Collage;이미지 콜라주
RGB Movie;RGB 동영상
Overlay Artwork;오버레이 아트워크
Play Sound;사운드 재생
Preserve Aspect Ratio;종횡비 유지
Blank Screen Time;빈 화면 시간
Blank Screen Start Command;빈 화면 시작 명령
Blank Screen Stop Command;빈 화면 중지 명령
Play intro;인트로 재생
Detect aspect ratio;종횡비 감지
Default video;기본 비디오
16:9 video;16:9 비디오
4:3 video;4:3 비디오
9:16 video;9:16 비디오
3:4 video;3:4 비디오

# -- extra --
