#@繁體中文 (Traditional Chinese)

# -- generic --
$1 Rule(s);$1 規則
Blank Game;空遊戲
Custom;自訂
Default;預設
Disabled;停用
Empty;空
False;否
Multi;多人
No Sort;不排序
No;否
None;皆否
Off;關閉
On;開啟
OR;或
True;是
Yes;是
Import;進口
Cancel;取消

# -- misc --
Press TAB to Configure;按 TAB 鍵進行配置
Displays Menu Options;主選單選項
Action;動作
Add Artwork;新增插圖資源
Add Emulator;新增模擬器
Add Exception;新增例外條件
Add Filter;新增遊戲過濾
Add Input;新增輸入按鍵
Add Display;新增顯示
Add Rule;新增規則
Allow Exit;允許退出
Anisotropic Filtering;各向異性過濾
Anti-Aliasing (MSAA);抗鋸齒 (MSAA)
Artwork Label;插圖類型
Artwork Name;插圖名稱
Artwork Path;插圖路徑
Auto-detect Emulators;自動檢測模擬器
Check for Updates;檢查更新
Collection/Romlist;收藏集/遊戲清單
Comparison;比對方式
Confirm Exit;結束時確認
Confirm Favourites;操作我的最愛時確認
Controls;輸入控制
Add Tag;添加標籤
Custom Arguments;自訂參數
Custom Executable;自訂執行檔
Custom Overlay;自訂疊加層
Default Action;預設操作
Delete this Display;刪除這個顯示介面
Delete this Emulator;刪除這個模擬器
Delete this Filter;刪除這個遊戲過濾
Delete this Game;刪除這個遊戲
Delete this Rule;刪除這個規則
Delete this Shortcut;刪除這個捷徑
Displays;顯示介面
Emulator Name;模擬器名稱
Emulators;模擬器
Multiple Monitors;多重顯示器
Enabled;啟用
Exception;例外
Exit Attract-Mode Plus;結束 Attract-Mode Plus
Exit Attract-Mode Plus?;要結束 Attract-Mode Plus 嗎?
Exit Command;結束時指令
Exit Message;結束時訊息
Filter Name;過濾名稱
Filter Value;過濾值
Filter Wrap Mode;遊戲過濾循環模式
Filter;篩選
Settings;設定
Global Filter;全域過濾
Group Clones;組克隆
Hide Game Title Brackets;隱藏比賽標題括號
Format Game Title;格式化遊戲標題
Hide Console;隱藏控制台
Image Cache Size;影像快取大小
Insert Command Shortcut;插入命令捷徑
Insert Display Shortcut;插入顯示介面捷徑
Insert Game Entry;插入遊戲項目
Insert Menu Entry;插入選單項目
Joystick $1;操縱桿 $1
Joystick Mappings;搖桿映射
Joystick Threshold;搖桿靈敏度
Language;語言
Layout File;畫面佈局檔案
Layout Preview;佈局預覽
Layout;畫面佈局
List Limit;清單大小限制
Menu Colour;選單顏色
Menu Prompt;選單提示
Menu Toggle;選單切換
Mouse Threshold;滑鼠靈敏度
Overview;簡介
Plugins;插件
Power Saving;省電模式
Remove Input;移除輸入按鍵
Reverse Order;反向排序
Rule;規則
Scrape Artwork;搜刮插圖
Scrape Fanart;搜刮玩家自製插圖
Scrape Flyers/Boxart;搜刮宣傳/盒裝插圖
Scrape Game Logos (Wheel Art);搜刮遊戲圖標 (輪播插圖)
Scrape Marquees;搜刮遊戲招牌插圖
Scrape Snaps;搜刮遊戲捉圖
Scrape Videos (MAME only);搜刮視訊 (僅 MAME)
Scraper;刮擦器
Screen Rotation;螢幕旋轉
Screen Saver Timeout;螢幕保護啟動時間
Selection Delay;選擇延遲
Show in Cycle;顯示在顯示介面循環裡
Show in Menu;顯示在主選單
Sort By;排序方式
Sort Only;僅排序
Sort and Show;排序並顯示
Sound;聲音
Startup Mode;啟動模式
Target;目標
Title;標題
Game Stats;遊戲統計數據
Video Decoder;視訊解碼器
Window Mode;顯示模式
Added $1 Collection/Romlist entries;已新增 $1 收藏/ROM 清單條目

# -- indexStrings --
Name;名稱
Title;標題
Emulator;模擬器
CloneOf;衍生
Year;年份
Manufacturer;製作廠商
Category;類型
Players;遊戲人數
Rotation;旋轉
Control;輸入控制
Status;狀態
DisplayCount;顯示器數量
DisplayType;顯示類型
AltRomname;替代檔案名稱
AltTitle;替代標題名稱
Extra;額外
Buttons;按鍵
Series;系列
Language;語言
Region;區域
Rating;遊戲評比
Favourite;我的最愛
Tags;分類標籤
PlayedCount;遊戲次數
PlayedTime;遊戲時間
PlayedLast;上次遊玩時間
FileIsAvailable;檔案可用性
Shuffle;隨機播放

# -- filterCompDisplayStrings --
contains;包含
does not contain;不包含
does not equal;不等於
equals;等於
greater than;大於
less than;小於
greater than or equal;大於或等於
less than or equal;小於或等於

# -- commandDispStrings --
Back;返回
Up;上移
Down;下移
Left;左移
Right;右移
Select;選擇
Previous Game;上一個遊戲
Next Game;下一個遊戲
Previous Page;上一頁
Next Page;下一頁
Previous Display;上一個顯示介面
Next Display;下一個顯示介面
Displays Menu;主選單
Previous Filter;上一個遊戲過濾
Next Filter;下一個遊戲過濾
Filters Menu;遊戲過濾選單
Toggle Layout;切換畫面佈局
Toggle Movie;切換影片
Toggle Mute;切換靜音
Toggle Rotate Right;切換向右旋轉
Toggle Flip;切換翻轉
Toggle Rotate Left;切換向左旋轉
Exit;結束
Exit to Desktop;結束至桌面
Reload Layout;重新載入佈局
Reload Config;重新載入配置
Reset Window;重置視窗
Screenshot;螢幕截圖
Random Game;隨機選取遊戲
Replay Last Game;重玩最後執行的遊戲
Toggle Fullscreen;切換全螢幕
Add/Remove Favourite;加入/移除我的最愛
Previous Favourite;上一個我的最愛
Next Favourite;下一個我的最愛
Add/Remove Tags;加入/移除分類標籤
Screen Saver;螢幕保護
Previous Letter;上一個文字清單
Next Letter;下一個文字清單
Intro;簡介
Insert Game;插入遊戲
Layout Options;畫面佈局選項
Plugin Options;插件選項
Custom1;自訂 1
Custom2;自訂 2
Custom3;自訂 3
Custom4;自訂 4
Custom5;自訂 5
Custom6;自訂 6
Custom7;自訂 7
Custom8;自訂 8
Custom9;自訂 9
Custom10;自訂 10
Ambient Soundtrack;環境音效
Startup Sound;啟動音效
Game Return Sound;遊戲返回音效

# --uiColorDispTokens --
Indigo;靛藍色
Blue;藍色
Cyan;青色
Turquoise;青綠色
Green;綠色
Acid;酸性
Gold;金色
Yellow;黃色
Orange;橘色
Brown;棕色
Rust;鏽蝕
Red;紅色
Pink;粉紅色
Magenta;洋紅色
Purple;紫色
Grey;灰色
Neutral;中性
White;白色

# --windowModeDispTokens --
Fill Screen;填滿螢幕
Fullscreen;全螢幕
Window;視窗模式
Borderless Window;無邊框視窗

# --screenRotationDispTokens --
Flip;翻轉

# --startupDispTokens --
Show Last Selection;顯示最後選擇的項目
Show Random Selection;顯示隨機選擇
Launch Last Game;最後執行的遊戲
Show Displays Menu;顯示主選單

# --filterWrapDispTokens --
Wrap within Display;循環至第一個遊戲過濾
Jump to Next Display;跳到下一個顯示介面
No Wrap;不循環

# -- settingDispStrings --
Sound Volume;聲音音量
Ambient Volume;環境音量
Movie Volume;影片音量
Loudness Normalisation;音量標準化

# -- splash_message --
Generating Romlist;正在產生收藏集/遊戲清單
Please Wait;請稍待
Scraping Artwork;正在搜刮插圖

# -- confirm_dialog --
Add '$1' to Favourites?;要將「$1」加入我的最愛嗎?
Auto-detect emulators?;自動檢測模擬器?
Found 1 emulator;找出 1 個模擬器
Found $1 emulators;找到售價 $1 美元的模擬器
No emulators found;未找到模擬器
+$1 more;還有$1個
Clear Hotkey?;要清除熱鍵嗎?
Delete display '$1'?;要刪除「$1」顯示介面嗎?
Delete emulator '$1'?;要刪除「$1」模擬器嗎?
Delete filter '$1'?;要刪除「$1」遊戲過濾嗎?
Delete game '$1'?;要刪除「$1」遊戲嗎?
Delete shortcut '$1'?;要刪除「$1」捷徑嗎?
Overwrite existing '$1' list?;要覆寫現有的「$1」清單嗎?
Remove '$1' from Favourites?;要從我的最愛移除「$1」嗎?
Rom path '$1' not found, proceed?;未找到 ROM 路徑“$1”,是否繼續?
Overwrite existing '$1' mapping?;覆蓋現有的“$1”映射?
A display with this name already exists;此名稱的顯示已存在
Configuration files have been migrated\n to the 'config' folder.\nDelete old files?;設定檔已遷移到 'config' 資料夾。\n是否刪除舊檔案？

# --input_map_dialog --
Press Hotkey;請按下要使用的熱鍵
Press Input;請按下要使用的輸入按鍵

# -- edit_dialog --
Enter Display Name;輸入顯示介面名稱
Enter Emulator Name;輸入模擬器名稱
Enter Filter Name;輸入遊戲過濾名稱
Enter Tag Name;輸入分類標籤名稱
Enter Romlist Name;輸入遊戲清單名稱

# -- Titles --
Configure;設定
Default Display Options;預設顯示選項
Display Options;顯示選項
Artwork Options;美術素材選項
Control Options;控制選項
Emulator Options;模擬器選項
Game Options;遊戲選項
Shortcut Options;快捷鍵選項
Exception Options;例外選項
Filter Options;篩選選項
Rule Options;規則選項
Generate Collection/Romlist;產生收藏集/遊戲清單

# --indexDispStrings --
Executable;執行檔
Command Arguments;命令參數
Working Directory;工作目錄
Rom Path(s);遊戲檔路徑
Rom Extension(s);遊戲副檔名
System Identifier;系統識別
Info Source/Scraper;資訊來源/搜刮器
Additional Import File(s);附加匯入檔案
Non-Blocking Mode Wait;非阻塞等待模式
Exit Hotkey;結束熱鍵
Pause Hotkey;暫停熱鍵

# -- datetime --
_datetime;%Y-%m-%d %H:%M:%S
A Moment Ago;片刻前
Never;從不
$1 Second;$1 秒
$1 Minute;$1 分鐘
$1 Hour;$1 小時
$1 Day;$1 天
$1 Minute Ago;$1 分鐘前
$1 Hour Ago;$1 小時前
$1 Day Ago;$1 天前
$1 Week Ago;$1 週前
$1 Month Ago;$1 個月前
$1 Year Ago;$1 年前
$1 Seconds;$1 秒
$1 Minutes;$1 分鐘
$1 Hours;$1 小時
$1 Days;$1 天
$1 Minutes Ago;$1 分鐘前
$1 Hours Ago;$1 小時前
$1 Days Ago;$1天前
$1 Weeks Ago;$1 週前
$1 Months Ago;$1 個月前
$1 Years Ago;$1 年前

# -- help --
_help_art_add;新增插圖資源 (遊戲招牌插圖、遊戲捉圖、其它...)
_help_art_label;設定用來識別插圖資源類型的識別名稱 (使用在畫面佈局)
_help_art_path;設定插圖資源檔案所存放的路徑 (多重路徑可用分號間隔)
_help_art;一種提供給畫面佈局使用的插圖資源
_help_back;離開選單
_help_control_add_favourite;設定「加入/移除當前遊戲至我的最愛」的控制鍵
_help_control_add_tags;設定「加入/移除當前遊戲至分類標籤」的控制鍵
_help_control_back;設定「返回」的控制鍵
_help_control_configure;設定「顯示設定選單」的控制鍵
_help_control_custom1;設定「自訂 1」的控制鍵
_help_control_custom10;設定「自訂 10」的控制鍵
_help_control_custom2;設定「自訂 2」的控制鍵
_help_control_custom3;設定「自訂 3」的控制鍵
_help_control_custom4;設定「自訂 4」的控制鍵
_help_control_custom5;設定「自訂 5」的控制鍵
_help_control_custom6;設定「自訂 6」的控制鍵
_help_control_custom7;設定「自訂 7」的控制鍵
_help_control_custom8;設定「自訂 8」的控制鍵
_help_control_custom9;設定「自訂 9」的控制鍵
_help_control_displays_menu;設定「顯示主選單」的控制鍵
_help_control_down;設定「下移選項」的控制鍵
_help_control_edit_game;設定「編輯當前選項」的控制鍵
_help_control_exit_to_desktop;設定「結束並立即返回桌面」的控制鍵
_help_control_exit;設定「結束 Attract-Mode Plus」的控制鍵
_help_control_filters_menu;設定「顯示遊戲過濾選單」的控制鍵
_help_control_insert_game;設定插入新遊戲條目的控制項。
_help_control_intro;設定「顯示啟動視訊」的控制鍵
_help_control_joystick_map;指定電腦的搖桿裝置在 Attract-Mode Plus 裡的搖桿順序 (例: 你可以強制這個前導永遠使用 "Microsoft X-Box 360 pad" 作為搖桿 0)
_help_control_joystick_threshold;這個設定用來定位搖桿移動的靈敏度,數值從 1 到 100 (100 為最大值)。
_help_control_layout_options;設定顯示「佈局選項」選單的控件
_help_control_plugin_options;設定顯示上次查看的插件的「插件選項」選單的控件
_help_control_left;設定「左移選項」的控制鍵
_help_control_mouse_threshold;這個設定用來定位滑鼠移動的靈敏度,數值從 1 到 100 (100 為最大值)。
_help_control_next_display;設定「移至下一個顯示介面」的控制鍵
_help_control_next_favourite;設定「移至下一個我的最愛」的控制鍵
_help_control_next_filter;設定「移至下一個遊戲過濾」的控制鍵
_help_control_next_game;設定「移至下一個遊戲」的控制鍵
_help_control_next_letter;設定「移至下一個文字清單」的控制鍵
_help_control_next_page;設定「移至下一頁」的控制鍵
_help_control_prev_display;設定「移至上一個顯示介面」的控制鍵
_help_control_prev_favourite;設定「移至上一個我的最愛」的控制鍵
_help_control_prev_filter;設定「移至上一個遊戲過濾」的控制鍵
_help_control_prev_game;設定「移至上一個遊戲」的控制鍵
_help_control_prev_letter;設定「移至上一個文字清單」的控制鍵
_help_control_prev_page;設定「移至上一頁」的控制鍵
_help_control_random_game;設定「從當前清單隨機選取遊戲」的控制鍵
_help_control_reload_layout;設定用於重新載入目前佈局的控件
_help_control_reload_config;設定用於重新載入配置的控製文件
_help_control_reset_window;設定用於重置視窗大小和位置的控件
_help_control_replay_last_game;設定「重玩最後執行的遊戲」的控制鍵
_help_control_right;設定「右移選項」的控制鍵
_help_control_screen_saver;設定「進入螢幕保護模式」的控制鍵
_help_control_screenshot;設定「螢幕截圖」的控制鍵
_help_control_select;設定「執行當前選項」的控制鍵
_help_control_selection_delay;設定按鍵重複開始前的延遲時間 (以毫秒為單位),預設值為 400
_help_control_toggle_flip;設定「將顯示畫面旋轉 180 度」的控制鍵
_help_control_toggle_fullscreen;在全螢幕和視窗模式之間切換
_help_control_toggle_layout;設定「切換畫面佈局」的控制鍵 (主題資料夾中含有多個畫面佈局檔案時才會進行切換)
_help_control_toggle_movie;設定「切換影片播放」的控制鍵
_help_control_toggle_mute;設定「切換聲音靜音」的控制鍵
_help_control_toggle_rotate_left;設定「將顯示畫面向左旋轉 90 度」的控制鍵
_help_control_toggle_rotate_right;設定「將顯示畫面向右旋轉 90 度」的控制鍵
_help_control_up;設定「上移選項」的控制鍵
_help_display_add_filter;新增一個遊戲過濾至這個顯示介面的遊戲過濾集
_help_display_add;新增一個新的顯示介面
_help_display_delete;刪除這個顯示介面
_help_display_filter;在這個顯示介面的遊戲過濾集中設定這個遊戲過濾
_help_display_global_filter;設定一個適用於整個收藏集/遊戲清單的全域遊戲過濾規則
_help_display_in_cycle;在切換「上一個顯示介面/下一個顯示介面」循環裡加入這個顯示介面
_help_display_in_menu;在主選單裡顯示這個顯示介面
_help_display_layout_options;設定畫面佈局所提供的設定選項
_help_display_layout;設定這個顯示介面所要使用的畫面佈局
_help_display_name;這個顯示介面的標題名稱
_help_display_romlist;設定這個顯示介面所要使用的收藏集/遊戲清單
_help_display_sel;設定顯示介面
_help_display_edit_default;配置新顯示器的預設選項
_help_displaysmenu_exit;設定結束項目是否顯示在主選單
_help_displaysmenu_layout;設定主選單所使用的畫面佈局 (設為「Default」為使用程式內建的主選單)
_help_displaysmenu_prompt;主選單的提示訊息 (例: 選擇系統)
_help_displaysmenu;設定主選單的設定選項
_help_emu_add;新增一個新的模擬器
_help_emu_args;這個模擬器的命令行參數 (可用的變數: [name]、[romext]、[rompath]、[emulator]、[romfilename]、[system]、[systemn]、[workdir]、[nothing],以及任何有效的其它標記,詳情請參考 layout 文件)
_help_emu_delete;刪除這個模擬器項目
_help_emu_executable;這個模擬器的完整路徑及檔名 (可用的變數: $HOME = 用戶主目錄、$PROGDIR = Attract-Mode Plus 程式目錄,Windows 系統額外還有符合系統環境變數的 %SYSTEMROOT% 及 %PROGRAMFILES% 可以使用)
_help_emu_exit_hotkey;設定一個全域熱鍵來結束模擬器 (當這個熱鍵按下時,Attract-Mode Plus 將會終結這個模擬器處理程序)
_help_emu_gen_romlist;使用設定裡的遊戲檔路徑、副檔名、XML 及附加匯入檔案裡的資料來產生遊戲清單
_help_emu_import_extras;設定產生遊戲清單時所要使用的附加檔案路徑。 支援的檔案: catver.ini (遊戲分類)、nplayers.ini (玩家人數)、series.ini (系列遊戲)、languages.ini (遊戲語言) 及 mame.xml (多個檔案路徑可用分號間隔)
_help_emu_info_source;使用 "listxml" 為 mame -listxml 輸出、"listsoftware" 為 mame/mess -listsoftware 輸出、"thegamesdb.net" 為從 thegamesdb.net 搜刮資料、"steam" 為從 steam 安裝中讀取、"scummvm" 為當模擬器為 scummvm 時使用 (使用 "listsoftware" 及 "thegamesdb.net" 必須正確設定系統識別名稱)
_help_emu_name;編輯模擬器
_help_emu_nb_mode_wait;若此值非 0,這個模擬器將會執行在非阻塞模式 (Attract-Mode Plus 將會等待至所設定的秒數後才將視窗焦點從模擬器轉回並喚醒 Attract-Mode Plus,這對於正確啟動 Steam 之類的程序是必要的,在你了解它的作用前請保持為 0)
_help_emu_pause_hotkey;設定一個全域熱鍵來暫停模擬器 (當這個熱鍵按下時,Attract-Mode Plus 將會暫停這個模擬器處理程序並返回前導,這個模擬器處理程序可在再次選擇同樣遊戲後繼續)
_help_emu_romext;這個模擬器的遊戲副檔名 (例: .zip),若遊戲在個別的子目錄時請設為 "<DIR>" (多個副檔名可用分號間隔)
_help_emu_rompath;這個模擬器的遊戲檔存放路徑 (多個路徑可用分號間隔)
_help_emu_scrape_artwork;從網路搜刮這個模擬器所沒有的遊戲插圖
_help_emu_sel_auto_detect;此功能將掃描父資料夾中已知的模擬器,並為每個找到的模擬器產生預設配置
_help_emu_sel_gen_romlist;為多個模擬器產生收藏集/遊戲清單
_help_emu_sel;設定模擬器
_help_emu_system;這個模擬器的系統識別名稱 (多個識別名稱可用分號間隔)
_help_emu_workdir;這個模擬器的工作目錄 (Attract-Mode Plus 會將工作目錄作為執行模擬器的開始位置,一些在這個前導裡以相對路徑所設定的資源路徑也都會以此工作目錄為開始位置)
_help_filter_add_exception;新增例外條件至這個遊戲過濾 (若遊戲符合這個例外條件且未被先前的規則過濾到,它將會列在這個遊戲過濾裡)
_help_filter_add_rule;新增一個規則至這個遊戲過濾 (遊戲必須符合所有過濾規則或例外條件才會列在這個遊戲過濾)
_help_filter_delete;刪除這個遊戲過濾
_help_filter_exception;設定這個遊戲過濾的例外條件 (若遊戲符合這個例外條件,它將會列在這個遊戲過濾裡)
_help_filter_list_limit;設為 0 為無限制,若你想限制排序清單的數量請設為 0 之外的數值 (例: "10" 將會取得前 10 個項目,"-25" 將會取得最後 25 個項目)
_help_filter_name;這個遊戲過濾的名稱
_help_filter_reverse_order;反轉已排序的收藏集/ROM清單的順序。預設順序為：資訊依「A到Z」排序,統計資料依「由大到小」排序,或依來源清單順序排序 (不排序)。
_help_filter_rule;設定這個遊戲過濾的規則 (遊戲必須符合所有過濾規則或例外條件才會列在這個遊戲過濾)
_help_filter_sort_by;設定用來排序收藏集/遊戲清單的遊戲資訊屬性 (設為「不排序」則保持收藏集/遊戲清單原始的排序順序)
_help_game_custom_args;設定此項目將會替這個遊戲覆寫預設的命令參數,設為 [nothing] 則會覆寫為無參數 (可用的變數: [name]、[romext]、[rompath]、[emulator]、[romfilename]、[system]、[systemn])
_help_game_custom_executable;設定此項目將會替這個遊戲覆寫預設的執行檔
_help_game_delete;從遊戲清單刪除這個遊戲
_help_game_edit;編輯這個遊戲的資訊
_help_game_overview;編輯遊戲簡介
_help_generator_build;開始為已選擇的模擬器建立遊戲清單
_help_generator_opt;設定要為哪些模擬器建立遊戲清單
_help_input_action;目前所設定的 Attract-Mode Plus 操作控制
_help_input_add;新增一個輸入映射給這個操作控制使用
_help_input_default_action;設定這個操作控制的預設操作功能
_help_input_delete;移除這個輸入映射
_help_layout_file;一些畫面佈局主題提供多個 layout*.nut 檔案,須選擇要使用的畫面佈局檔案。
_help_layout_name;配置佈局
_help_main_control;設定搖桿、鍵盤及滑鼠按鍵用來操作 Attract-Mode Plus 功能
_help_main_display;設定遊戲清單/畫面佈局群組 (又稱顯示介面),用於在 Attract-Mode Plus 裡循環顯示。
_help_main_emu;配置模擬器選項
_help_main_intro;配置介紹選項
_help_main_settings;配置常規選項
_help_main_plugin;設定插件選項
_help_main_scraper;配置抓取器選項
_help_main_screensaver_timeout;設定切換至螢幕保護模式前的等待秒數 (0 為停用)
_help_main_screensaver;設定螢幕保護
_help_main_sound;設定聲音音量、操作事件聲音對映及環境音效
_help_misc_anisotropic_filtering;設定紋理的各向異性過濾等級。這將提高縮放紋理的品質。
_help_misc_antialiasing;設定抗鋸齒級別
_help_misc_check_for_updates;設定 Attract-Mode Plus 是否應在啟動時檢查可用更新,並在發現新版本時顯示更新通知對話方塊。
_help_misc_confirm_exit;結束 Attract-Mode Plus 前先確認?
_help_misc_confirm_favs;加入/移除我的最愛前先確認?
_help_misc_custom_overlay;允許佈局自訂用於顯示、篩選、標籤和退出選單的疊加層
_help_misc_exit_command;設定當結束 Attract-Mode Plus 時所要執行的命令 [例: "sudo shutdown"]
_help_misc_exit_message;設定當結束 Attract-Mode Plus 時所要顯示的訊息 [例: "關機"]
_help_misc_filter_wrap_mode;設定當使用「下一個遊戲過濾」或「上一個遊戲過濾」切換至底時所要執行的動作
_help_misc_group_clones;將同一遊戲的所有克隆版本分組到一個列表項目下
_help_misc_hide_brackets;顯示遊戲標題時隱藏括號內容
_help_misc_prefix_modes;移動“The”和“Vs”。遊戲標題末尾的前綴
_help_misc_hide_console;啟動時隱藏主控台視窗 (註: 這僅在從 Windows 介面啟動 Attract-Mode Plus 時能正常運作,若從命令提示字元視窗啟動 (例: 批次檔),這個處理程式將始終附加並輸出到這個命令提示字元視窗)
_help_misc_image_cache_mbytes;設定 Attract-Mode Plus 內部影像快取最大值大小 (以 MB 為單位)
_help_misc_language;選擇 Attract-Mode Plus 使用者介面所要使用的語言
_help_misc_layout_preview;立即顯示佈局配置變更
_help_misc_multiple_monitors;為 Attract-Mode Plus 啟用多螢幕支援 (設定為「否」可能減少執行遊戲時的螢幕閃爍問題)
_help_misc_power_saving;僅在需要時才重新繪製螢幕進而達成省電 (可能造成一些畫面佈局動畫卡頓或在 Linux 系統畫面凍結)
_help_misc_quick_menu;設定是否可以使用相同按鈕開啟和關閉選單。還可以在選單之間切換,而無需先關閉它們
_help_misc_screen_rotation;設定畫面的基本旋轉角度
_help_misc_startup_mode;設定 Attract-Mode Plus 啟動時所要顯示的選單項目
_help_misc_track_usage;設定 Attract-Mode Plus 是否要記錄使用狀況 (每個遊戲的遊戲時間及遊戲次數)
_help_misc_ui_color;選擇在 Attract-Mode Plus 的使用者介面中使用的顏色
_help_misc_video_decoder;設定視訊播放時所要使用的解碼器 (若存在多個解碼器)
_help_misc_window_mode;設定 Attract-Mode Plus 所要使用的顯示模式
_help_plugin_command;這個外掛所關聯的外部執行檔
_help_plugin_enabled;設定這個外掛是否要啟用
_help_plugin_name;設定插件
_help_plugin_sel;設定外掛
_help_rule_comp;這個過濾規則的比對方式
_help_rule_delete;刪除這個過濾規則
_help_rule_target;設定所要過濾的遊戲資訊內容
_help_rule_value;設定所要過濾的正規表達式過濾值 (例: 若過濾目標為「年份」且比對方式為「等於」,過濾值為「1984」時將會比對所有年份為 1984 的遊戲、「198.」將會比對所有 80 年代的遊戲、「(198.)|(199.)」將會比對所有 80 及 90 年代的遊戲)
_help_scraper_fanart;設定是否要搜刮玩家自製插圖
_help_scraper_flyers;設定是否要搜刮宣傳/盒裝插圖
_help_scraper_marquees;設定是否要搜刮遊戲招牌插圖
_help_scraper_snaps;設定是否要搜刮遊戲捉圖
_help_scraper_vids;設定是否要搜刮遊戲視訊
_help_scraper_wheels;設定是否要搜刮遊戲圖標 (輪播插圖)
_help_shortcut_artwork_name;提供要與此捷徑關聯的插圖名稱 (Attract-Mode Plus 將會在顯示這個捷徑時嘗試使用這個名稱載入插圖資源)
_help_shortcut_delete;從遊戲清單刪除這個捷徑
_help_shortcut_label;編輯這個捷徑的標題名稱
_help_shortcut_target;編輯這個捷徑的目標顯示介面
_help_sound_loudness_normalisation;啟用自動將音量較小的媒體提升至統一音量的音訊效果
_help_sound_sel;分配這個操作事件所要使用的音訊檔案
_help_sound_volume;設定此音訊來源的音量

# -- screensaver --

Basic Movie;基本影片
Movie Collage;影片拼貼
Image Collage;影像拼貼
RGB Movie;RGB 影片
Overlay Artwork;疊加藝術作品
Play Sound;播放聲音
Preserve Aspect Ratio;保持寬高比
Blank Screen Time;黑屏時間
Blank Screen Start Command;黑屏開始命令
Blank Screen Stop Command;黑屏結束指令
Play intro;播放片頭
Detect aspect ratio;偵測寬高比
Default video;預設影片
16:9 video;16:9 影片
4:3 video;4:3 影片
9:16 video;9:16 影片
3:4 video;3:4 影片

# -- extra --
